apiVersion: ENC[AES256_GCM,data:Ims=,iv:9EHxLOde2wyoqmduHeRv5xtgvRnladdbC3x51L0sMEA=,tag:r2KRPAj6zwLU1yF55FMsuw==,type:str]
kind: ENC[AES256_GCM,data:CcWTDmNC,iv:XZ+zH2MYQ3wl4L1k7zDRgAzvv7Oh8J6GIUUaxOGH1bQ=,tag:g1Apr5cZueB28bdqdSRgVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:z1ZyiQErvgPmwTcSB5YkNzM7zZU=,iv:+cJhv/1AWksdJlzs/G++Y3bLgMyeigyc0Ja9T4qDH+Y=,tag:x1r6yq7Lygg0M3IVhsBqZA==,type:str]
    namespace: ENC[AES256_GCM,data:bY6PTQw=,iv:NByRs/w2H9Rz/NrESBkFW5xpu+S0TR6ao6ZYR8mjDe0=,tag:a5WKiZSQVznY99QxRP/jzQ==,type:str]
stringData:
    kafka-connect-password: ENC[AES256_GCM,data:5t9rurMpbmfuV0CvgLaIQfgPmXa2PhRSpXcaxl6zfTO2UaU5eyzCoIRsy2g=,iv:6OxNNhPn/vn/8j+9qlgm5ooj8J1OHPq11T5bYyljzjo=,tag:343B8iWQ+xUI0PFVEU0UbQ==,type:str]
    kafka-console-password: ENC[AES256_GCM,data:9+lDx9rw1CGnMBDN2pCZzRZACX+lqzt3o9m2dkDTPI+b/gSnLdeXWe9YmQ==,iv:N1Igd0khY1QH7tu5LMaVsr2zk2eum+gbLt02evqXaz0=,tag:wMxn1k72iDgKuWSJjK8l2g==,type:str]
    snowplow-collector-password: ENC[AES256_GCM,data:CA49ahuOfjxl1X741qXcPqBKTefnc+EpIhzqj0KOKnhskEHN/Jz8dY9mlLo=,iv:keZPgugR4ZohsElRhpBajPDaYo4qV19ttfXxPK74AB4=,tag:2l/fe9EIJWojnU58fE6cRw==,type:str]
    snowplow-enrich-password: ENC[AES256_GCM,data:uWEtRnMxx3qpQ8lv+/cKdN/dySgJ6vo9Z4fq08do2/oINCUpuue6BHDvLqs=,iv:JGGE3nR5Ww0wKmPAUAn7RFO6pd1GPM939WwdGBk2hSE=,tag:fiVWlY6tYM16l6mYfwI9Cg==,type:str]
    clickhouse-snowplow-password: ENC[AES256_GCM,data:81saOstDhsQmTj7NlSJmHMhxbMeEddOj3C3UQr7dv0NGlSEf/fH7MQ==,iv:3CueF1MoZOG6e99O2SQCAtgm5Yjv3BOX5eGxZm4EMl4=,tag:5UEKhZLHljRaKsyV45KPtQ==,type:str]
type: ENC[AES256_GCM,data:aNsuwClF,iv:4tA316+WQMd3ap5LF+SVEqp1HzxN1h1sFT6SZF4BZ1c=,tag:jjWMWVT3DjNuTCk8MAB05w==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RUZIOFJrUzQvRmg0bW9S
            QWl6czNka2NxajROWVlBRUVtOW5IL3VGOG5RCjlxdktEUHRmdldCalRHczdMcHpF
            eUw2ZW1HUVVRRTlCVGpZeHFEditLc1kKLS0tIElLSlRLSlc5L0JoVFVGVVkrOTVU
            cDMvdmlBeHJoWVBIZUU3T0pRWU4wK1EKBg9R2gRCiWltS+An9H3ke1O8cVzltyq/
            q9JkAUic0qHJ89BXRX9yQ8uiajbsZZmQhhNt4v9YSuSWagvh1szrLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T16:49:31Z"
    mac: ENC[AES256_GCM,data:+KW7VBiWyusGN4OIokowhCnep4EGlZgzjIgY8+nzvWGeC2IuC9P6zJIxpEAjRGXlNZS7p7IKFso9YD8iU6FQOGxiTTQ5R3CDJlj0rivmIH+0v+l5j+gfCK3YQILz0aCAWXR1z7K0VC5GhxFXj+JRy2lqL4SVWmLZoT4umUHLfgM=,iv:rQUpoVEJVwKPIi7gr6nFLxHP5CEznPdfK9Tpkqr6Fv0=,tag:rrOkPJDemIvVw9UrFd9IKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
