apiVersion: ENC[AES256_GCM,data:Poo=,iv:Cg1lI513TLOdWHyhom1PJ9qs+XTZAzIGOAw1vf4jk7k=,tag:l8QzPGuG/WZPso8HFi5S8w==,type:str]
kind: ENC[AES256_GCM,data:XzXKwmbT,iv:gJYvdQI8wuXWrZ7qRvGXpZ65Y7YEwyp/QA/l3LVMo88=,tag:l7mDnS8nMBlc9YwOWDrpEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9+Y7SaPFEBpEAPzXigUTkBVSlxU=,iv:WZfpffn2WnCp0kOqfyo6n2XNYSWtkUxdiiA+Ft5YWJ4=,tag:M4iNEhtagydNQ5kapzpb/w==,type:str]
    namespace: ENC[AES256_GCM,data:4P/rmtM=,iv:iTZRO7ntU5UxbzRY0d+oTgSLaDtzVw8ioh4/FiwFEoU=,tag:qqWI/y8qlljEGCaLNqmeCA==,type:str]
stringData:
    kafka-connect-password: ENC[AES256_GCM,data:kc+6OgO9VKjV9aYyhJyQVHX4Y4JO+5yperLzWy7lcUFSSA8dDnf/6IACd64=,iv:snOFYT+tiZcpLECD8nfa8T6B9IkcYze78QJUkOjHtns=,tag:yaWqtw3nnDQSXLhB2U4lng==,type:str]
    kafka-console-password: ENC[AES256_GCM,data:J/Lc1vSpEQQekJ6VLLkZbeah2Qs5f1DeRej1obBVX/qGcRk49xYw0YBWgw==,iv:DFn4Po3kQUJsa/KwEWyw5nXzCswJW84EWDRVR9dmqpY=,tag:dO/wuTRf+qux+jj1gQqnNA==,type:str]
    snowplow-collector-password: ENC[AES256_GCM,data:KgGm3v6q1SDPra3V6sir0MEkEOHyBK9j4nxh/YIkSk5PxPMBdnv0aVd0ZQ8=,iv:G7CNlBTP5UfdADuvqpQ94e+13Ql1TVJBK3qtFfY4BWk=,tag:kFU8/qx3zoxhG/G9rpOY5g==,type:str]
    snowplow-enrich-password: ENC[AES256_GCM,data:YPVUe7K0PHVZfMGVJTHAXVvzpUXW9P0j8BiFOj1DnZlvSd+bSSIA5a55oqw=,iv:+nQCIgYq1306mkI9axTT9a6zHSWvre7hKqYEqYNlotw=,tag:j+puKG97X906Fg1iXrb7Cw==,type:str]
type: ENC[AES256_GCM,data:M8Lzq39u,iv:ml6MYVsiiRVhC2yWzPv5GVjUOFrOuJiJ8GMaOXfrGUY=,tag:WSyVolBZsO+MfBwzlcDe9Q==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNmh1UTRLYVhEM2w0NHVZ
            dlhaajRSL1BOTDdFNlBiVDA2SWR6UWF5RkFvCmxqOERFOEt1emlhNzFlMVlZQ2x4
            TmJLME9hMWVRR3c1ZExVMnBzVUlxNG8KLS0tIDNwTzQwdzVxL2Y0cE1tK0ZhTzBh
            dm0xcURSKzFPTWt4MVppRUtLRHZIU0kKft2ZldEHW2XgSL4W0pZ+62cb+sUr1XhS
            TbsuOVSkhNsd33YQg8JkSP2ZrcPpn/b5BuJBKNrokCJu6h7wzHOoEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T16:10:48Z"
    mac: ENC[AES256_GCM,data:YiFQ6JY1CyMHkF2HchdJu0fMijZ63T+vmqbowVIluLlFCldeAw4jtmuusqL3EmVOrU8+a6GxQlRTj9PjlML0l5Jog8ia6swWIw7JggkUqUR5oTwfbzBT0M8ITyvD/3VOVR4mRGUYVx+D4iZxlUD7Y6vrE+8AQ+iDG6cfSBW5edA=,iv:htQQRdPKdZtewvk9fgV5WnXKdCqQJZS8ScTwr2q65og=,tag:zFUadkChpu+aqSTqpFxHzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
