apiVersion: ENC[AES256_GCM,data:yVc=,iv:eU20ZxqOg8ZnJ34HrbnGMp+TZ93kMnfvZGEnV2IWg7c=,tag:7+z3afXfEPy/OysgaJOk+A==,type:str]
kind: ENC[AES256_GCM,data:DwbNAcLU,iv:IL6qqkrfGyIb0snPscEXNd6hCLNrYJJT0I4V7XELd7A=,tag:D9ZQrXNfSOQANgolA7w8mQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bLFRQ0AZmeXOTuAZH7Hp,iv:MvcqFDsvoqlBqjMtfXF6yVasSKSmVajztTkodkLK4ZU=,tag:jypC9lIi72tgHJAEOanuzw==,type:str]
    namespace: ENC[AES256_GCM,data:a4Wn/LOOFj2qMIyQsIFs,iv:oOTgu3Dg5hJiuHDdsbxxCY1i1lAsndcmjplKcCsuEug=,tag:9o3eha9tk28DTRV6M1Fvog==,type:str]
type: ENC[AES256_GCM,data:3g+1mbpm,iv:NobFQVOIEAy2nkUQWK/Nh0PCLI97pRS+0oLLVCgX+IU=,tag:/7SYVsdETNa27dd0AceJZw==,type:str]
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:JGODwtqE5fIAf3qrec/0hCSjaz4oZX9zkO6poqIn8Lib4MkfDPY97eVlOQ==,iv:PRqzW/0YmVqU6R6D/BOTEShv7V0b58MzEqZF7ebHTMI=,tag:qavh2vV4HNISMtcm4Ifghw==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:uGXrMa+o,iv:Zu3b0AndXM9Jk1me0yCoT4B38Isay/B6G3lw9+j8uww=,tag:llJUxbNysHtL/jw2zwmkqw==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:FNhUgrr2TM4XASEhJr8k,iv:fzIZfw1RC+2Lrst8w3/K5exLI7igr4Ju9YxXAmP1dpM=,tag:MIY5GZ3VCz2ne7CWd4yL3w==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:9xTf7A/8,iv:lRRORXgUcSNflLggoR0zDJUwlytDSdUUfPNnFhktHwE=,tag:V1nb2bvv3GrxI9NvODFhXw==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:geuC,iv:D26neYOCw2XMWZB8fwYZudM4VTNG2pCowO8TnC/EncI=,tag:gji5FsziStI675M8M8GDpg==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:GmDgC/oP0Q==,iv:QwuBSB/k3wenUZBBk1wwZxabUIH4LtAJ8ZQej4vQF1M=,tag:25vJRqlP/AouU0PQVg3XIA==,type:str]
    #ENC[AES256_GCM,data:E1XZfOFib1Houq+6WvdpJgKjmWeiUF1eXkGfVXiYgD8lnGtcK3H9cxNCGmSGBXH6c0O7iMFEnutMtBurUukXOye4tuVBFgQH,iv:i1yF1cEK/Zks9TtRCn+IzBqO+dm95KgaYB6QB7pE1nc=,tag:Zfoz3Gm9TRa108hzq9rhpQ==,type:comment]
    #ENC[AES256_GCM,data:mwmtG0HI58UwsDWZ4zAZyMi9yjwQ3Oo1TWH9qOxRTLRYEcdLC21gxGVgR1shfUsisqjdHXp47jh3N9AAh8nmJUo0nOas0OvVtag=,iv:QFZiBuOyvC96mYm8kt1I1Az2eWwGMO/Bh8fnrnQYg00=,tag:cNwK3fN3yFSDoAqdLbFuGw==,type:comment]
    #ENC[AES256_GCM,data:AumW1z7eUpFPcd4FUEdDfu2p3wGsdft9f/1LGXG8W7U5jiPoCFBa/Cpjy3R2y01CTns2vY/0hv6ZUfyll3lh6CiEKpkGCW8=,iv:frBNLQUDWuz8Zk2pPkoXHCBUsp2k9DsYedIAXec7Hjc=,tag:UwDD24CJq50W1Q6nABEtbA==,type:comment]
    #ENC[AES256_GCM,data:yPTprlgU4t3leXNvq4knDzPOx7PkTHndNntFn94XVKktFqle7pJzJWo4RKNth543Bq4TuP+eCQEvG7I=,iv:m1NriKY4v8rndwuy2LjVIG/7XATvI6/o1/b0exe84Js=,tag:MSrT+dVsxEQ/wYeZa4mGmA==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaV2hHaklJNlVidWZQNFRa
            bGlJb0p5YTRUa0RQMzRMSmw5cmg1aHcwMEFnCmFnWUNvVkNvUzYrU25ydi8vRnQv
            ckFtelowS0ExVVJBRUlWMmJkbWRiRW8KLS0tIHF0djdrWEJ0TWFwUGZLRG1SN1dP
            UzlEaWQrYXdib0ZmYjdhSG8xd3RxbzQKDBJb40I7Ul0ifsEY6d9zSysa/BL1kNRd
            EJcF4FmmnGLfh6iocjD6BzoSanE68tnmpI22qq1jlep1nI/euCpjCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-06T09:45:00Z"
    mac: ENC[AES256_GCM,data:QU3F0E3CvuQMRa9EV0rUIUd2F8MsGLEXTvzJtksf3D/NxHqrDi5xv+GcyQK7IsZWv29AwriWAtFS32EH/ASY5j7GiqetKXZEX3b/vkytNIbLYclRynEQwT3310LE6hPv2o6N65JIdiytiSVIJLE4NTMP2eH1wzcRrddT1QVzkHU=,iv:vPHCuC9aCDt8qOBXK7+Hv7rLlq+hHsUxc95Gp/ts6WI=,tag:DMyY+prvO08zE9vOW44ASw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
