apiVersion: ENC[AES256_GCM,data:T5Y=,iv:3BdGLCgN//pbNRc3feutw8JCG4kuzdTEvt/+yk0QlsM=,tag:q1j3c90SyQy24A0Eh880xw==,type:str]
kind: ENC[AES256_GCM,data:RBoIVHs5,iv:3FZS5Efs7lOJLmZvfd4lydE2yimdJAwKhltAADAGmrE=,tag:D+Idy3rnOJ0axzsJtmEk1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2o+cMuUBtFLmN1jaRXGQ,iv:Rtri7qPiMYaBvXdSDaAkmiyQGFoGyipslWalO1pnBsE=,tag:UyPJ9Hua5kq0W8cSYYdRgw==,type:str]
    namespace: ENC[AES256_GCM,data:l0lQErnGC7Hln8bYz1IR,iv:Bg/xZik+xXBQ02+xSHS46/dAJeE6UuiN5hRsXNA4Ulk=,tag:fe2mptmaOPtViybPPcpVnw==,type:str]
type: ENC[AES256_GCM,data:rfj162vE,iv:dE6WcG5aQLOTqud0iSk1N9c3biFC4REr32i3Up3LswI=,tag:3h8z85MNM48oCsdkzp1cwg==,type:str]
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:WSnRLu/MQJdwwl/4TbWdgHom8iv9l9adx5RfYj9ACMHiPFQxV1yJPC3w/w==,iv:pyyt2SL3NEPo2HVWGpaQvUVoDHECQIEBE9A3nqdq510=,tag:C9RyDqsjttMHzKG9hVBXlg==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:ZgZOFNdD,iv:+EPHw7335jQSLgt5Cn01lNXRVAvyWdquX6pK68Uekyo=,tag:ANIPq1j8le46Vm2Yie4kzA==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:ViEdrPafMQNsU6FwHMhx,iv:PdktOSJHKFm9PmnqphCtBRmhesME4GVkUMJP3OdPSH8=,tag:pfv6iIHiUkG1VnGzHha8pg==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:PrtWz6+V,iv:LFhfM6uXpGBvkJdUW/E9kDFUxr6ZNgv6MdN5vtYuaZA=,tag:mcXL5r123Vus4EHP39jmqQ==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:m9W+,iv:L/d6UjIzmS6QqBhKTOESxd2lI8D4FjqcXv2LXJA8vis=,tag:LfEFbICD0Vrj74r/VmwzHA==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:WNhrQKVHDw==,iv:0FftCqDrRDsVlLRXGWLOFTadWaO2/5UDMfGW4TWKtu4=,tag:tU3YNPS6rMEx3rP6Kgcm5w==,type:str]
    CRYPTO_PBKDF_FORCE_ITERATIONS: ENC[AES256_GCM,data:tLxK/YIY,iv:FHCjZDzf6DY6qfCAMjzeodDXoRGvlAAqUiLygGyvCnY=,tag:NllI09sN4OwzR5FWr1QHVw==,type:str]
    CRYPTO_PBKDF_MEMORY: ENC[AES256_GCM,data:ig==,iv:xZaLsxw/cayrJzGoDyKYNkbDNBi+TZU0lPkdIXdrTYU=,tag:NRuFDqkYvOr3rpXqxsxzGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNmhDYWkrK3RPTHNQdm1C
            MUIreDJmUFVIdzRaY1N4d3FSdHZhdFQzckM0CjhRVUE5MS82cWk0bE5kL2ZPSUor
            aGs1Ums0MTd3YlNXYmlKWVFTTVRiTVkKLS0tIDQ0Z0FFRGd5dDQzMnlZOE85NjJD
            Zjlrbm1FMU9OQ2Y0Zm16MmRKRHBwbEUK6DM6Yqpnk0TbAmRWatAN22Bgj8UmLtJB
            vQT7fUSymqrK2hZzuu/bIzQJng90uoyPXQQAk1M+mIR5JmpfbylFIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-05T03:48:32Z"
    mac: ENC[AES256_GCM,data:WTlF9QN08IWG0az7BpKswC2nQ6O60xzlvO8DD0SLjHXCP9G61k/nJi5/2B26Np8b4tqufE61nXxxyn7ragNUXLlzoeEUxMMW7DoNhEIiS0v1fUkHDZB4+6Pg3A9dWogEmQXStaLF5mB9tmTjeVAULSxA2+KO558Tpr36KgFOghg=,iv:m/0tz6dSxxMbh7RJxUcCYc1ib9vx5wxxueJyDNB82nA=,tag:6CCK1fjQmgSMzMdRY2A//g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
