apiVersion: ENC[AES256_GCM,data:IVM=,iv:uM49KpvVzIotmcr8J0RD+cAa4/KE2K1v0XqIid6iJOM=,tag:bERXSQDUB/7upfWWw02x8g==,type:str]
kind: ENC[AES256_GCM,data:atVCKLBz,iv:/tZ7BHMqvtid/9pm25VFvjG64/qLfC4Trgz+m0P48iA=,tag:yFeM1xGhlOmHaNbQ2c3YMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YOnDEQyAKJS+tgcRFbL3x2du,iv:kYzF7cLX5HE61iP2ZwM/nFOOCDsV9IwtUMx5rVSIvzM=,tag:AUdf/4SdGJoIxAAIYYiC0w==,type:str]
    namespace: ENC[AES256_GCM,data:b0PG0eoO9o+N5Oi+mQ==,iv:IO64u1cCal4fqxnpab0ckG9pkiXMjeP8/En+CZaV1qQ=,tag:vm8+12gXg8enXUGgMzRzHw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:4o4NpgniDXwKFw9V955r5DKTqYCwF6j4Ax3RxinnEqDV3pM7CJGrDWSyzw==,iv:RVXCkfSSn3uuJDPGgTv8A8BIiKxTj+QgYbM92xNJti0=,tag:r15znBgzNeDqZKF1JcR8DA==,type:str]
type: ENC[AES256_GCM,data:uVw6E+Eh,iv:lB9INpCdkZDVeCbR0DAAFMOGilOp+GIt4A+QU0uJt4E=,tag:+2NffMllNq5km4DHk+VlbQ==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU3JsQ016TXl2b1Fpblp1
            YWhIOVdoVDFzV2ZPVUgzQXJPNk02aWl2S1ZrClc4cTRLTkZQYkYvOWI1ZXp5bm5J
            VzZWUFNUNUhqeHE3M1krWnFuMXg1NlkKLS0tIHdXWDFyUFg0VjhSRTlZcnNwbjNr
            ck5DZ2RvZ0VIcVdzeFhsa0praHZ2UW8Kbag+5J78SYRyZuflmPSpuyPW73EDNGsd
            mff1iCllIcXrj4XILc+aW7u8W57QdRpAHN+U1kynFqMZYz0v4OiaUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T16:13:43Z"
    mac: ENC[AES256_GCM,data:w2AMegT43xqnpbdIkbHqr3VU/08HXAy4qXez6IYh/cACsbHRCuQNtpQOHvB31+ry8pJbiGUCXBsR2bcQluifzkTvaW1W/7nUS85olmRZP745ptpmGqWVRVepkuX2ffCYDheyrnzl+S62q+FTKrd3urYWB96O4y8TWo3TpSJfNzU=,iv:8ahOFNdtLa8yKji5WgWNfAJ37JAlebiOxWANG4petcs=,tag:xaI94ujVsP968EA0JBxmXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
