apiVersion: ENC[AES256_GCM,data:VDQ=,iv:mUY2PpR1rMUVQt7XeXwGb/iI5cShslmJFWIt0p9vrWA=,tag:8TNeIWN3h8jm5SCkOzJfZA==,type:str]
kind: ENC[AES256_GCM,data:hbARTO58,iv:oC9Gwm293Ci8kX5wv5Csl1CuQhLVSoyFyMseDWRKQtw=,tag:ZRy1aUaQhv0dgM5yfKNcmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TtEHRQ6Srp5K71gcxm0oFwAgTjH8ZqQBWQ==,iv:glFMwz9QWJXjWVcoGFlQn5GXg3swy9n+Ai8kWSoi4zE=,tag:C6fe9gHDFxT+Hh1+8At1Uw==,type:str]
    namespace: ENC[AES256_GCM,data:YZX1Yk4IbfjrOBSM,iv:r7uI3P9btGHO+QaHkzyOxlxhtjwqBKiZSgiyR4XYosQ=,tag:Rhmyr2EgEW2BygsFxW6HWw==,type:str]
type: ENC[AES256_GCM,data:KmRS22ks,iv:3Ki7GFaSlqfj7gClm6c8TrGGB4HbH5EQTBnsx4ShXVg=,tag:6xN8M8G889gFOGfJmbq7DA==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:9hJcWK3KwOW5qTP3Do9/Q56oF8/UpjAc+MlGPiipLEX4f5OKa5M9+zUC/4W4CipEuKYDC9lNMIavizkADx5Nuw2+LjmcnYIZ371ks57vCLwfICFw0WrzEhrfAS7/9iyAm8rNvJhLu8TWi7k2xiN+/JlvitzVmElH,iv:nf0R2AjA9sQGi1rMHv0i7PcqVbLBiloXEiwcZeSce4E=,tag:GfWxCcc9yZXhw7NNkAaGcw==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYTJSU05XeVJVZUxvVGRB
            dG9vVmp3Q2RLWE1oa3hjZFNhd0dWdmEzelQwCjh0V2dBVEhNajBWbGZPSDYxQm9z
            M0ZYZ09IakNRd3phd29BemVpbWNxeHcKLS0tIFQvOGE1ckpCVmxjUTJjUXJvdXk0
            cWpPNHZ0QjhqM0N0N2VuMG9PQ2o4WEUKcAkvOm+R4gSa2LIC786j8KjX9PGqQZpL
            H5ZG1Dmyg27EO4S5Q7AyLVDG2qdZ5UtwPeWPPZ3mwjoxH3uK0LsAUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T03:42:55Z"
    mac: ENC[AES256_GCM,data:ATRttT3lBgK0yo9GqnruBnnAjWQ6BJ7PgaaBT4U5R8gcb/SqWnt44fOYtZCoExMsfUZOlTmue5fHW/0ZUi9T+B0d18Ap89EdK1gXI73buXBtPF/67y19lwYWkQBD/Du35Dcpgg0VliMPhxFtoB5DnExsCPJPyNgrc3rmlGnfWZs=,iv:3fby3xwIMHm5CqvZZKSpu5C/ia3ZMv/WmY30+ICFseE=,tag:zT8dbxC7DUS0VyVvsd9neg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
