apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - reference-grant.yaml
  - postgres-app-secret.sops.yaml
  - postgres-cluster.yaml
  - database-url-secret.sops.yaml
  - deployment.yaml
  - service.yaml
