apiVersion: ENC[AES256_GCM,data:dlE=,iv:Np0ApiQUtut7yAgUzomZy8Ny4uB3W6/VSSnpBAGHDUQ=,tag:IvJR0jlOJ0lLxFFzWplOvg==,type:str]
kind: ENC[AES256_GCM,data:GWJcA7Bn,iv:ucA0+dg/6JpuH4oJsoT5KT2q5iv3BnOGnUc/jb+aBGI=,tag:V2j11/VG4qehR5pqESvt4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uuX2JmwgMpQN4Oz7Pgj5cNxg/Wqv338cyw==,iv:dKDx1s4Io3RwXu742M2OKHUk73b5APpNOYuLZYQ+OlE=,tag:c8qNtbzr2rtwFcXE++Vswg==,type:str]
    namespace: ENC[AES256_GCM,data:NoFddJGkSlSI7N2G,iv:FbiLQoIJU6yqSsdJEEVd9vVR3ephb88bdlWbZ7/o+I4=,tag:foUTmaXcwbnpW2Bcpr07lw==,type:str]
type: ENC[AES256_GCM,data:AOhloBBXApks/DUanf0GYN7saCi3jtTm,iv:w4CJsbeWtEck38l5sVfuGlUq0W1NETbmhReve82dK0Q=,tag:e4dpnGmgeq4ilDCvqXRdeg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:hqV89ru0wQWWM5ym,iv:LApfVkDsJxpRPIQTKrqVvSkvCZivpseUKf3i9N1vZnA=,tag:VeYYfQAmW4iN6NKEkzvINA==,type:str]
    password: ENC[AES256_GCM,data:+VW3YTQy2O1ZU3sn4wGG/1Ju4X8ESQ==,iv:HbndyDmLC2GBzG6x2paclwoVp/BMw091du1m3RIghqI=,tag:w7SdV3ZhIfzPS50wA6RjUg==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUDgvLzZMUEhtRVJQWmdN
            UDRHRllqNXhkYmdRemc1dXVkMkFMY2NkTnlnClZ5MS9GQ2tDMUhNSUtOMTB0eGo2
            WVpDa1NtUU5ocThGNmI3WVhDNHhGUXMKLS0tIHpLc1l0QVgrRC8ySnVrbXpaemt5
            R1hubmtvZ2dGMFVCZnRFQmwzWVJUdWcK4Zj3/rbTxGBwM5Nf7FZFdmdGeSoulHmt
            XGSZ2AwtN9GplyrCUKI7RtMFWjPlSfP86c1XHQppsvi/yBSV9lnY1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T03:42:55Z"
    mac: ENC[AES256_GCM,data:gb0dQgOM9VpIcu+KV50RTem3Btq7nX+HqLDc/AuGVGGyeydyEgSwc+ROWG7V494lR6rFBOKUh9GSKrXSwL4Dap8P90nB8sR6hjDPktlOSKeTI75Y91lAnFJqPI4STLG9Z4DQEh3IRxuMC6rIAVxWYUaU60sejpRmtGYrNxJIhhM=,iv:NkYs9dQC8IVZPj9EMShubV8ZhFWFsHCW2RtFkJFyrNs=,tag:/PFgmzqPpL59lIoBoNH5cw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
