#ENC[AES256_GCM,data:Cvd8K2a+hEhphCbTgI+UlFCTHEi/A0qJIJpS6zuoMQrbFsxZN6hwFfsDDEaL/sn0/8SfUnyMwTbiTW0f8DJSWFdvuIwnGHui,iv:YYTnESYFaYAb8exMRTImPISEOChxHtlleTJOEBmVbX8=,tag:AEsA6WXRzA621ElChToZzw==,type:comment]
#ENC[AES256_GCM,data:CZg+3GDZFK/0oQJFWc4R2WAuajv68QE9Uo8uLjy2kFo6OiIvkqBgDIKVOBmEO6M=,iv:06V4Kb449JP2JlR0Phh/fJsTLsRZ4cvE/5e2dN9hy6k=,tag:j+ay6Nzj51BqZ0wA+O/KKA==,type:comment]
#
#ENC[AES256_GCM,data:ENUqAAx34sU2MuY1/dYVeWzJxdXiDuQr3XRvWEEHboou/WHk5TZD3ZfmLjM6dn0xZF9m4nUAI3bUfNKRklpaQ4Bca5LqFYHvKpOxE6VXWt1+yw==,iv:nyl7NUJD3Lw7ieJa4yfIkfc3sRcHAgTvd0FV+SHhns8=,tag:uiq0MoJ+uufcuQmtD3KrNg==,type:comment]
#ENC[AES256_GCM,data:bweq5KEgo540gbJ+hD6QHxU/6pE5SIdMYlEXbmDGn9ovb4Hjoo6yA4JoaTVxX8jAMYuZz+Cw+Of3UteuP4W+LysSjPigaUZJVtixKnbyylPy,iv:lg7dpDYWCq4E047f4GrfA4MnFEM51OpzjntTyV4yaVM=,tag:SB+qUb3tasq+9DwSHrU+kQ==,type:comment]
#
#ENC[AES256_GCM,data:LRU2qYxJmFbYv2ndyPnYknHUiKMB55C4Cw1nDZZOIBo=,iv:qrrR5DGlf59S5BlTZunibpxcE4g8iwEhrVZWmCR+4NE=,tag:gLgigFgOcxRfJvNjopJssQ==,type:comment]
#ENC[AES256_GCM,data:fIJawmuEIMta5bVx7+ZSt+2vKQsMEYsfp500JuqfCaKEEhg=,iv:qVtO5Gcv8CXnzhxNeZpa23PdDEve6dw6bZYdsHzsHjo=,tag:3gUVvldiDAo1qVdfJZYg2w==,type:comment]
#ENC[AES256_GCM,data:WeBNygI/ngAw2AFw94wEboMqq5ww2zHtNV+5SaaHN1BWF2eOeuHJ0MzelSoPaR3wFjzLUllS6Mst0HjMen53PYhR+C9yqtgxP9u7ABUF3yEyxMZ4Sw==,iv:ghIe7em43KtU2QbDoq7FPYFCUscImN90zgKSttluUjQ=,tag:ZU+UkqskbbCO5VimkhGnzA==,type:comment]
#
apiVersion: ENC[AES256_GCM,data:olc=,iv:8lOMqq+ATtVTNlVCGiOizYNeS/0Jis92ECYdONZYeS0=,tag:zE60EwoT/wuFPkOGZamfGA==,type:str]
kind: ENC[AES256_GCM,data:Q5SyEZhe,iv:8D7ouK1Wr5p347WlQozHolqm+yipLCLS3XJQ8ksyRkk=,tag:JAdFrrYk3UDRnEf40QnICg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0XiYMXy4kXMLdzgVtOKoXI8UIxo=,iv:HSwbVCE1hfSAb0cpOcI6MLl5KDnDjCmzqlrl8BkjYG4=,tag:QCyg8muhOyGmEG9cYZXROg==,type:str]
    namespace: ENC[AES256_GCM,data:lv46ylo=,iv:Kjh7cX153C+uZAdvQUOhFKBF2AJpfbdndvU8UAnlHnk=,tag:iE6FDkIdq0oeC1VR3yPTXQ==,type:str]
type: ENC[AES256_GCM,data:nJAennP/,iv:ExrEjebJD+BFTW4N7hBTW0hkC9XXwvKoJ4JBwsSsQQA=,tag:A4B9J1M/N+t6FH7bPVk6+A==,type:str]
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:+gsnLUi/OhbHo4c40Q0Ud03No8g=,iv:Qg2HNyoxSAWZjgdN036aNyCWdYNNrTSZaYdXpK+cMY0=,tag:Y4Ta4QavyfmAvTYw7eTpWA==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:0xU8l59r/MqDibiG+3WvBxdFLju355H8hyiHXPWkawNdHAyxKRI98w==,iv:IjQFvKiRqYfctlf9lmhh4b2IJELvsrNlqY/rmwo7g1M=,tag:AeCQJkMDko4eXXGHJWUjQQ==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VGhBNFQ4a1htR1h3dFFa
            Z0d3b3hscm5VQ3YraHZQV1lDT0J1R0xzb2wwCkhRakcvRWdwVUtOaFNiTEcxMFR0
            UlE4a040RVZjVTdoczIwNEZjZzc5MXMKLS0tIGFLak4ybnVlZTJJRWI3TTZBZ3A0
            azhUcTY1NG1iNEcyZHJEL0dtVWJDdFkKsQE161Tey6yuwHPjjrdfMkHbRvyCOeI+
            cftunAtoVTxgWW43AdJVJig6/wk3z973tr0AFO+W0aD9Iy3JAtsY/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:23:59Z"
    mac: ENC[AES256_GCM,data:BtYvZvwWvmicL9hpYtzxkU23DtWh4Xi58pSGHhPjPg8e/UbiPKdAut5umkv76nPhJqy83NrxJh7+JiREXLVuWQsXqGMtltGkVv2bzKp+TS8wjCxOghxahQS3r/KSfFVktN1PcfDsRUhHlxUYC8uYrIzolVbFncCiztyclpWRkGU=,iv:7P5nFzEafSGMEyOFMYAHZJXJ2PlnNROYLy28a2l7g0k=,tag:bOvNZ/DbVslPPff1tBvB7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
