version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "/docker/**"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"
    directories:
      - "/apps/yral-ios/packages/YralApp/"
    schedule:
      interval: "weekly"
