[workspace]
resolver = "3"
members = ["apps/task-runner", "apps/yral-database-spacetime"]

exclude = [
    "apps/hot-or-not-web-leptos-ssr",
    "apps/off-chain-agent",
    "apps/website",
    "apps/yral",
    "apps/yral-auth",
    "apps/yral-backend-canister",
    "yral-billing",
    "yral-common",
    "yral-metadata",
    "yral-mobile",
]

[workspace.dependencies]
anyhow = "1.0.103"
hex = "0.4.3"
log = "0.4.33"
reqwest = "0.13.4"
spacetimedb = { version = "2.6.0" }
spacetimedb-sdk = { version = "2.6.0" }
