#ENC[AES256_GCM,data:4r5VoPANaLgw4hGuu0RE4noNzRspHyx8RMeep6wp9XVXqCntDbqf5IanBLbR7nvGOejh74/EDpN6AdtZJNfhN9Y=,iv:EtXIRTx3/iOW5r4f5TTE70/QCIlI22AlUSqDXbJ+Inc=,tag:i6P15tz35ync5tYVBAdUXw==,type:comment]
#
#ENC[AES256_GCM,data:tmKQ6cHK0Aqd25Q0J/lRrUx3IEwe08ezCPjqnTF5R/tkqP7vfUelmi++4E8umORmjTo=,iv:x8G8N253ukteYQAeizRtjNF3uOMos7jDB4wE6Plc31U=,tag:P5sJou9/xTyiGibX5oY3wg==,type:comment]
#ENC[AES256_GCM,data:BBdGeyd/p9OIGhiNWaCkGmpq7kFma7fi+3/RSys=,iv:OY/FAcqsmq2C46xma3bHOBhr76d3I0++rCCsxXUQOVc=,tag:q2H8rt6/KFdVd/1Lrhr6QQ==,type:comment]
#
#ENC[AES256_GCM,data:6Ba7rcHe5QnyrP3PzQU=,iv:LIY58LF9cWuGLKsATucplBhMt8A7oFJfjfK+u6wfZyw=,tag:1X0SsB4ymgKuF09lZwKWJA==,type:comment]
#ENC[AES256_GCM,data:HuXa6SUPA4jhRjq3PJ14pe3tevsBqlhQhlEnSzFM6Usq9N4ynEGiN+772qqFpmTOfI81eeMHSxEkSquM2yHxmicBN27azG62ZccLn5uoa+GW3f549MMAPBOiuA==,iv:7tA8RcS/EQJ3+4w6K1cJpj9B1EOO6zoDZavOYiI+CMA=,tag:2aTCjKPMnAp3Wg1sdGhOeQ==,type:comment]
#ENC[AES256_GCM,data:URipc+Mzb5SygDA3fGsKErahuKIhqq90JSaSdMhoV+BHQr6XTCgUY9GTy+k8PkP/Wp/uYp7OXnyOLy+1Xc9ZZxk1JdQ1UA0EsMQS,iv:5I3c3fTyKgzjITW1jvNPtU/CC1gmp73eCIL3sv0xuYY=,tag:1S2ZBC8owOd6YZii6cpGuQ==,type:comment]
#
#ENC[AES256_GCM,data:dHwb3GutAjC0+rKd1PhEWhOZ9HxexsHfuEtn/N4KzEBXso7LG8jAbi8koFKevr5/8C1ILZW/Wcc23cUs5pJBqiQqlGA=,iv:ocgnTtmvs9wyGNWokOpnza3KbLu4oI6f/8TEOxy/DXs=,tag:Kch0CAhLuaR9hM7dpOUzcg==,type:comment]
#ENC[AES256_GCM,data:CRXm6rRXqJSnqCMzz3pyJbMOUdNrc287FWAWx2yAmTCSapB1nI1o/SqzgaG5bpY=,iv:/54DFkes57DsxpzcBo3JldJ8pOUCjdyp3TytaHijx64=,tag:DHWFYuaQmGjY0f937a3G9A==,type:comment]
#ENC[AES256_GCM,data:na1afNIrbcnWuUq2Gv7UjsDB0hUVDK/EQYN9C2N5zqXWKSVAZ2OeYx2ohcmPyycq6/GxC4FZIRTh/xiF1v0ISaD2cpXU,iv:+YOpBygnKem/mBtDDpii6NpwGrQiDkwatqMOaQhJNBY=,tag:jqW5PYYwjmk8z9h2m4ls4g==,type:comment]
#ENC[AES256_GCM,data:BS+b2bnZp9vWkyA+YkB57H127q5AXX8JatehnoHQv1HTIxPYJCcKRNj11sRRbRixOu2R4n2RU0lLu3FIMZSrTQ0jNKNdw93Esg==,iv:4KY+HZKr9EGGJAQnELOHdh1xigo78yXAJy1d+4nr1Yk=,tag:byJNwMsffVBPcRfGL5BtIA==,type:comment]
#ENC[AES256_GCM,data:Q1ritKIGfdDefaIahvT2Du8kzdE3ak5VrVMATich3QWxPRHcTij+QAs52tH+OgB3ZJ2Uy7W7MMTsNkDQLA==,iv:eEEzvMn2A9H+tCrYeNVb0s0ELmMVXttGzfxzdmxcM/M=,tag:5VAj0H7MJPmql44gFGpyKA==,type:comment]
#ENC[AES256_GCM,data:6FAvXgwgc9zkJkJEJCT+XQwPLjMEKjseEkyGD3WuRRVw/0KIwLjFgT9uLUYXeTRczojBT0yRm76t/Z2jUdeibFN69ztA,iv:PDFTu6KYORQ/JvPXKKnl9TKIB48Sb5y/11JP0waT3Ow=,tag:tGtiaCabxtsTCOUqVqcwHw==,type:comment]
#ENC[AES256_GCM,data:oET7U2r6QCnoqfIBF0Y+ackkoFOKmJa5uRHqlGBsnZ6YMeSWCj7TkgTDu7tTsuI6aw8+Jm2svVT52M3uNBYKZFVf,iv:87/MKKM13JB+o5bCZnyvQotOQ9Yqifqz1+PXKjztQQU=,tag:m9+b+VrWXGxnNYzaGQZKCw==,type:comment]
#ENC[AES256_GCM,data:rw0avbXkrogyy53Q/V+dhSqEuOQeeoVSoz0MghZ0EH4eoFTx+kipy0UWTX6kwy7P3P/pAccIyZzO4VOCUj9vWyWRNnM=,iv:XJvq4NEpjM6MPAw5VAb2iuSQ9qFRvltADiyhFpGoYzU=,tag:wj7L8pWjOH6w8I3I3BTepQ==,type:comment]
#ENC[AES256_GCM,data:471ViidY/yoUJsQSOhHpXCJ1WY4z4vUo4+ObgUy/XGIVdlE6fOztb7fb2fK2+OJsfpgjGjnPcQ99C4CK1iTUu0XdlA==,iv:9IEYfK0Q7Hzcd5BOVv8mNBAopeALlXtCKmp07vYslBg=,tag:alQ0A77Y5KGf/3P2kpn+jg==,type:comment]
#
#ENC[AES256_GCM,data:UOZldMTG4sHyKviuqjkDkhgmxYSa4OCtNMRtHoaUEsYRZo0PGHOVjPmdH9S/psMJrEE=,iv:5zJInvnaEZH/RUc41gt5nkSRyhgTRE1OkeJ+mDx1gAI=,tag:ouKR4QooGy93vmvyehsJ6Q==,type:comment]
#ENC[AES256_GCM,data:EqzGqbxzKyq/VYr+IYXK3P4x7F9QnPEm0dUbHPUNrFmyX+v/uizu8Ng=,iv:fqfOe+EtZJgU6/r1VLdC4X0if+QJlnmGfIn4HmK89ag=,tag:SBNTswmNxK+2e6B2UaDJWA==,type:comment]
#ENC[AES256_GCM,data:s0LTncHmmfxz2Tlo0UXIw+9unFMFcIQih2tJ5i8O6+AZNED0NdYexe661SUPe4HB7zh3tQNUZ+qvLesWEHZR59VIL3p9WumSd1bSPpq631g=,iv:JHEVW5uqvj1VZkseMBclqN9f0RElbRz35A3e9h50WNs=,tag:DC/nw5cD8ZZubjkbNxg+2A==,type:comment]
apiVersion: ENC[AES256_GCM,data:RIc=,iv:/JCTEmv8VM1mocn1yZ6nQY9F+C76aLwHUg5wI7/Dh2A=,tag:NACo/AJKdyh4e/3/EAOsRQ==,type:str]
kind: ENC[AES256_GCM,data:k4pZ1zIb2wWf,iv:7w7sGqmtN1wyLQxEuF/yj95vtC1meByz66tHftANKP4=,tag:L+paJMzIQbx44qaB0AMgRQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dMQpmmmCImXtdq069NDsuYqmUWTfviwZsg==,iv:ttvWrrgjE8jBholz6vCBsFILfe8ORNgAryAA8eW9/qc=,tag:h1mmIOf56xxAGHb4+SQs1A==,type:str]
    namespace: ENC[AES256_GCM,data:FVJDskM=,iv:xF9/NMVrvRnaY28ji2zQIJrXU+YWUtLMtC2zc3NIGSk=,tag:LnCQlcEe8czBa6Nu6umREQ==,type:str]
data:
    nginx.conf: ENC[AES256_GCM,data:ATWkTg0s31v1st6dk+E3+WE318zoQigw8uY4hDYbbdI/3izNqPzJDbTRUVqd9FvnaqOWYSB0G0q2mWmEs/zA+yd9MxrK4m/z08sDkSJFAMTSTpSzktarpostvt5jiHtpXZwXr/5ea5TtB4mLMCtuhKW9I56iwS/HT9fiR3ugsHtVt7v8yjR0P0Z5s3z0H7UFBZWS2wvqygYIcf4F8IRYi3DHwYFpoBQR4GqH2iiynltMLSdnJcmgTEdi+uIPySuYsNEC8N8dhftdzSg3ovx3hCvaCHlBj8pyZ9H/cllBK3IU/x8gJFVKWv9dFwT5L7aM/olWybWnhokXDFloDrnvoQ8zBUyLnB6vDbNRs3F8e+udojvFFlAtLKDnOm2kIeVkfHBGV/JwHZxMQjK1iZmviwXOKFN0Hv4rdH56CRl2BxDnun4Cy8yAStzkv8D4pzASyqa03rOllH3EbWLFYAlDyfBaUQJfhmZjA48IBT1M0EZWivg/nwbcFayGYED5/9j6Z50wJuiUYhdBjqzdu5U77fcTy0auWRFIJaoutjnQtXm3V/94cufyCd3+JgLWceJpGKXgz27HUsvQ6aT+OOr+tav5gVOtA4APzwY7fTkSiptkQITD8ap3ctozY0+3l+Mo1aNJ7EppXtAIon0rvfZsUKsT6wGnfdmLQHLUwO9GU0M3KZzY1Ga2zB0guLWn4UPrxth7/p0hw7supVWlPqqoMPsI6w7SYv3n0C5MrRnVMEQ2DCCCe8DJQvsYhGP54bT/qKhdVq7EeVsrlJmCdkY4iAbnvKmkYjqFk48Iqnm9ycCwEbTzZzAdJSV3ez3WNYxhUznusoe7K1iUfblXC3emj1yIR3zDSRFNh/nU6LvTwA0lcNR5Ak904qEtPPd+2ispKi5QePkuZNDKfXWR//BSk3bMomMDXXRuFa+LhiK3b5T8koICwbzRkXcHz9DgCUmlcBIub/xauu8rDOkTANX2FiQmKyit1xOr+j1pZSQa9ZoSkJaMTQKdi3iEsEsOMoW3a0vf4GzKWWHsjTKToLDr3RAApRloGGG/oE1Bzw+O1bpV0Z6eVQweAm7JOVc7TAbwRZCrt4D5lXcsnjnluXMjApQnpNJGTQxqcddl5KeJey8OTw0qrXpkiNDi5lF2v/eI6rFZFFUzesnOj57gXfCBEpzLf4Pu1IPvtJdm4YJzAUwRHBX3H0gAMVYXgu6hfsagspmTKs4AjNnyszxC0TcpTECNHS3qhrpf0IEqEqpqNd+V7QFiTovaWfvjqR9Zq+t1QxWYdrheEs8hBKFeVBkBUJLzNvuJqx+BbRksvrX1Z/K2GrsFj+DDO7QVP6OXPzmWIiZIjPHW09VqOLupUHe7oyA6yrCgpz4B/9kKVU97wrluL+aoxv2wJrZIpeUF74UOcuMzMi+emltVnl38CEOuYWLFetwoc11v4Ir7x7jLrp8G4Rtues3dtpPVO2lHnHUBmHFXqZHJ/8UPIw==,iv:gtL5RupiCgRhfIXbPDGkhaoKBy4Sg6d401bVIa45o3s=,tag:my3pxt/MzvhtYOZ+7N6ufA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cnNjMTNBbVdZa0V4WHVB
            ZW02MGJqNjl0Wk0vQzRZeWlaMXpiMnBYLzBzClZuaEVIRjFJajRGTHFGV0hMYkVr
            dXJiMU55dlNJT0Rudk9DUHdnTmRSSzQKLS0tIGJPQWhZb3JyT0VuZFpyNHA1TGNQ
            THN6dlhwZTF2Wi9RVXd6TUJsSVIxOVkKRGNppYvZdpgE4j5Yt3mPkB3fijJ7AIrO
            0r5VZ4j5QeMKiUrh/H2VmBeZ32xmUSUDClEewn+/AnuX/ZI+ssICUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-09-07T05:11:46Z"
    mac: ENC[AES256_GCM,data:4Xog3zNejK+xpD3AWwPcKfgLrFHH5/kvD7gUzyAGto8Ct26YfHkyhPMlKe5YH0dVAtZel5ouEg4lk6kNl89pmihq88rOPGYX5OM5zh8CmWFEo80Ic/0LEA7HqVtupwC9w/Mk3a5B8XasaUiRXKsPDVfikS5q3aDSMUMvZigp1zA=,iv:1G/sA01jv59j3b/FlfimqC0MRdRDmFLE85DFeHXGxV8=,tag:rT/7rC9ItsJj6vInj1QyXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:mwE81JSJUQ==,iv:sRauGSlFfIBYaAzX/PFDVVM+15+U1KR+OENMIvOVxvQ=,tag:ikASG0haWkX19JYU5a3lQg==,type:str]
kind: ENC[AES256_GCM,data:xm4ARL+aj3/I/Q==,iv:JIYJicsETXHa4mgq0Fsb4A+vMbl297V7dwZ2klceu9I=,tag:vehmHwrkA/pjRriE8xtYQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KbnvYh6LJX3pQrnIQ43bf3mO,iv:yp6W0nGSf4zS3B9yp+CzvezkDWJPxXzk0haBN5a8ZPM=,tag:uwb261cJf2lJUv58qGNn/Q==,type:str]
    namespace: ENC[AES256_GCM,data:8UMXNHI=,iv:BxViZG7ey+c9wXxHoaX8da/plbD7/0tWcWZA0AZt3Wc=,tag:rMN+xHQEsabuox1PloehoQ==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:HQ==,iv:d66wMCJ+R83TIXXeOjt/7RxQMTzxCFo+D8bMQzqHebs=,tag:yY+SNoGCyVrtJJ5tCF+sCQ==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:XQZIH7u/6YzB1iIV9VC2Wv90,iv:IaxHedxQI8nUTF1re3yNMgba0VAtT/v3xIjJKxawSTg=,tag:52LB1t4ew7VPE5IMYKXJLQ==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:WYmyXI3WmR6uJ8VAYnLSxTrO,iv:mR4EObCXCAUsaNRynL64zGNN6qD+bihLNr0cdhlQveY=,tag:Sao8m9TMP1dZbDU01+Uo/g==,type:str]
            #ENC[AES256_GCM,data:CVlou080nN6IrEEcA3mYbZz+kyJsGsBHo4CCrNjjJz2BChsjVl9OWspgyq4Cyu/yeVgyecAbkIkHImI=,iv:aYoKEcsvuXU/GKP7yzlJdmTOLmnPygJzanDyFZMFVXY=,tag:X2Hhyv+N2n3UDFhuAoNcPQ==,type:comment]
            #ENC[AES256_GCM,data:XQ3/7n5XRB94JbyumzTxl4ELB7OZsJKSvlytjDUxSBfMs80piZDOVAlQaOAtnH3zWz+fEu7qe4gB81qIQXE=,iv:b4QMXclBP9oMWL9sfrrmgCOpUhmtKMDaqFzgkCC1OAw=,tag:y2OpuEa6ZKPeX7xMrdH+zA==,type:comment]
            #ENC[AES256_GCM,data:1EYSK5ODRktHzwQS36Oau24WTFyfnzzOnTcgvFLVZSNQQRRz1nIazeo1kcp+lPkSeSUVLRN/nBo1uA==,iv:2VDHjmjmxAP+GwhyYgPGtdv4kN8a/lRLvjnyUPKqGMU=,tag:8LLPgz4AeUb4NmYF2UgqrQ==,type:comment]
            #ENC[AES256_GCM,data:l4uQA6JFlxlvMb54FCMufw2qRHeznR/1N5p8WHSsky20fLpDCPEEXET6NKnjbL2vVqBi9w==,iv:RGOkCoLz+mvsBXfPC4lw5f+BSGhIvadYEcVNXtXwMqE=,tag:be4+qK/LfFumGyb6h4ROOw==,type:comment]
            #ENC[AES256_GCM,data:jxOkp0T/Uzv9qyD9FHIWTRJf5raeWACmTBILTIpwiA9zN0wKp/iJ4fgdycRMaYsodSHKIE4Oayd+cUY=,iv:wuEV0vke5zUEWKrTulRvnMfVd8ldDJdlmaWLzetSTnY=,tag:kolqqaE6F/EMeCmdn3QhHw==,type:comment]
            #ENC[AES256_GCM,data:FrIKT8Fhkt7icSTpR6Vqq7S8cjZ/h/DfuSKw0+QycuNvoJCbxwzLtkuh9C5q6PgOfo5RKVml3tLYca/EogM=,iv:YlVKwsSe4JUSPZ0zn3yOu7HAORILeRs48JOPNq3DHjM=,tag:7JAJR9i9VkEOnCBVEWTcvg==,type:comment]
            #ENC[AES256_GCM,data:CSBX8AAgGPnVwLrWgQx8hOgGLj0npxBuuUEb,iv:QhB7fMMpzFFoUzRz0yGgJlRiFcmf1mf7UwPsUVjOm5g=,tag:vXAFM2KqPj4C+ERaRwvmNA==,type:comment]
            annotations:
                yral.com/nginx-config-restarted-at: ENC[AES256_GCM,data:mVJZPzxLOI7fsw==,iv:cFI6pGNura5lZsSWHSftrB59z3yz9v5O9X7eOs1hEIE=,tag:M1PeDEfaZGePS12wAYK27Q==,type:str]
        spec:
            containers:
                - name: ENC[AES256_GCM,data:pz53HT4=,iv:/41zGYE60P1JQqWGCMTHqkkHfEnLHVKU5QrvpWn8H7c=,tag:IyiGgFeyz91MJlIpsXgGZQ==,type:str]
                  image: ENC[AES256_GCM,data:8AAxLBRs2B0uXfsOdD2kUT8=,iv:jkSylNvth38O1Lxt9SlFuzkgsqhUfpODgr2+KAqeZBg=,tag:+982DSoX77vsSh5Ik/6sxw==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:Wjoi2w==,iv:uFiEFQ8g4K+eCiPqg+Mj/pXtP2q1yOcvfOF23HYYRto=,tag:003xbZBdRh8mcgtBkWfBiQ==,type:int]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:JUwZ,iv:qNuONb5csH7Tl8U0SyqECwTCabya78fa9piwSNKjdSA=,tag:fvzpjaD6n5BhXbGFFNFPDA==,type:str]
                        memory: ENC[AES256_GCM,data:fXR7+Q==,iv:XP8TpWBTivBgkn9rOWLB1cwtahalmSOZSZQXa3Pw5Y8=,tag:JU2ObJ96LbzJhoMLRuNolg==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:Xqx5,iv:Sdctr7+HfOqCJBEqLZl7vQnkgct7Vodm4jhe5Gs4hkE=,tag:ye4lEq6851EgsIIl26gXpQ==,type:str]
                        memory: ENC[AES256_GCM,data:3NAj4A==,iv:2vH6x6gy5yYKhET3lIqQSQYxzUVtFGSnpjUCiesR5Y0=,tag:AKiabOiUgrGNqcTI24A63g==,type:str]
                  livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:rwBN5mG8/FA=,iv:gvEL4Ii/8SZB5EvzBqqUzsRDsLlcBdm5uyefAI+SFHU=,tag:qZtymrkt/aUpFcu07KxpQQ==,type:str]
                        port: ENC[AES256_GCM,data:z5MMCw==,iv:zU4O9Be691R2GT/bPRiq27kIRU+drMQFIjeWB2oAD+0=,tag:VUG3yN5JvNTR9RT8lNrK4g==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:qQ==,iv:6o1IxICqNUHxnZoGLH3SNmLtgLd+zyCg5H+8Y0aPDjY=,tag:FlBIvCrFzuKmjdfmYSJlwg==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:QhI=,iv:VnJKMP3b98sav3znKNdkG2Wv6hD54WklYiotAIrQGsU=,tag:D1gz/Xt1aHkgS3+8kdIJug==,type:int]
                    timeoutSeconds: ENC[AES256_GCM,data:DQ==,iv:2YboHXo37LLn3m0V3ZQ0/UUeKYrZJWvJEr5zRVes3EA=,tag:OvgnOZnkRr1rauOOGAr+fQ==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:QA==,iv:gkTGXTe9OSMWyaOOB8MShVEMoq3928fNKC2vONwkpr8=,tag:2YWkYZEzEt0gosV8fcXPBA==,type:int]
                  readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:SDQ0KFeI,iv:P2Axy2PKch1NmymmpKw6i6W4nOAP1uT0Iam/vK6RvFM=,tag:Ccf9Gy8C5pQlRyNHB3nZmg==,type:str]
                        port: ENC[AES256_GCM,data:hi7hdQ==,iv:Zk73pnwAaXDHicJzDCXVS04nHnXbUK98C1ba93LG2GY=,tag:UJSNgQ4cG/TlUrid6wYq6w==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:ZQ==,iv:TCAX5WRat3TahRxDR8sXVshnRTA6CooVfMqvllg4Wuo=,tag:CcpxFiGhkeuIwqNpQUlflQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:PM4=,iv:Hg/X9EDkoTzzoHtQINp/XUFyYDRZ89wmlGoLm4AYpB4=,tag:3KW4MBjDdMjORwpTRcD1Lw==,type:int]
                    timeoutSeconds: ENC[AES256_GCM,data:sw==,iv:gUoM5bbfzA132bKKaXBDQ2WmNoN9xvTgetq+OnjlauI=,tag:bYLKn6YFD7Hxw//qztZasg==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:PA==,iv:Igheu3XtnTDNf0O14r7jYJYqhHbFb9XTBBcxkPKALHQ=,tag:T2jndwp8UQ9Hc3cccROoSQ==,type:int]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:VEwLWUkm,iv:KsekrZIxpSw+MuN9JcY/6tPHXSGcqqWbOGNr0ovq0/s=,tag:m3+AdyrBZY3ehdrl0HvYnw==,type:str]
                      mountPath: ENC[AES256_GCM,data:jPdlGXW3VeO0kuFJsAgn1ybJ6gUzANnWeIEhrGzc,iv:XW019pM6MrcXt9nAw1cnUegeOTitshSXPBTtPY62a4A=,tag:P5X4p0c1uaQGmrupQ6F/FQ==,type:str]
                      subPath: ENC[AES256_GCM,data:dPZFEd2HlEcJ3w==,iv:9HNJt3VcnaCDqQzkEbCf+CUHXPw7k9IbM3eT1q6eNS0=,tag:J9gnzHnTZklwcfq3BaRmdQ==,type:str]
                      readOnly: ENC[AES256_GCM,data:tGAM4Q==,iv:DhAPAjMml0vwhl8FJVqz5mr62mwPdI2t9xXitsXuEAo=,tag:UKT1/c4eDiLNt+q9Ev52Qg==,type:bool]
            volumes:
                - name: ENC[AES256_GCM,data:dRAsU8GL,iv:heF9P9FWWfS1yEZ3DbDnMhFUAPOJ8DziWswwaz2L438=,tag:LbmcaxAPwHjna1kFRdHrgw==,type:str]
                  configMap:
                    name: ENC[AES256_GCM,data:3Xi+DAPzTLUiDqZcGbsa3MRfU5J2f0qnoQ==,iv:iEluLsqx7my6T8lhjt1fcfVD2XUZCug58LjrtKutPps=,tag:Y0k3EEQY/LtrzTCkVewt2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cnNjMTNBbVdZa0V4WHVB
            ZW02MGJqNjl0Wk0vQzRZeWlaMXpiMnBYLzBzClZuaEVIRjFJajRGTHFGV0hMYkVr
            dXJiMU55dlNJT0Rudk9DUHdnTmRSSzQKLS0tIGJPQWhZb3JyT0VuZFpyNHA1TGNQ
            THN6dlhwZTF2Wi9RVXd6TUJsSVIxOVkKRGNppYvZdpgE4j5Yt3mPkB3fijJ7AIrO
            0r5VZ4j5QeMKiUrh/H2VmBeZ32xmUSUDClEewn+/AnuX/ZI+ssICUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-09-07T05:11:46Z"
    mac: ENC[AES256_GCM,data:4Xog3zNejK+xpD3AWwPcKfgLrFHH5/kvD7gUzyAGto8Ct26YfHkyhPMlKe5YH0dVAtZel5ouEg4lk6kNl89pmihq88rOPGYX5OM5zh8CmWFEo80Ic/0LEA7HqVtupwC9w/Mk3a5B8XasaUiRXKsPDVfikS5q3aDSMUMvZigp1zA=,iv:1G/sA01jv59j3b/FlfimqC0MRdRDmFLE85DFeHXGxV8=,tag:rT/7rC9ItsJj6vInj1QyXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:jHI=,iv:7E2cC0XCeLtdrcrBmFy3Zacujhtp3u5ezsV+1r47e7k=,tag:EvZvi28Ts64fElFheVHsfQ==,type:str]
kind: ENC[AES256_GCM,data:PJKfaPickQ==,iv:o+Fam3ceRPv2LHtDf1NGLCmwKy2YRYgRmvEYhL8g/e8=,tag:/PnqYho2ccLnX5foiZWdtQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:26vKSOD/McN6bnCGPZWNKPLL,iv:Tad6rvUS3Ip+1Ote3gRGjN9RlMtSS6aNKcAN0xwAQd4=,tag:qK7FKNDWAf2Ca6SDNb/7Yw==,type:str]
    namespace: ENC[AES256_GCM,data:kcBGG9o=,iv:nEVjTWpxuECXGD0bDDAo0jd/aLA9wT8alzfj9flBnbU=,tag:MQLWQ6d5t5c46sqdjSc19Q==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:f/03DATLGcUvhuRIa4Lzaaxm,iv:gLokmIba3gL3D8RKRcJ69vBneo3vEbDLoT3ZZIv8R84=,tag:UIKnWemisIv2/WDJXAnCHQ==,type:str]
    ports:
        - port: ENC[AES256_GCM,data:Xt82Cg==,iv:+GIYBYvoJhwcWN85KgmU7Xx3qngwTf8kRd3xOvRxkIA=,tag:gYLjlM9Ko58Dt3pn0duaTA==,type:int]
          targetPort: ENC[AES256_GCM,data:8+Jotw==,iv:n2P93QukHrrwXHeQO0/zg4qI9508tQKFjwDh/AwlxFg=,tag:XDKUQuWPxMWCUKj1p8q0HQ==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cnNjMTNBbVdZa0V4WHVB
            ZW02MGJqNjl0Wk0vQzRZeWlaMXpiMnBYLzBzClZuaEVIRjFJajRGTHFGV0hMYkVr
            dXJiMU55dlNJT0Rudk9DUHdnTmRSSzQKLS0tIGJPQWhZb3JyT0VuZFpyNHA1TGNQ
            THN6dlhwZTF2Wi9RVXd6TUJsSVIxOVkKRGNppYvZdpgE4j5Yt3mPkB3fijJ7AIrO
            0r5VZ4j5QeMKiUrh/H2VmBeZ32xmUSUDClEewn+/AnuX/ZI+ssICUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-09-07T05:11:46Z"
    mac: ENC[AES256_GCM,data:4Xog3zNejK+xpD3AWwPcKfgLrFHH5/kvD7gUzyAGto8Ct26YfHkyhPMlKe5YH0dVAtZel5ouEg4lk6kNl89pmihq88rOPGYX5OM5zh8CmWFEo80Ic/0LEA7HqVtupwC9w/Mk3a5B8XasaUiRXKsPDVfikS5q3aDSMUMvZigp1zA=,iv:1G/sA01jv59j3b/FlfimqC0MRdRDmFLE85DFeHXGxV8=,tag:rT/7rC9ItsJj6vInj1QyXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
