#ENC[AES256_GCM,data:cg8qvjGtgx8f5zSzfmkb6n9bh5xmTTHbOnVxnG4NXBPqwi/pEIAkOKFzgIJDwt+TlL2bKjxJWSC57Ultts4fHQs=,iv:JGpCdyrgKqECSI6lJCIvb3cpxp8bHTYe4qSJZpLUA3g=,tag:OAys3Z2mzgJVaelL7+Vssg==,type:comment]
#
#ENC[AES256_GCM,data:SWcKtqm5lA7DCjcKou6oOVDCN7KQKvf6/o51SPva/PovYJv0s3Ym1eEthBckta+uyBY=,iv:1dk3xWqJ9+Dk9jIHN0ITB7NtNhqR56EBhXnrpMAN/gw=,tag:k/ZG9R2IAPq+P06Q+6X3ew==,type:comment]
#ENC[AES256_GCM,data:td1wNS6EKemGSt19xeXBGEwI2XfYZ6cCE6UPfbc=,iv:YN320Wbn48UB9QHzCqexmJWI+FLLxFu7TMrtVWV8tMY=,tag:ia4i1rKAWEoglUPkWmVstQ==,type:comment]
#
#ENC[AES256_GCM,data:nu00jeSSKxU8m0NANW4=,iv:e2jxkSbUSZjL1AMV3OizG6A8tteh7ZuatFlGQOC2O/s=,tag:nKghi6hitlp/OFKpzVlvag==,type:comment]
#ENC[AES256_GCM,data:hGw3EMTckYcb0xgcxRsIwjjIqn6wA/G3SuV6kIbzytxeUVpHoGeIRsXb9a0TOxioKjSlyCXphkyyWq2++9DRHjocymEOa5OJ+zQ8nAl7p4usT42ae79PE+T6yA==,iv:xCAs59y5HA6m4sX36veMvXadNvPXNY/w26vejZM/J0I=,tag:xk597MF3yIFD8A666qRobQ==,type:comment]
#ENC[AES256_GCM,data:7VncOBfkJlToz/ZY4trVzEBV5xp24MvYkKPJZCGUK20c0e0wirB01iaqyFKkHodF2Ie3fApN3HmE1GII7t1TAuSo6Ps/f4BwJS/Q,iv:r7U5SGbsmPffUqdz66bSdUkaMAdtFInuwM3J5SztCHc=,tag:pRaVC30WCmZbz6+WJVTOag==,type:comment]
#
#ENC[AES256_GCM,data:MKzFEpQKm4HnzxfZ/qXrQrLKkFq6ymQjGAup7vLs5eI+QXDN7z7VvNpzh3zw5dCU9+N0Mwzp/Bgl0nXBEAV7OfwJ38U=,iv:FHrsXdNkbsoHffVHDtHaAJ2Q/hjQdJ7hEbR7RDndb1g=,tag:xxUB4+gr3KFuCEB9IUvZ/Q==,type:comment]
#ENC[AES256_GCM,data:oiL98eY1HJIQRp85M3y/shMXMvFLSJrJyK0SsSK8wp4PowHj6ewJP1r/5jKPldo=,iv:JStwDCASYZpl+m3VRSkbLOXGjMdtrpyQShlsZP/LGsU=,tag:jqirA4USoy44h14exBAczQ==,type:comment]
#ENC[AES256_GCM,data:lxfKCIgeQUSziz53jluurkqCT9nPUDccZWbffryxk73oQT75S0ETZhfQ7Qfl83qoDsA2dbADiuIPl9YqHvzaiORk38BC,iv:W+RHP3sN2C7c93/KMEJMzSk40+RDSd4ZhYKplpAg544=,tag:IIprMVoUGzle7GBtKCefUw==,type:comment]
#ENC[AES256_GCM,data:nM/p0dJl6kpDTZ59lePB6+bR/IkesHsMg3QQ0w1MdhL02KK3zVJHXlJ8o0WLMv+cgEsKekcqeoK4WheMd483DxDykeoiMRTCww==,iv:6/g2pdjszDX22EndMOrgogICGgfv4pQVZcdYileJhaQ=,tag:teM5gVusR5BmN32hL44IbQ==,type:comment]
#ENC[AES256_GCM,data:lf0Zz/5rKVVgdWmbbUwPykU7Zm/YoVbs6tXMiVnyiQJHC8fxQgM5kfSpbe+UdESnSSkmGPUWx1rZ6Q1MLw==,iv:HuYrFYabJHkTbd92UFusrSOSYxC4XIPG8SNB+992Kyk=,tag:AQPcmCM23t1je9Yf2sSaPw==,type:comment]
#ENC[AES256_GCM,data:e/QgVL1rsDvZkyKn7jhFVRf+tJO3+U0scqZqUR1AtKbK+6V0q9RwBfcLpYCzxwJ1RpoyH7Nj1+IdvgRDwoTyZN/8SPpg,iv:1WulQpBGNMBuAgZa+vN4odWXkJ620ouDjpdqRRPJab8=,tag:nq1b7W8omr0LiROyO8LKVA==,type:comment]
#ENC[AES256_GCM,data:vI/mZXF2QlFy+7/ZrU919slxtVxTRHpYOd4iHTEwXYNSe34ROD+5Q/eXt9zWAv3plJveNMoHeMS/O/8vW2r+If3e,iv:nYQshbc04LRjz5Qsj+TxjTxu5uN1njvSjYBSPFxroKQ=,tag:1orHcxbzf/sFdU1WG8Cv3Q==,type:comment]
#ENC[AES256_GCM,data:bIGwcdjJxwvEds+BKgT8OMCKxK2YX2wqvVHyvfV4oPEb7yfyj6Osm0gUP0ELDZhv0L45yAb8/HmGgfI/K+T04hDieeM=,iv:QaUnx3HFHOjUiX0pJbKvhPpzsZzDf97zSGp4A51folI=,tag:zCUZYJpOW9O3SyUyP6m1zw==,type:comment]
#ENC[AES256_GCM,data:vDkztw4/jb0Pu9Kikomt/dYDa94jqiRgeqEF7kwoR2pyaMX//M+5LDuTztXDwa8svfGR0bq3UTfI3vAxmPs08ZubrA==,iv:4TQWDLQK43h5K33SgN4202nafUxXLdPSLSBNwYiVWAA=,tag:lWu3RXl1j2YLYeaM+lhf0A==,type:comment]
#
#ENC[AES256_GCM,data:q4QMEj6ENz3nn+6wPGVHMRtHqLdHeJG5STNRBfQ0ZnvvfOf78qQCh9S+hy3x8LLI2Ws=,iv:k0J5kB1oEl/D7p18jkh6JCXKQ3cfIeid+mZjfSjqpIY=,tag:lVm0VgeLB99nlJqfWFs0jg==,type:comment]
#ENC[AES256_GCM,data:zf0jIce9s/nDwV4x9lxFEus7f46I8ZonqxNBuLMgkGPuz4INvWPi/QQ=,iv:jJLNbhCnD18dMTdYpVRvTCmQTq4OJDbOPV0113fZNbg=,tag:RvMSyNAY/FVas3YFWKbfJw==,type:comment]
#ENC[AES256_GCM,data:osVs0Oogc+fttKwD4Nhj4Gy1zOgnVNerZArJL59ywAwFRkog7NwwAIiTnG1WBd8nR2rRsXfsF4er/j03czV3EmcmcV1nJoY17I+XY144+xo=,iv:5+bYEl4i4jb3asimC8TFNABOioLLuGUCweaEWIkwO/c=,tag:YGzmeX9hRjI2vVvLmurwNA==,type:comment]
apiVersion: ENC[AES256_GCM,data:uyo=,iv:e95Kbqw/t3x3cYWPF0J4+NPeZI+caNbKZi1hLsO7J2k=,tag:4mt+4M8omKUz65rQfmIjyw==,type:str]
kind: ENC[AES256_GCM,data:3Aqbpfor9TV2,iv:G2v435U9UKRo5NErjDr2lz+gs+DKOcWjC15r4n1hBok=,tag:q4LOF5Ib4L1Vwn/i/SzFaQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2oZNFf1tA3t24F8fMcpRnRnVUS9VEQ6uAw==,iv:zHaXXJfsTJIVKwPV8XHZP+yqCv63PFbHv6QlUV4KA1g=,tag:97FFZOgbovUrYw4zIsS5yQ==,type:str]
    namespace: ENC[AES256_GCM,data:R73uPQk=,iv:rmHDaKdnwEBoDjQjzr2/1fl0sy+hnlBQmJqu6QypzyA=,tag:62kE6hpCiDgYvNrBFql7bg==,type:str]
data:
    nginx.conf: ENC[AES256_GCM,data:mrzU75MEd62aUXjlPAso4Ys3EfYYkD4etokk6Uzlq0YVKGiYwbr4qDDruad4JEnrvri89wsQbgFaXYbNCr/MoCNEp2ZPNvQug8CXrYZIZYgiegheg6sw6/jdTlYzdsNFHDA11PpOUQ3ND7EGJMoaCBOWShx+MpT8tqJcXZe6eDPf8086rKPsKkrAHd83NCWzAzXz7uSJEgAMBbOjgi9B9ECCMrraoulHf9kheW7eQTnQumE9MC6BQcBAhwdVC+fa0qdwp88kVOYOb69MvKJtIg69idLJhmLweCRxixtsXk61u3p45g8vwGD6c7YRhr86H67mRhPbsmqBlRAYUVNL7tvuUyMo+5J1L0NpxLTGFjsW79B++iqtrWukbXDg78GHgvsMBiIbuJp/DkR4kP8vxFRPMUTp63To6Unw3U1wW2OCDHF5/u8UcQtmxm1/waeIfBDuZDvs5PFoMXD7sE0fhK10nXAgrmlw7tOru+bQcol+WnfEOJ92+xN3RSAYJiLa+VEAmkQCf5ez1l9WpF7dT24tCv2xYXk4qpKLM9Szob5qVJrQI/bEAkynYlQURpuYwSNFuLJbDmmCnZtJJGS7/QfdTxhGnV1YQFwdPqD9gjXX51f9T2wOTipKldhk74rR5UwvJHxZVdels3jInuF7E6J+Z0Fjc8GfOXMR4uDt/ZfYgCoeLBAawyFvzCk/yi/Xh96LP/uzwgraFGpczV21VN1NlLRtRM4kRKie8dPVUuHmHNMPKujeKJ/tOKvj6o43tUZQYLXG67kl4tBNeXMINLuG713pM8jtDQNP5fSUx4fXuUd4SRpehKnCnj5sJ5eUOPu4RBnGCBFVj1ZUprZhXri2V6qqrI9ZLQIXhcRiS8lKrFiOZPl6ek3x/vpBdJ2aECiQr58ZRYtuGwrHkg0rYevo0bhoyWLsf6Ka3Slg95NYd75oXzUtyFDNH6UEYzgWIw9Yn/QIhnBfh6q9I6XbAWt6nz52JkDAzmwRAc1Sqa4aRNTNdXBVoktDW0kKTZnzYytfqvDuAsyAqPINEqStiRiMlkcZTn3IKirQsimQuRbkaLgZ8817oRiLGKMaDCkY0q1s9TI/IUIef7ulyReTfKmasKEJVxxNi7mC4os0DEsfj1Xux0mVTcGU34yVIMrNBC8w9XyKi77ZI10LPh4edEhGbGe6Z2FyFEirldEd6M99dfcuVGzn37rgptvCsJ23U7lxw/qUxlYvYI/rZnN0ILoQ7iCXarFOxhWxZ6WoFzccWX2wd5YTesLhFwsM5fU9l2VySRl2U/uCK1+cOldVYGD8ILyYN2LRHZohjI5MfF3TKYH5B0zvep298x/FIdLo5+MN3G4qjwsKeA5fdwgx6YnrualuBTQIyvWAydxxeWwGyfYp4P3HhwwUpLRJc37RYpIiKQ3Ps2YcrN89F2BRn+KbGkRmXgDEe3INbANo7FSN9s835OvWUCpiTJNfcdwazb2e6U6UuBbhYw==,iv:5RnZfToww1JO6HPWcmzEC04trvjsQtCiL9AYV2ymPuk=,tag:lAeyVYlVc/fOkG4Pmm1/Yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbW1tUEF4dFRseDJEMEx4
            bU1OcC8xdjFTQ3E3dVBZT0tXTUkvU2kwRWdjCnpWUVk3RU9jNllxQXdlemdjSEMx
            eFNkUE1ETXFlM0ZWMGx0L243RmNUZGMKLS0tIFIrZUY4M3BvZHNlbW9DWWc0RFN2
            dGE1SlgvdWFHOHBKNWN5dEFyS3FqN1UKeA229bPoa2vRiy9Nu5YTfZYcMGzofzca
            Y/pUEFZAfmwPvKm9vWsbloHZXqzsCIPP0Nf13hFSSkbAijWMax/25g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-09-07T05:08:25Z"
    mac: ENC[AES256_GCM,data:Y4TueSUhN0n8wNmZmso0Ztbx1clNkDgK+7uuPpuiQtc+SCN51rEMDwS3sCuBYyft9QZtSwIs7snmoZ6wZsBueczx2fxstGtSlW2gB6rGI18WJYHG2nKU9kVhH5Y3unoACrVSp0zbxmwyxLgV4xqr3k3oKYV79QLybTw9dQ1b/Mc=,iv:nT6xy+iB7R2OMQxkMaxOgedksRy+cOoRzmTsjMXDbkA=,tag:wZVdcPUpkRl72G1Df4iG0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:M4/nuu4geQ==,iv:fVytDetuJ+EdsOvi4Hom2vi+JaDL6pN3zD6lozj/ahk=,tag:GH8eE9ecq/QKdp1ELJNqeg==,type:str]
kind: ENC[AES256_GCM,data:6rC2dr39H1IVCg==,iv:HnmHTenrKlU4QQqJGFeOC/JWL7wVFfIGyDCIjkJB+JY=,tag:3xnU1OAvBkbvYPYZamLSAg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:thA6AXLJ3XPwxZh0vytWpR5n,iv:1dWGrrdp3re5XDrHh//L9jHejBdKQJlYsrflofszGz0=,tag:OXJuTBlrvlGfoc6QXHVgpA==,type:str]
    namespace: ENC[AES256_GCM,data:SKfC9/A=,iv:vWZ2atL7tsKcVI4J3lxIY1ZvM8jghEGQPKey3XB/Qxw=,tag:AdLXBxvX0O+cgAAHWAnpuw==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:HA==,iv:uEfn5DWKxLeOq/vP/9Rp9DpCJMuar299sHl9Wxs0kLo=,tag:w+dNMjYt4H6eZdRM8B6rUA==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:eBC6p7vhGAh/40tFOaWqJmaN,iv:IX2eiGt+0RBCa9GjL/xpIDKWI4J8V7IJw7uFJxQVL0U=,tag:J7SxZuLfRJ7tNdwenWcmEA==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:QklgKsrLrcocrrCrA17fcPaC,iv:FazT6/umCSc7F4qdlL/6XQ1NceV6etrst4ToDuUEwyQ=,tag:pQ41aRr5HSMK1xHbP8jwUA==,type:str]
        spec:
            containers:
                - name: ENC[AES256_GCM,data:mUy4di0=,iv:opIoMbUtP5jmKctRTEARMqEzPT5nh/F8yY7tSVtoN2w=,tag:YZ/pVls0Bjo4M2nrvGUm/g==,type:str]
                  image: ENC[AES256_GCM,data:ghGgVo8GDWTyGf2o13xHZ14=,iv:xe72BFN5gM6c8sG+/77qONwxPgBgwAYq+TSTacDyUF8=,tag:23zP+HLZvhV8WE92hA78vA==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:zotwnQ==,iv:dif9LC1w06tBJH0TetiUusMJ0oADvGQ/fUrKvEEsPdE=,tag:2MpsgsdZkd3Y/MLPKH52PA==,type:int]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:7jt2,iv:BlY1iS3Akp0yyy7uNwApVf3UJUmRxndEgVD6kflW2PU=,tag:uWxVKWdEB9iRQBc7k0lvwA==,type:str]
                        memory: ENC[AES256_GCM,data:gbDN/A==,iv:bKj9rCZV4V5sr7pqKVNpz2caV/ns1FLWWebvg8c8ARc=,tag:8hj0xgj6yiTXtygeBXxQzQ==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:Bcwr,iv:XqkKSEj0H9ZmJpYk3WT263ier9yE0HxkTp/w+ld7YWQ=,tag:sOtuPqwgUa9uTkSwQf8gpA==,type:str]
                        memory: ENC[AES256_GCM,data:8/lwWw==,iv:HUMrPbx7S9jC+6z+qVUB3axKMfWtEJisSWGepu/vJpU=,tag:OLMKAJQBBQvmsx4v5y2QCg==,type:str]
                  livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:weMuON3GICI=,iv:k6o06c/OIz3jSI5GR75jL9jliW5J2eCGNcjhGXQQv1M=,tag:gEQVwNkYsha3Keo4+irhYg==,type:str]
                        port: ENC[AES256_GCM,data:E/F69w==,iv:KNIH3WPfwO4JQ2Fjv10lzwl+l2PYfzmwTw0FNUaMT4E=,tag:r7jGK7Fo1xIUF4SiwBZhYA==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:Zw==,iv:08WwbRoJxC3fF3pAfVWnIWiLCXNJvGxpSZqz6vhQrE4=,tag:v5nupk4O+DJfqhjsLDY6Gg==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:gRc=,iv:b1H2z5HASTJ2quolZILSDHNAcLVFoab/dXb3/RGlMoI=,tag:LkHipLwjK1h1ACMA+TMmSA==,type:int]
                    timeoutSeconds: ENC[AES256_GCM,data:2w==,iv:+797LyASzuZe7FbD9S2dfdQZ4qqLuooIzYUsb/abURY=,tag:BVg/ZcAVSYxNKDKHt4C+tQ==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:yQ==,iv:vH/v+0ksw/7EYqZEk0SNRUWSWla4szE3BEVM8ITO2LU=,tag:c0cpnA+lvEnoIi6VAE8yrg==,type:int]
                  readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:YeUFofWd,iv:kC00ZiNFOOfCIqXzkoWgursHvc7fxveP3opeCKCDvF8=,tag:G2RMZGrgR0LfktTHmRQf2g==,type:str]
                        port: ENC[AES256_GCM,data:FsoYPA==,iv:XiD2m5/Ka4w17AR70KYjqoDMVK0UYXMnN9lApXeaEF8=,tag:+eXglrxL+D7KvW87sg7THw==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:Fg==,iv:t6/HtVDRUxMSib928x58rnpxHPulk2sUmtVgi2u26HE=,tag:+NzOSgOPJJi6PNF92skcSQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:pyQ=,iv:KT8k7Y1+CcMsTy4VM0d9SK6T5GZGvskJ5E0Wae6PIQQ=,tag:Tp9Mb+TH9LCuquapBX5e6w==,type:int]
                    timeoutSeconds: ENC[AES256_GCM,data:hQ==,iv:VaNnnS36ls2BtKw3Bz1ZKBMj4tRpoGRTGVO9LOEWqjY=,tag:3G62WFr3lMlUiFHyXVFHKA==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:sA==,iv:O9cKwWcjQIhpkSGhRva+EGItenE3nFkoA3sqST/vY28=,tag:354DcIZMqd8myFr6E/7yZA==,type:int]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:Z9FcWBMr,iv:d2RcaiHzT0xL56VXPyr/Dt5YrhBHEc0s3Z54S78xR4Q=,tag:WbgwM958H2ZT4OHsF0c/vA==,type:str]
                      mountPath: ENC[AES256_GCM,data:phaaBUb/HT95v3BZeLrErSZvo/UxjWz4XEtyzC4i,iv:4q1VMUfpo/x3+X1i3tPvy0MtPraZ5KaHlHQ0gEERj50=,tag:ozkw0/6WxmgUJYFDHKw9ew==,type:str]
                      subPath: ENC[AES256_GCM,data:VmTUhLvUlDZGYQ==,iv:5qKJ50v7WOXjCr0KWiEfa0+xsCt9i8+2d7nuFXCBIwI=,tag:zV93nNTodPA5ACa4wHAynw==,type:str]
                      readOnly: ENC[AES256_GCM,data:4FBuTA==,iv:IZ09vnPMYWGWhuwpH3EC+h6UOSNoS9rDUF2p43j1zkQ=,tag:7nJajzbS5TwBmGDD+BJHsA==,type:bool]
            volumes:
                - name: ENC[AES256_GCM,data:X5SE0Rsi,iv:xN1KpRfQk5si6GE9LoU16Qyg7L4PQGYKoG+WbqME/Vs=,tag:8ZbXxOw6xk6f8jqT3c/zBg==,type:str]
                  configMap:
                    name: ENC[AES256_GCM,data:KAWbrlBKHhe51KPaX4/5tJFrOV/948By8Q==,iv:gaLVwqwiCDj9VoWglwJkQ90zL9kP01FM0qT4LJAY+Fo=,tag:e22Bt7hNF8BWQvnquFNF4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbW1tUEF4dFRseDJEMEx4
            bU1OcC8xdjFTQ3E3dVBZT0tXTUkvU2kwRWdjCnpWUVk3RU9jNllxQXdlemdjSEMx
            eFNkUE1ETXFlM0ZWMGx0L243RmNUZGMKLS0tIFIrZUY4M3BvZHNlbW9DWWc0RFN2
            dGE1SlgvdWFHOHBKNWN5dEFyS3FqN1UKeA229bPoa2vRiy9Nu5YTfZYcMGzofzca
            Y/pUEFZAfmwPvKm9vWsbloHZXqzsCIPP0Nf13hFSSkbAijWMax/25g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-09-07T05:08:25Z"
    mac: ENC[AES256_GCM,data:Y4TueSUhN0n8wNmZmso0Ztbx1clNkDgK+7uuPpuiQtc+SCN51rEMDwS3sCuBYyft9QZtSwIs7snmoZ6wZsBueczx2fxstGtSlW2gB6rGI18WJYHG2nKU9kVhH5Y3unoACrVSp0zbxmwyxLgV4xqr3k3oKYV79QLybTw9dQ1b/Mc=,iv:nT6xy+iB7R2OMQxkMaxOgedksRy+cOoRzmTsjMXDbkA=,tag:wZVdcPUpkRl72G1Df4iG0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:+Ms=,iv:eNaL5PtnDiGcoBc1cVc43QSpDDx+biL4vMIU5BFaZfE=,tag:Y55VabrgQO3kTphnQtPcfQ==,type:str]
kind: ENC[AES256_GCM,data:fE77+Ic7IQ==,iv:walSIsanC9vD3OIGnOb44k0ujOZpU3HQYzkalMn5XeM=,tag:Bi9Uxn/1+IhwCV18dmmYGw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:peq30wqQ5IaPPMe8lkucq0JP,iv:G/+3sbt9qVE0lOTB4ljXvFMDZElBUOVRRjiV4jGpeKg=,tag:PX/UKnzpIU7F13Erg3ZxfQ==,type:str]
    namespace: ENC[AES256_GCM,data:0fHGNqM=,iv:x+UaYbFpU/h5Rxzgnv74QuKxw+mjk90ToKQHcCu/8ZU=,tag:hz8xy+9InlN5v1TYDhS/gw==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:6dOFZkItJArHfbvp8CZjKnjT,iv:qwMskRbr3RSl/6eUUdEa/BgQ8l3M549YgVXblucRCJ0=,tag:IOmfUBm2tdk9jHaVRkhcUA==,type:str]
    ports:
        - port: ENC[AES256_GCM,data:Uiou5w==,iv:oFayDokJGR77ksy9CkO9ZIBlhOzFdmKOidg+Z7RMVVM=,tag:IObfrjvA+xKiNVCCMPTV/Q==,type:int]
          targetPort: ENC[AES256_GCM,data:8n2k3g==,iv:MNZXGvbSEHY9jDBgGxyY41QARa71vIMUitWjSnLN4xE=,tag:W7c4as+kT6foeCIVK6DUAQ==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbW1tUEF4dFRseDJEMEx4
            bU1OcC8xdjFTQ3E3dVBZT0tXTUkvU2kwRWdjCnpWUVk3RU9jNllxQXdlemdjSEMx
            eFNkUE1ETXFlM0ZWMGx0L243RmNUZGMKLS0tIFIrZUY4M3BvZHNlbW9DWWc0RFN2
            dGE1SlgvdWFHOHBKNWN5dEFyS3FqN1UKeA229bPoa2vRiy9Nu5YTfZYcMGzofzca
            Y/pUEFZAfmwPvKm9vWsbloHZXqzsCIPP0Nf13hFSSkbAijWMax/25g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-09-07T05:08:25Z"
    mac: ENC[AES256_GCM,data:Y4TueSUhN0n8wNmZmso0Ztbx1clNkDgK+7uuPpuiQtc+SCN51rEMDwS3sCuBYyft9QZtSwIs7snmoZ6wZsBueczx2fxstGtSlW2gB6rGI18WJYHG2nKU9kVhH5Y3unoACrVSp0zbxmwyxLgV4xqr3k3oKYV79QLybTw9dQ1b/Mc=,iv:nT6xy+iB7R2OMQxkMaxOgedksRy+cOoRzmTsjMXDbkA=,tag:wZVdcPUpkRl72G1Df4iG0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
