apiVersion: v1
kind: Secret
metadata:
    name: harbor-secrets
    namespace: harbor
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:fdPEjHYyPXfyFfInnwHb6ZqTI3k/FzlVWgeRGU6S7Q==,iv:x6E1BFDsuwiYwTlw5Ovds6R6VNrBO+ngR0sZsq2YdLQ=,tag:oaw69+2r807GaDXgSWYg/g==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNDFWa2MvcmYyaS9lSTZE
            NVRDZ3poc1RCWUFJZU55dm1lUENGNVlpWVZBCkR4UHlBN0RWMmJSQ0VubW9vbHd2
            dVA3dGpFTVdsTDZ3YnpoZHFJSERFaXcKLS0tIExyeWsvc09ueVk3YjJ5ZFBpYy9r
            c202cVh0SkFFT0VDbUM1QlE2eVRMYUEKfMfYzgcJNxJ1QqkuW+OoiSyl+GeXQFVD
            gA8lyFN2q/Me519H9qbRqFJQS7VHqOkfnspxF5tSg4K+2/yqal98+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T13:08:28Z"
    mac: ENC[AES256_GCM,data:RU1BoJ0Jpq4yZlanrwl1sBQaMJFS/MuW0VYeuKEOODDDqsx1mLpFcqv47Ry9bTgzw5STV2nhzLiUr7AlvPfIImqCWIkcle+oDqu3R+cNA9bmzRCvQeoeJjgQ3t0sOfxJchIJPkCP9PbGj4KR5VVqRVYb11bUfRad+pjCwEabVnE=,iv:r3TMMYW61Lt9hYrtiQ7CpHBDLj+PCqZLT3Yy/tEiPCI=,tag:z7tlSjCz+2MMTCccti4Y4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
