apiVersion: v1
kind: Secret
metadata:
    name: harbor-db-replication
    namespace: harbor
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Vhq6Fs7PToE=,iv:QvKbgml48+ZdsCAVk53FPcLcByTnyr9Rt+dQJj2+s4E=,tag:r8jfnOGqLj61bh+fYVVauw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK3htOWNvd09maHUzWlAz
            enh0MFpxd2h5cEtxektRM1M3RWJxQjUrVkJrCkZKUVpFb0NwTjhZQ1poN3dldjhJ
            T29yNWZQeXJET3VuQmdRSFkzVkt0TGMKLS0tIGtGS0xvMWlMV3dyeXFsV0JJYlo4
            VW11cVVLeFpwOGZ5OFZTclZPTmNYdncK6Q04leXH4vUmwITMkrTsB5zNyaerbjqX
            gfbuWqq8BbARf/J53NaWf6VvfPT2YhkBAFmxYkNmsI3GmPrxWCXtlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T16:51:50Z"
    mac: ENC[AES256_GCM,data:MsXHIs+diJSRRC6R9Q8DBpppjbCqks491GIOr5txshsOEk1a6wDBhfeJ/lnOLKO3nz4UBT7Q8Bj3AAK7fzUPH4/J/je8NbATiHFA8pXzv3fTTItr6TldI8TKEHZLGEjX816b762/9rTMCdn84YZ3B1CkDt+owbdfKXJIbSd+MsE=,iv:c4wEIuxABEYlNi2hGtDWFHhUv2leHRmTNuFaFdJ8jUA=,tag:WUtCdiwjztFAZqojzSC1xA==,type:str]
    version: 3.13.2
