apiVersion: v1
kind: Secret
metadata:
    name: harbor-db-superuser
    namespace: harbor
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:PpU769ZHKBc=,iv:yzsARedIMjuxz80DQU9KXmnn+TP1ieo+3w95gLsxsFk=,tag:dENe7ER1Xjv7EFB4eKkHUA==,type:str]
    password: ENC[AES256_GCM,data:WzccEViXi3wrczxCnd15XZxtq2fImwjvbTYnNWS5Rhc=,iv:ye47mOZv4ri4/rJ/ZWasDSJJkfCgtlRPfW/fVB3E/T8=,tag:cUb+0PsKEZbmbRbkpOxWiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcXR5Ly95WTkrTmtOSXRY
            ZXV0OGxyM2ozMEVjbVhmNnlEd2dlcTFoOXpFCm9Zd3RCOTBhVnhiK0xlWXU1UGto
            Ri9Wb0RTS0ZPUG5abFdqNFVwc21zbVkKLS0tIE1xdW1XYTB3YkZ4M0ZMRkRsanZy
            SFl3T1RXaUxHNlJCSWUzdlRYZTUvZlUKiO/IPsajlrKdylAsGydsZsWqTNzG7Ha1
            xeFgBUW2rMllv53EwC7+VPpAlW9LIEFq/5aLnxPLipzZTU/LEMA+SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T08:58:42Z"
    mac: ENC[AES256_GCM,data:VButzD40lIrBNIFgjY1wJQ5mnVnXta4ChaS5vJb+k2dMJvE613SW6EXnHRl2swobquvTHriuBd/rBWqtz+He6oF+IMRGxAhDQFcK2I80vaTDVDkXOGoJqpDUJgvQmZNd4rm8Cwp0acSke8lWe1UUhs2IB+WDB5HYgDaeP6Majxs=,iv:pdOVAcA2q4jMj1Yl62+rR5cjLrddqremFMo4TBdsUmc=,tag:Xtkc81zbFGGuvbEPs70hWg==,type:str]
    version: 3.13.2
