apiVersion: ENC[AES256_GCM,data:Ctc=,iv:RVgStPc3CKh5Z8fKGQri82dhh6o5wR3XUeKj9RwKRBE=,tag:jDe1dzzDFxLhh11xgtViOQ==,type:str]
kind: ENC[AES256_GCM,data:++w3sAeP,iv:m/ZATZQtNY1lyhny3eHWIHO1/wE75chMOQY8dMxhS9A=,tag:fa6zqH6VwzYbyI525Hh5ZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r+6ppv+9Y7LBpScMlME=,iv:3U6W2drCb9UCamkw1d5C4S7WEL833BW7WFk9ml7W05c=,tag:P1mtkXYr0GNj7treosdWHQ==,type:str]
    namespace: ENC[AES256_GCM,data:KG8On+0C,iv:7yZEYsMD5ZPe5eJ/EqWQpiG8u/IDYqZuC/9ci1cPfcA=,tag:Az8xfpttTx3NHjBBdOw2MQ==,type:str]
type: ENC[AES256_GCM,data:2kNkZ1VE,iv:4OcMCHPQlklYq8wFNr3SCQYiuEsTWlrmsetWYbzzm0Y=,tag:GWb2/ddEJUfErWRgBMo4xw==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:4RDm4slY3HeM9semEaaaoDdUqFM98KX/7zgLM7pJhQ==,iv:LwlJEClJsIJnM467axXcGu9xkktgD15aqMS8uIloP5M=,tag:b8nGoLi3czCYQqWkET+Iqg==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdUZLd2t5QTdhWWtwQ2Mw
            dWkwOU5jMk9Kd291VDYzdDdjL281YWFGYVFZCjFNMzFzMWlIc3M2WVhWb0pKRms2
            SHNaVmg2RTdMQjNZb2tzN2lmL0VLUGsKLS0tIGM3d2R0d2R0RmVyZlhRTzhVSFZr
            L1BSeFMxSy9nbm1FSWNuTU1sY0ljdmsKQPYP1kEai+f064FJraeTj1QXBmOdaNRF
            xzbOyUuk0hBkzWZttgL7r2v1nTolQutSZ4WBRTqkGO/+5QUvOSH7aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T12:48:09Z"
    mac: ENC[AES256_GCM,data:hTEtCSydZ/V99voVeJGxLVVHzJTXtUVcL+ID5BbeAlojSn8+fl15nmtwwDE3C3NzT9kQIWzC7PjigCXKaBilbYIv0EeibkjRNu0jmsw9hF28HEz9WwAwB9Hih2i7oFM+AQ6nTQw4TCJqf0cZYxOzSQDb5Ik2u10647tsA2Mwt8M=,iv:/N2ftXYK0RtLP66J5JP7MNjqkt/DWybEOjqAzsPRVos=,tag:9cQwYnRNbCrOGy7hFo/CMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
