apiVersion: v1
kind: Secret
metadata:
    name: harbor-db-source-password
    namespace: harbor
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:5/V7OlxtnJ4=,iv:4WPxWQhHRv9P/rAQqdz4/LZYlt6aOvgD46fZbUVA7qE=,tag:03+r9FyFghVcPcHW5WBfgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycFhrSzRxRW1VRGtLckNj
            VnNmeDYwdUpMUy94Z2FidW84WGVNT0lFdEUwCjdiem5WU0h0aVdLSTNqLzFxOUNj
            SEhFVHM2Y05uWXo1bGVRKzZHQnlJSmsKLS0tIGY1TGFvWDgrMXROVXVuY2Q3QnY4
            NUg5S1JBdUtiV2FkbFY4S0xRRHVhS1kK6GS+QmxYa1ePiLQpp+DONGnHTbNrI8J/
            hL8Ihl/ig9xQxn5WiCPiqWWjgrh9jImkeP00FaQhOzx3ntVUSz7+tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T17:08:18Z"
    mac: ENC[AES256_GCM,data:At0OUBK9Qv1aZN6nnPTX5waAiqropdDRoptiPSy+NJtvAKz8uSGO91i8ckSaQWnCQwuvk7uI24NJbrIvutwxXWAiI6JOv+9ZWSf1BnkLLZW5O/mM7mWJp/of9V++qLfTwDoYq4M9FCsbKn4uKM6oiPlbKh+JihWNvpxwKclR2PQ=,iv:YmyXbsh5CHUmwpxXKIhB4gPx/zagN4jHeT+o7UYz+nk=,tag:DUQJAM/1EjF27qVVDo4xFQ==,type:str]
    version: 3.13.2
