apiVersion: v1
kind: Secret
metadata:
    name: harbor-secrets
    namespace: harbor
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:X9LoW15epoYuGkPSNaom4VvQGKAFG9puIB0lrOoVoQ==,iv:XACws11MikpxCoOKynZbvE2tba7iL6aYtr6+EdhG0NI=,tag:rLBWHSz/vkIWmzub6sixUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeW05MmtqcURIcmkrcG4y
            Mk1wbEJBdU9uR0VJSHlIOXNYREJBSm1yZVRzCkFCMXo1WUdtOXAxMk5XRWZLQVlU
            RFQwY3BIR1JIOUhZREpacUtjQTJYejgKLS0tIEFYdjZDb1oybC9MeXV2bTZtODdQ
            MnEyK0V5OW1zQXVGOVV0emJpMkVnZ0UKiQRFRuQUKffgp9rwTzMIPbtyl/C203RQ
            FRJMBx7fo1Go/pyhZ9V16dzbGPbLRuD36wwZhxOGyEqxOhduhCtU6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T08:14:47Z"
    mac: ENC[AES256_GCM,data:RAwmpO7P9rixY8qP5eiOCwUMLk85u5NZ5G+vNV7R6SP9YnXqNsXGA5mM6NF3OV4wCPhlsO6Ft5uxIYFSkmOP7w3S1zEnahz2MEPGc7XqQmUTUt7Z3a5VCiEHwzRiUTQOVIDqDYDVTlH19UZyzs0lQOWhkFoOtGOv/hKvHcXxJ88=,iv:1WSCni00Q/vrbDV77UtTdxc9qv3pL0Yc+B9EDPYt5yU=,tag:oiJxlslBNjKz6QwxIBgSFA==,type:str]
    version: 3.13.2
