apiVersion: v1
kind: Secret
metadata:
    name: harbor-db-superuser
    namespace: harbor
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:VIQYb9u68/w=,iv:KPR4NgEZdwfGHrUtoLICFIWHj+H7sR7FWm8y/TZChsM=,tag:10z2+qXTTvOFhe9/fM07Kw==,type:str]
    password: ENC[AES256_GCM,data:b5agtBPfBvaWk/ktPt6bE9H+0DoMSXzgCkIniuMyHxU=,iv:37CCMDZ/SxdlDLF5VPexkZ1lhNpX5hl1MhPl0n/5joY=,tag:aKCM4NwRF8Ar472MnjHDiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aUxCbE5pQ016dERna0RE
            emFRbTlVWmhSblVrZ2diTm9velZoZThOZlJNCjBXTkVzQWVjWFJFOUE0RHFJdmRO
            SUN1cFNPUjlSYVpwdm80Z25xOHBTdzAKLS0tIGhlaUdaVkhQaUU4eG5vNFZ4dHRG
            MVM3dnYwblJDcUhxVXM3QWlOTVp0NEUK7duOF7bHZT6uSrxWJck8cFTpJDvad1AT
            kGvXi84cWxUvWSEiSYwnVcxZePL52NgaNVDjAuTWU0e8C/8UuvuCUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T14:31:12Z"
    mac: ENC[AES256_GCM,data:SI/cwDXw13UDupI6/PE3TBFofw4hfXBz8m/FLlw2OFY1a9/mGgtaU4vyswRxSACabQhcTne0f9m4qW+b85yAu4Yo3Oi3KjZnqriborbklADCWTqrRVDrSCgYRl2NmQkz0usPv1iywiOwUquVhE0IN9sTqz3Pn/fD5kFf0DWD7Bc=,iv:4jwSogEQUDXFv6UJBSo3JWNCHxwZWk5OFLPG+eO89b8=,tag:dS9Xjupqtu6uATZsDYwiUw==,type:str]
    version: 3.13.2
