apiVersion: ENC[AES256_GCM,data:XhU=,iv:rWE2o/vlshnCyT7+0+fxoU7pANtOvnmkbTlkfjs6A4A=,tag:H3x3g6vhpo6ZXZ6Eb8RHwQ==,type:str]
kind: ENC[AES256_GCM,data:9rRv0XAI,iv:bg0g/ypKAI93yzG1WISAE8XlS8n3VffYCZEpwrMM98I=,tag:Lo8B8V8FLSuweMXuhwOd1Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sqTG+x8f3RfAatNyQtWeuYHfKPUW,iv:cI7/t221oqe9vhfp35KVgq88O5NFeh7aceTD6qqwFNM=,tag:g5FzPWDzLA2eF8tVKZgcyg==,type:str]
    namespace: ENC[AES256_GCM,data:FNPYfAR7,iv:xI+TEy28Ki5f8gNiKcCDX3MybyRWnl19Hzdrk2Xgg5g=,tag:e57xxzJnwsA75eQx5Po44A==,type:str]
type: ENC[AES256_GCM,data:t6lvBk7S,iv:Yxwc2o4dTYhHWJdS/KU+JZRaDyIslsExwYncVetZyq0=,tag:3E7miW1w5eWB/dNx7kfyHQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:3yMRFAWt2jA=,iv:3YtSQHcciQg8dYz1cB0yhAh5MJEv14OW1aoMe9l0KKU=,tag:S9nrB+hZkgmCgJtY5VzmIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNzdsTHFjU2YvTG1PRDhI
            NlFuV1cyMm1GeTB0K25DU3EzVkhYNExzRURNCnI2YWhBZktnZjhtQXhhemdYYUxF
            emltM0lpckJQMHRUVXdocVF6KzlwamcKLS0tIHBoRitaeWxaQithSzRTOFJJam5F
            N0lXbzkvdm4zQXk5MnZZUnptOG1SU1EKndCrENxX29VVR8h0azSPOlEDfVplpDIJ
            UedIvdzefkPJKdmQJj8gAg5iXh51NLgNJrtlYfGYzUpWSOqQyMjqXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-06T16:45:05Z"
    mac: ENC[AES256_GCM,data:L6Q1YulMr5xf7IEha9EN1ZMhTOzX09btt0MmrpWXvDvQMLAJcPQcP8ovLQJUjQPHaUJSouqaio/MGVZgCRJnskgEuOdGfeN50mOQUXvHTZBgAF0ROaVFGwQLKjWUqWELuUrxwkohLSIxcgF9fe8JwLF1hXCZHO1cd4DXanFmG7Q=,iv:IuK5olP8u8fo+JvpbLXNQRui1dMlFMaKbclcS5CuJbI=,tag:efGuXbCGkkQL8gcAOCMCmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
