apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webhook-certificate.yaml
  - release.yaml
  - triggers-release.yaml
  - triggers-httproute.yaml
  - triggers-networkpolicy.yaml
  - clusterbuildstrategy-buildkit.yaml