---
all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            control-plane-1:
              ansible_host: 95.216.228.60
            control-plane-2:
              ansible_host: 95.216.6.238
            control-plane-3:
              ansible_host: 88.99.213.237
          vars:
            node_type: control-plane

        worker_nodes:
          hosts:
            worker-1:
              ansible_host: 138.201.85.40
            worker-2:
              ansible_host: 95.216.24.51
            worker-3:
              ansible_host: 94.130.128.105
            worker-4:
              ansible_host: 88.99.148.85
            worker-5:
              ansible_host: 138.201.199.41
            worker-6:
              ansible_host: 138.201.125.248
            worker-7:
              ansible_host: 168.119.139.49
            worker-8:
              ansible_host: 138.201.251.32
            worker-9:
              ansible_host: 88.99.147.157
            worker-10:
              ansible_host: 95.217.35.190
          vars:
            node_type: worker
