---
all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            master-01:
              ansible_host: 10.0.0.1
          vars:
            node_type: master

        worker_nodes:
          hosts:
            worker-01:
              ansible_host: 10.0.0.2
          vars:
            node_type: worker

      vars:
        kubernetes_version: "1.28"
        container_runtime: containerd
