apiVersion: ENC[AES256_GCM,data:INI=,iv:/HzM2WebItBLi9/VnlVnSd58v7OQncA+zrgdX8gyXXQ=,tag:PWgwszAsl9TsJ/ffSgAeGQ==,type:str]
kind: ENC[AES256_GCM,data:uod17nwO,iv:6xeQ+OFbC1QFA/GPGU/es05Sbqu7gsj/Uni0ZU95Vkw=,tag:aJM20ZCeLUt3rxJnx3Lc+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vFrct8tTBpXvwWoc0FLkbLjT,iv:K3NKXkFkeyPKpu9gKoHEEBJD0d7jzu3VQQjbjzrsv9Q=,tag:Ia2ertfIyhnI2zlmMVwZcg==,type:str]
    namespace: ENC[AES256_GCM,data:IZKEuXxI,iv:HJNOo0cM/LpF3KUEqQNOGwCVF7t8HNgZ2h/zK5ndoFo=,tag:WHGvDAahluNdE81qhjmIeA==,type:str]
type: ENC[AES256_GCM,data:d0OzAiTc,iv:xwp6j2CcQynWSGoOQWjC66vJNw5C40URC7m0rzwxNXY=,tag:3O3r80BgDnCag/d0vhvsMA==,type:str]
stringData:
    cloud: ENC[AES256_GCM,data:bJaq9LazHU+lDf80b/euzGReGfyVhFRq2TqjHCAT/5J6YLC1XOCm3HibQegnTNpYz3Lgu6Xg8GJ1mVBq7m5xkn3CFcUGqh+GT4Tx7009nYO6j52vOYJ3N+7flWcKsWptcXamPz+pQgrWJ0j1sYZZVQ==,iv:tGmkeDw0cgFfYgqi7qrFVSdYh96qbM11tatC9VnsZzE=,tag:GudeVOjaCbDsg74+VUTeMQ==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTHdpNW8rSzYwTkltd09i
            TXBudHRsRlRua1dVczFva29nbDd0R3J3RWk0Clk1aGJhTFE4S0VLd2w2T2NVWUZt
            WUF0TXhwZitUY0dLYkRha3MrWHI0dUkKLS0tIFBHN3RmVEZhNHViQytVeXdNYWVZ
            dDM4amtuTFI4OWVrSHo5MldYTHBIN0EKZ5JqaS3DBN+pZT+Q5o9s2PAUn956KNKR
            o5fz000CDclVLIduUGKVO888DVI0dfYaRFki45watStvndZnKtuTzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T14:24:33Z"
    mac: ENC[AES256_GCM,data:hoq3XEdKQ6/mb2FqpvWqx4qCWB/ET8Na2TqjI6RcmhO9RbfY1VxY002OajTFIfqM7pgIAEHNepgxIYhJzKS56Bq7VYkg5cZnYptFBhFo5+BCzIW99Y87ZecLAOEjXgd6SWW5mjjpHEvcoEwzacvW2Q5iBiwO1+gDIYz0U6fXX3U=,iv:GF8SVE8EqzJ4up4ZY7mMvxSzspKPAeVrVn5/BjRTddQ=,tag:pGPsziQCdo2hlP5Yj21D3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
