// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::post_view_details_from_frontend_type::PostViewDetailsFromFrontend;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddViewDetailsArgs {
    pub post_id: String,
    pub details: PostViewDetailsFromFrontend,
}

impl From<AddViewDetailsArgs> for super::Reducer {
    fn from(args: AddViewDetailsArgs) -> Self {
        Self::AddViewDetails {
            post_id: args.post_id,
            details: args.details,
}
}
}

impl __sdk::InModule for AddViewDetailsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_view_details`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_view_details {
    /// Request that the remote module invoke the reducer `add_view_details` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_view_details:add_view_details_then`] to run a callback after the reducer completes.
    fn add_view_details(&self, post_id: String,
details: PostViewDetailsFromFrontend,
) -> __sdk::Result<()> {
        self.add_view_details_then(post_id, details,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_view_details` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_view_details_then(
        &self,
        post_id: String,
details: PostViewDetailsFromFrontend,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_view_details for super::RemoteReducers {
    fn add_view_details_then(
        &self,
        post_id: String,
details: PostViewDetailsFromFrontend,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddViewDetailsArgs { post_id, details,  }, callback)
    }
}

