// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddPostV1Args {
    pub id: String,
    pub description: String,
    pub hashtags: Vec<String>,
    pub video_uid: String,
    pub creator: __sdk::Identity,
    pub is_draft: bool,
}

impl From<AddPostV1Args> for super::Reducer {
    fn from(args: AddPostV1Args) -> Self {
        Self::AddPostV1 {
            id: args.id,
            description: args.description,
            hashtags: args.hashtags,
            video_uid: args.video_uid,
            creator: args.creator,
            is_draft: args.is_draft,
        }
    }
}

impl __sdk::InModule for AddPostV1Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_post_v_1`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_post_v_1 {
    /// Request that the remote module invoke the reducer `add_post_v_1` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_post_v_1:add_post_v_1_then`] to run a callback after the reducer completes.
    fn add_post_v_1(
        &self,
        id: String,
        description: String,
        hashtags: Vec<String>,
        video_uid: String,
        creator: __sdk::Identity,
        is_draft: bool,
    ) -> __sdk::Result<()> {
        self.add_post_v_1_then(
            id,
            description,
            hashtags,
            video_uid,
            creator,
            is_draft,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `add_post_v_1` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_post_v_1_then(
        &self,
        id: String,
        description: String,
        hashtags: Vec<String>,
        video_uid: String,
        creator: __sdk::Identity,
        is_draft: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_post_v_1 for super::RemoteReducers {
    fn add_post_v_1_then(
        &self,
        id: String,
        description: String,
        hashtags: Vec<String>,
        video_uid: String,
        creator: __sdk::Identity,
        is_draft: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddPostV1Args {
                id,
                description,
                hashtags,
                video_uid,
                creator,
                is_draft,
            },
            callback,
        )
    }
}
