// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_type::Character;
use super::class_type::Class;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character`.
///
/// Obtain a handle from the [`CharacterTableAccess::character`] method on [`super::RemoteTables`],
/// like `ctx.db.character()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character().on_insert(...)`.
pub struct CharacterTableHandle<'ctx> {
    imp: __sdk::TableHandle<Character>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterTableHandle`], which mediates access to the table `character`.
    fn character(&self) -> CharacterTableHandle<'_>;
}

impl CharacterTableAccess for super::RemoteTables {
    fn character(&self) -> CharacterTableHandle<'_> {
        CharacterTableHandle {
            imp: self.imp.get_table::<Character>("character"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterInsertCallbackId(__sdk::CallbackId);
pub struct CharacterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterTableHandle<'ctx> {
    type Row = Character;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Character> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterInsertCallbackId {
        CharacterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterDeleteCallbackId {
        CharacterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CharacterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterTableHandle<'ctx> {
    type UpdateCallbackId = CharacterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterUpdateCallbackId {
        CharacterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `player_id` unique index on the table `character`,
/// which allows point queries on the field of the same name
/// via the [`CharacterPlayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character().player_id().find(...)`.
pub struct CharacterPlayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Character, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterTableHandle<'ctx> {
    /// Get a handle on the `player_id` unique index on the table `character`.
    pub fn player_id(&self) -> CharacterPlayerIdUnique<'ctx> {
        CharacterPlayerIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("player_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterPlayerIdUnique<'ctx> {
    /// Find the subscribed row whose `player_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Character> {
        self.imp.find(col_val)
    }
}

/// Access to the `nickname` unique index on the table `character`,
/// which allows point queries on the field of the same name
/// via the [`CharacterNicknameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character().nickname().find(...)`.
pub struct CharacterNicknameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Character, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterTableHandle<'ctx> {
    /// Get a handle on the `nickname` unique index on the table `character`.
    pub fn nickname(&self) -> CharacterNicknameUnique<'ctx> {
        CharacterNicknameUnique {
            imp: self.imp.get_unique_constraint::<String>("nickname"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterNicknameUnique<'ctx> {
    /// Find the subscribed row whose `nickname` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Character> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Character>("character");
    _table.add_unique_constraint::<__sdk::Identity>("player_id", |row| &row.player_id);
    _table.add_unique_constraint::<String>("nickname", |row| &row.nickname);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Character>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Character>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Character`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait characterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Character`.
    fn character(&self) -> __sdk::__query_builder::Table<Character>;
}

impl characterQueryTableAccess for __sdk::QueryTableAccessor {
    fn character(&self) -> __sdk::__query_builder::Table<Character> {
        __sdk::__query_builder::Table::new("character")
    }
}
