// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::class_type::Class;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Character {
    pub player_id: __sdk::Identity,
    pub nickname: String,
    pub level: u32,
    pub class: Class,
}

impl __sdk::InModule for Character {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Character`.
///
/// Provides typed access to columns for query building.
pub struct CharacterCols {
    pub player_id: __sdk::__query_builder::Col<Character, __sdk::Identity>,
    pub nickname: __sdk::__query_builder::Col<Character, String>,
    pub level: __sdk::__query_builder::Col<Character, u32>,
    pub class: __sdk::__query_builder::Col<Character, Class>,
}

impl __sdk::__query_builder::HasCols for Character {
    type Cols = CharacterCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            nickname: __sdk::__query_builder::Col::new(table_name, "nickname"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            class: __sdk::__query_builder::Col::new(table_name, "class"),
        }
    }
}

/// Indexed column accessor struct for the table `Character`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterIxCols {
    pub nickname: __sdk::__query_builder::IxCol<Character, String>,
    pub player_id: __sdk::__query_builder::IxCol<Character, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Character {
    type IxCols = CharacterIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterIxCols {
            nickname: __sdk::__query_builder::IxCol::new(table_name, "nickname"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Character {}
