// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::alliance_type::Alliance;
use super::class_type::Class;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterV2 {
    pub player_id: __sdk::Identity,
    pub nickname: String,
    pub level: u32,
    pub class: Class,
    pub alliance: Alliance,
}

impl __sdk::InModule for CharacterV2 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterV2`.
///
/// Provides typed access to columns for query building.
pub struct CharacterV2Cols {
    pub player_id: __sdk::__query_builder::Col<CharacterV2, __sdk::Identity>,
    pub nickname: __sdk::__query_builder::Col<CharacterV2, String>,
    pub level: __sdk::__query_builder::Col<CharacterV2, u32>,
    pub class: __sdk::__query_builder::Col<CharacterV2, Class>,
    pub alliance: __sdk::__query_builder::Col<CharacterV2, Alliance>,
}

impl __sdk::__query_builder::HasCols for CharacterV2 {
    type Cols = CharacterV2Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterV2Cols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            nickname: __sdk::__query_builder::Col::new(table_name, "nickname"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            class: __sdk::__query_builder::Col::new(table_name, "class"),
            alliance: __sdk::__query_builder::Col::new(table_name, "alliance"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterV2`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterV2IxCols {
    pub nickname: __sdk::__query_builder::IxCol<CharacterV2, String>,
    pub player_id: __sdk::__query_builder::IxCol<CharacterV2, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for CharacterV2 {
    type IxCols = CharacterV2IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterV2IxCols {
            nickname: __sdk::__query_builder::IxCol::new(table_name, "nickname"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterV2 {}
