// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::alliance_type::Alliance;
use super::character_v_2_type::CharacterV2;
use super::class_type::Class;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_v_2`.
///
/// Obtain a handle from the [`CharacterV2TableAccess::character_v_2`] method on [`super::RemoteTables`],
/// like `ctx.db.character_v_2()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_v_2().on_insert(...)`.
pub struct CharacterV2TableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterV2>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_v_2`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterV2TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterV2TableHandle`], which mediates access to the table `character_v_2`.
    fn character_v_2(&self) -> CharacterV2TableHandle<'_>;
}

impl CharacterV2TableAccess for super::RemoteTables {
    fn character_v_2(&self) -> CharacterV2TableHandle<'_> {
        CharacterV2TableHandle {
            imp: self.imp.get_table::<CharacterV2>("character_v_2"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterV2InsertCallbackId(__sdk::CallbackId);
pub struct CharacterV2DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterV2TableHandle<'ctx> {
    type Row = CharacterV2;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterV2> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterV2InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterV2InsertCallbackId {
        CharacterV2InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterV2InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterV2DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterV2DeleteCallbackId {
        CharacterV2DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterV2DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CharacterV2UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterV2TableHandle<'ctx> {
    type UpdateCallbackId = CharacterV2UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterV2UpdateCallbackId {
        CharacterV2UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterV2UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `player_id` unique index on the table `character_v_2`,
/// which allows point queries on the field of the same name
/// via the [`CharacterV2PlayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_v_2().player_id().find(...)`.
pub struct CharacterV2PlayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterV2, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterV2TableHandle<'ctx> {
    /// Get a handle on the `player_id` unique index on the table `character_v_2`.
    pub fn player_id(&self) -> CharacterV2PlayerIdUnique<'ctx> {
        CharacterV2PlayerIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("player_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterV2PlayerIdUnique<'ctx> {
    /// Find the subscribed row whose `player_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<CharacterV2> {
        self.imp.find(col_val)
    }
}

/// Access to the `nickname` unique index on the table `character_v_2`,
/// which allows point queries on the field of the same name
/// via the [`CharacterV2NicknameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_v_2().nickname().find(...)`.
pub struct CharacterV2NicknameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterV2, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterV2TableHandle<'ctx> {
    /// Get a handle on the `nickname` unique index on the table `character_v_2`.
    pub fn nickname(&self) -> CharacterV2NicknameUnique<'ctx> {
        CharacterV2NicknameUnique {
            imp: self.imp.get_unique_constraint::<String>("nickname"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterV2NicknameUnique<'ctx> {
    /// Find the subscribed row whose `nickname` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<CharacterV2> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterV2>("character_v_2");
    _table.add_unique_constraint::<__sdk::Identity>("player_id", |row| &row.player_id);
    _table.add_unique_constraint::<String>("nickname", |row| &row.nickname);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterV2>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterV2>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterV2`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait character_v_2QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterV2`.
    fn character_v_2(&self) -> __sdk::__query_builder::Table<CharacterV2>;
}

impl character_v_2QueryTableAccess for __sdk::QueryTableAccessor {
    fn character_v_2(&self) -> __sdk::__query_builder::Table<CharacterV2> {
        __sdk::__query_builder::Table::new("character_v_2")
    }
}
