// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::alliance_type::Alliance;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ChooseAllianceArgs {
    pub alliance: Alliance,
}

impl From<ChooseAllianceArgs> for super::Reducer {
    fn from(args: ChooseAllianceArgs) -> Self {
        Self::ChooseAlliance {
            alliance: args.alliance,
        }
    }
}

impl __sdk::InModule for ChooseAllianceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `choose_alliance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait choose_alliance {
    /// Request that the remote module invoke the reducer `choose_alliance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`choose_alliance:choose_alliance_then`] to run a callback after the reducer completes.
    fn choose_alliance(&self, alliance: Alliance) -> __sdk::Result<()> {
        self.choose_alliance_then(alliance, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `choose_alliance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn choose_alliance_then(
        &self,
        alliance: Alliance,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl choose_alliance for super::RemoteReducers {
    fn choose_alliance_then(
        &self,
        alliance: Alliance,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ChooseAllianceArgs { alliance }, callback)
    }
}
