// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::token_type_type::TokenType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateVideoGenRequestArgs {
    pub principal: String,
    pub model_name: String,
    pub prompt: String,
    pub property: String,
    pub token_type: TokenType,
    pub is_registered: bool,
    pub is_paid: bool,
    pub payment_amount: Option<String>,
}

impl From<CreateVideoGenRequestArgs> for super::Reducer {
    fn from(args: CreateVideoGenRequestArgs) -> Self {
        Self::CreateVideoGenRequest {
            principal: args.principal,
            model_name: args.model_name,
            prompt: args.prompt,
            property: args.property,
            token_type: args.token_type,
            is_registered: args.is_registered,
            is_paid: args.is_paid,
            payment_amount: args.payment_amount,
        }
    }
}

impl __sdk::InModule for CreateVideoGenRequestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_video_gen_request`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_video_gen_request {
    /// Request that the remote module invoke the reducer `create_video_gen_request` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_video_gen_request:create_video_gen_request_then`] to run a callback after the reducer completes.
    fn create_video_gen_request(
        &self,
        principal: String,
        model_name: String,
        prompt: String,
        property: String,
        token_type: TokenType,
        is_registered: bool,
        is_paid: bool,
        payment_amount: Option<String>,
    ) -> __sdk::Result<()> {
        self.create_video_gen_request_then(
            principal,
            model_name,
            prompt,
            property,
            token_type,
            is_registered,
            is_paid,
            payment_amount,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_video_gen_request` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_video_gen_request_then(
        &self,
        principal: String,
        model_name: String,
        prompt: String,
        property: String,
        token_type: TokenType,
        is_registered: bool,
        is_paid: bool,
        payment_amount: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_video_gen_request for super::RemoteReducers {
    fn create_video_gen_request_then(
        &self,
        principal: String,
        model_name: String,
        prompt: String,
        property: String,
        token_type: TokenType,
        is_registered: bool,
        is_paid: bool,
        payment_amount: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateVideoGenRequestArgs {
                principal,
                model_name,
                prompt,
                property,
                token_type,
                is_registered,
                is_paid,
                payment_amount,
            },
            callback,
        )
    }
}
