// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DecrementRateLimitPaidPropertyOnlyArgs {
    pub property: String,
}

impl From<DecrementRateLimitPaidPropertyOnlyArgs> for super::Reducer {
    fn from(args: DecrementRateLimitPaidPropertyOnlyArgs) -> Self {
        Self::DecrementRateLimitPaidPropertyOnly {
            property: args.property,
        }
    }
}

impl __sdk::InModule for DecrementRateLimitPaidPropertyOnlyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `decrement_rate_limit_paid_property_only`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait decrement_rate_limit_paid_property_only {
    /// Request that the remote module invoke the reducer `decrement_rate_limit_paid_property_only` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`decrement_rate_limit_paid_property_only:decrement_rate_limit_paid_property_only_then`] to run a callback after the reducer completes.
    fn decrement_rate_limit_paid_property_only(&self, property: String) -> __sdk::Result<()> {
        self.decrement_rate_limit_paid_property_only_then(property, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `decrement_rate_limit_paid_property_only` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn decrement_rate_limit_paid_property_only_then(
        &self,
        property: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl decrement_rate_limit_paid_property_only for super::RemoteReducers {
    fn decrement_rate_limit_paid_property_only_then(
        &self,
        property: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DecrementRateLimitPaidPropertyOnlyArgs { property },
            callback,
        )
    }
}
