// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::following_page_type::FollowingPage;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct GetFollowingArgs {
    pub principal_text: String,
    pub limit: u64,
    pub cursor: Option<String>,
}

impl __sdk::InModule for GetFollowingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `get_following`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait get_following {
    fn get_following(&self, principal_text: String, limit: u64, cursor: Option<String>) {
        self.get_following_then(principal_text, limit, cursor, |_, _| {});
    }

    fn get_following_then(
        &self,
        principal_text: String,
        limit: u64,
        cursor: Option<String>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<FollowingPage, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl get_following for super::RemoteProcedures {
    fn get_following_then(
        &self,
        principal_text: String,
        limit: u64,
        cursor: Option<String>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<FollowingPage, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp.invoke_procedure_with_callback::<_, FollowingPage>(
            "get_following",
            GetFollowingArgs {
                principal_text,
                limit,
                cursor,
            },
            __callback,
        );
    }
}
