// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::videogen_config_response_type::VideogenConfigResponse;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct GetVideogenConfigArgs {}

impl __sdk::InModule for GetVideogenConfigArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `get_videogen_config`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait get_videogen_config {
    fn get_videogen_config(&self) {
        self.get_videogen_config_then(|_, _| {});
    }

    fn get_videogen_config_then(
        &self,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<VideogenConfigResponse, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl get_videogen_config for super::RemoteProcedures {
    fn get_videogen_config_then(
        &self,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<VideogenConfigResponse, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, VideogenConfigResponse>(
                "get_videogen_config",
                GetVideogenConfigArgs {},
                __callback,
            );
    }
}
