// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::rate_limit_response_type::RateLimitResponse;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct GetRateLimitArgs {
    pub principal: String,
    pub property: String,
    pub is_registered: bool,
}

impl __sdk::InModule for GetRateLimitArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `get_rate_limit`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait get_rate_limit {
    fn get_rate_limit(&self, principal: String, property: String, is_registered: bool) {
        self.get_rate_limit_then(principal, property, is_registered, |_, _| {});
    }

    fn get_rate_limit_then(
        &self,
        principal: String,
        property: String,
        is_registered: bool,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<RateLimitResponse, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl get_rate_limit for super::RemoteProcedures {
    fn get_rate_limit_then(
        &self,
        principal: String,
        property: String,
        is_registered: bool,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<RateLimitResponse, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, RateLimitResponse>(
                "get_rate_limit",
                GetRateLimitArgs {
                    principal,
                    property,
                    is_registered,
                },
                __callback,
            );
    }
}
