// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::post_details_for_frontend_type::PostDetailsForFrontend;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
 struct GetPostByIdArgs {
    pub post_id: String,
}


impl __sdk::InModule for GetPostByIdArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `get_post_by_id`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait get_post_by_id {
    fn get_post_by_id(&self, post_id: String,
) {
        self.get_post_by_id_then(post_id,  |_, _| {});
    }

    fn get_post_by_id_then(
        &self,
        post_id: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Option::<PostDetailsForFrontend>, __sdk::InternalError>) + Send + 'static,
    );
}

impl get_post_by_id for super::RemoteProcedures {
    fn get_post_by_id_then(
        &self,
        post_id: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Option::<PostDetailsForFrontend>, __sdk::InternalError>) + Send + 'static,
    ) {
        self.imp.invoke_procedure_with_callback::<_, Option::<PostDetailsForFrontend>>(
            "get_post_by_id",
            GetPostByIdArgs { post_id,  },
            __callback,
        );
    }
}

