// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IncrementRateLimitPaidArgs {
    pub principal: String,
    pub property: String,
    pub is_registered: bool,
    pub is_paid: bool,
    pub payment_amount: Option<String>,
}

impl From<IncrementRateLimitPaidArgs> for super::Reducer {
    fn from(args: IncrementRateLimitPaidArgs) -> Self {
        Self::IncrementRateLimitPaid {
            principal: args.principal,
            property: args.property,
            is_registered: args.is_registered,
            is_paid: args.is_paid,
            payment_amount: args.payment_amount,
        }
    }
}

impl __sdk::InModule for IncrementRateLimitPaidArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `increment_rate_limit_paid`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait increment_rate_limit_paid {
    /// Request that the remote module invoke the reducer `increment_rate_limit_paid` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`increment_rate_limit_paid:increment_rate_limit_paid_then`] to run a callback after the reducer completes.
    fn increment_rate_limit_paid(
        &self,
        principal: String,
        property: String,
        is_registered: bool,
        is_paid: bool,
        payment_amount: Option<String>,
    ) -> __sdk::Result<()> {
        self.increment_rate_limit_paid_then(
            principal,
            property,
            is_registered,
            is_paid,
            payment_amount,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `increment_rate_limit_paid` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn increment_rate_limit_paid_then(
        &self,
        principal: String,
        property: String,
        is_registered: bool,
        is_paid: bool,
        payment_amount: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl increment_rate_limit_paid for super::RemoteReducers {
    fn increment_rate_limit_paid_then(
        &self,
        principal: String,
        property: String,
        is_registered: bool,
        is_paid: bool,
        payment_amount: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            IncrementRateLimitPaidArgs {
                principal,
                property,
                is_registered,
                is_paid,
                payment_amount,
            },
            callback,
        )
    }
}
