// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::kv_has_result_type::KvHasResult;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
 struct KvHasArgs {
    pub key: String,
}


impl __sdk::InModule for KvHasArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `kv_has`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait kv_has {
    fn kv_has(&self, key: String,
) {
        self.kv_has_then(key,  |_, _| {});
    }

    fn kv_has_then(
        &self,
        key: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<KvHasResult, __sdk::InternalError>) + Send + 'static,
    );
}

impl kv_has for super::RemoteProcedures {
    fn kv_has_then(
        &self,
        key: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<KvHasResult, __sdk::InternalError>) + Send + 'static,
    ) {
        self.imp.invoke_procedure_with_callback::<_, KvHasResult>(
            "kv_has",
            KvHasArgs { key,  },
            __callback,
        );
    }
}

