// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct KvSetArgs {
    pub key: String,
    pub value: String,
}

impl From<KvSetArgs> for super::Reducer {
    fn from(args: KvSetArgs) -> Self {
        Self::KvSet {
            key: args.key,
            value: args.value,
}
}
}

impl __sdk::InModule for KvSetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `kv_set`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait kv_set {
    /// Request that the remote module invoke the reducer `kv_set` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`kv_set:kv_set_then`] to run a callback after the reducer completes.
    fn kv_set(&self, key: String,
value: String,
) -> __sdk::Result<()> {
        self.kv_set_then(key, value,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `kv_set` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn kv_set_then(
        &self,
        key: String,
value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl kv_set for super::RemoteReducers {
    fn kv_set_then(
        &self,
        key: String,
value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(KvSetArgs { key, value,  }, callback)
    }
}

