// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ModuleAdmin {
    pub identity: __sdk::Identity,
}

impl __sdk::InModule for ModuleAdmin {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ModuleAdmin`.
///
/// Provides typed access to columns for query building.
pub struct ModuleAdminCols {
    pub identity: __sdk::__query_builder::Col<ModuleAdmin, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for ModuleAdmin {
    type Cols = ModuleAdminCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ModuleAdminCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
        }
    }
}

/// Indexed column accessor struct for the table `ModuleAdmin`.
///
/// Provides typed access to indexed columns for query building.
pub struct ModuleAdminIxCols {
    pub identity: __sdk::__query_builder::IxCol<ModuleAdmin, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ModuleAdmin {
    type IxCols = ModuleAdminIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ModuleAdminIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ModuleAdmin {}
