// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::post_status_type::PostStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Post {
    pub id: String,
    pub creator: __sdk::Identity,
    pub video_uid: String,
    pub description: String,
    pub hashtags: Vec::<String>,
    pub status: PostStatus,
    pub created_at: __sdk::Timestamp,
    pub share_count: u64,
    pub view_total_count: u64,
    pub view_threshold_count: u64,
    pub view_average_watch_percentage: u8,
}


impl __sdk::InModule for Post {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Post`.
///
/// Provides typed access to columns for query building.
pub struct PostCols {
    pub id: __sdk::__query_builder::Col<Post, String>,
    pub creator: __sdk::__query_builder::Col<Post, __sdk::Identity>,
    pub video_uid: __sdk::__query_builder::Col<Post, String>,
    pub description: __sdk::__query_builder::Col<Post, String>,
    pub hashtags: __sdk::__query_builder::Col<Post, Vec::<String>>,
    pub status: __sdk::__query_builder::Col<Post, PostStatus>,
    pub created_at: __sdk::__query_builder::Col<Post, __sdk::Timestamp>,
    pub share_count: __sdk::__query_builder::Col<Post, u64>,
    pub view_total_count: __sdk::__query_builder::Col<Post, u64>,
    pub view_threshold_count: __sdk::__query_builder::Col<Post, u64>,
    pub view_average_watch_percentage: __sdk::__query_builder::Col<Post, u8>,
}

impl __sdk::__query_builder::HasCols for Post {
    type Cols = PostCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PostCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            creator: __sdk::__query_builder::Col::new(table_name, "creator"),
            video_uid: __sdk::__query_builder::Col::new(table_name, "video_uid"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            hashtags: __sdk::__query_builder::Col::new(table_name, "hashtags"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            share_count: __sdk::__query_builder::Col::new(table_name, "share_count"),
            view_total_count: __sdk::__query_builder::Col::new(table_name, "view_total_count"),
            view_threshold_count: __sdk::__query_builder::Col::new(table_name, "view_threshold_count"),
            view_average_watch_percentage: __sdk::__query_builder::Col::new(table_name, "view_average_watch_percentage"),

        }
    }
}

/// Indexed column accessor struct for the table `Post`.
///
/// Provides typed access to indexed columns for query building.
pub struct PostIxCols {
    pub creator: __sdk::__query_builder::IxCol<Post, __sdk::Identity>,
    pub id: __sdk::__query_builder::IxCol<Post, String>,
}

impl __sdk::__query_builder::HasIxCols for Post {
    type IxCols = PostIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PostIxCols {
            creator: __sdk::__query_builder::IxCol::new(table_name, "creator"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Post {}

