// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PropertyRateLimit {
    pub id: u64,
    pub property: String,
    pub request_count: u64,
    pub window_start: u64,
}

impl __sdk::InModule for PropertyRateLimit {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PropertyRateLimit`.
///
/// Provides typed access to columns for query building.
pub struct PropertyRateLimitCols {
    pub id: __sdk::__query_builder::Col<PropertyRateLimit, u64>,
    pub property: __sdk::__query_builder::Col<PropertyRateLimit, String>,
    pub request_count: __sdk::__query_builder::Col<PropertyRateLimit, u64>,
    pub window_start: __sdk::__query_builder::Col<PropertyRateLimit, u64>,
}

impl __sdk::__query_builder::HasCols for PropertyRateLimit {
    type Cols = PropertyRateLimitCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PropertyRateLimitCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            property: __sdk::__query_builder::Col::new(table_name, "property"),
            request_count: __sdk::__query_builder::Col::new(table_name, "request_count"),
            window_start: __sdk::__query_builder::Col::new(table_name, "window_start"),
        }
    }
}

/// Indexed column accessor struct for the table `PropertyRateLimit`.
///
/// Provides typed access to indexed columns for query building.
pub struct PropertyRateLimitIxCols {
    pub id: __sdk::__query_builder::IxCol<PropertyRateLimit, u64>,
    pub property: __sdk::__query_builder::IxCol<PropertyRateLimit, String>,
}

impl __sdk::__query_builder::HasIxCols for PropertyRateLimit {
    type IxCols = PropertyRateLimitIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PropertyRateLimitIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            property: __sdk::__query_builder::IxCol::new(table_name, "property"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PropertyRateLimit {}
