// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::property_rate_limit_type::PropertyRateLimit;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `property_rate_limit`.
///
/// Obtain a handle from the [`PropertyRateLimitTableAccess::property_rate_limit`] method on [`super::RemoteTables`],
/// like `ctx.db.property_rate_limit()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.property_rate_limit().on_insert(...)`.
pub struct PropertyRateLimitTableHandle<'ctx> {
    imp: __sdk::TableHandle<PropertyRateLimit>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `property_rate_limit`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PropertyRateLimitTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PropertyRateLimitTableHandle`], which mediates access to the table `property_rate_limit`.
    fn property_rate_limit(&self) -> PropertyRateLimitTableHandle<'_>;
}

impl PropertyRateLimitTableAccess for super::RemoteTables {
    fn property_rate_limit(&self) -> PropertyRateLimitTableHandle<'_> {
        PropertyRateLimitTableHandle {
            imp: self
                .imp
                .get_table::<PropertyRateLimit>("property_rate_limit"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PropertyRateLimitInsertCallbackId(__sdk::CallbackId);
pub struct PropertyRateLimitDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PropertyRateLimitTableHandle<'ctx> {
    type Row = PropertyRateLimit;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PropertyRateLimit> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PropertyRateLimitInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PropertyRateLimitInsertCallbackId {
        PropertyRateLimitInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PropertyRateLimitInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PropertyRateLimitDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PropertyRateLimitDeleteCallbackId {
        PropertyRateLimitDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PropertyRateLimitDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PropertyRateLimitUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PropertyRateLimitTableHandle<'ctx> {
    type UpdateCallbackId = PropertyRateLimitUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PropertyRateLimitUpdateCallbackId {
        PropertyRateLimitUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PropertyRateLimitUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `property_rate_limit`,
/// which allows point queries on the field of the same name
/// via the [`PropertyRateLimitIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.property_rate_limit().id().find(...)`.
pub struct PropertyRateLimitIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PropertyRateLimit, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PropertyRateLimitTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `property_rate_limit`.
    pub fn id(&self) -> PropertyRateLimitIdUnique<'ctx> {
        PropertyRateLimitIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PropertyRateLimitIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PropertyRateLimit> {
        self.imp.find(col_val)
    }
}

/// Access to the `property` unique index on the table `property_rate_limit`,
/// which allows point queries on the field of the same name
/// via the [`PropertyRateLimitPropertyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.property_rate_limit().property().find(...)`.
pub struct PropertyRateLimitPropertyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PropertyRateLimit, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PropertyRateLimitTableHandle<'ctx> {
    /// Get a handle on the `property` unique index on the table `property_rate_limit`.
    pub fn property(&self) -> PropertyRateLimitPropertyUnique<'ctx> {
        PropertyRateLimitPropertyUnique {
            imp: self.imp.get_unique_constraint::<String>("property"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PropertyRateLimitPropertyUnique<'ctx> {
    /// Find the subscribed row whose `property` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PropertyRateLimit> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PropertyRateLimit>("property_rate_limit");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("property", |row| &row.property);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PropertyRateLimit>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PropertyRateLimit>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PropertyRateLimit`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait property_rate_limitQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PropertyRateLimit`.
    fn property_rate_limit(&self) -> __sdk::__query_builder::Table<PropertyRateLimit>;
}

impl property_rate_limitQueryTableAccess for __sdk::QueryTableAccessor {
    fn property_rate_limit(&self) -> __sdk::__query_builder::Table<PropertyRateLimit> {
        __sdk::__query_builder::Table::new("property_rate_limit")
    }
}
