// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RateLimit {
    pub principal: String,
    pub remaining: u64,
    pub day_start: __sdk::Timestamp,
}

impl __sdk::InModule for RateLimit {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RateLimit`.
///
/// Provides typed access to columns for query building.
pub struct RateLimitCols {
    pub principal: __sdk::__query_builder::Col<RateLimit, String>,
    pub remaining: __sdk::__query_builder::Col<RateLimit, u64>,
    pub day_start: __sdk::__query_builder::Col<RateLimit, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for RateLimit {
    type Cols = RateLimitCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RateLimitCols {
            principal: __sdk::__query_builder::Col::new(table_name, "principal"),
            remaining: __sdk::__query_builder::Col::new(table_name, "remaining"),
            day_start: __sdk::__query_builder::Col::new(table_name, "day_start"),
        }
    }
}

/// Indexed column accessor struct for the table `RateLimit`.
///
/// Provides typed access to indexed columns for query building.
pub struct RateLimitIxCols {
    pub principal: __sdk::__query_builder::IxCol<RateLimit, String>,
}

impl __sdk::__query_builder::HasIxCols for RateLimit {
    type IxCols = RateLimitIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RateLimitIxCols {
            principal: __sdk::__query_builder::IxCol::new(table_name, "principal"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RateLimit {}
