// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::rate_limit_type::RateLimit;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rate_limit`.
///
/// Obtain a handle from the [`RateLimitTableAccess::rate_limit`] method on [`super::RemoteTables`],
/// like `ctx.db.rate_limit()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rate_limit().on_insert(...)`.
pub struct RateLimitTableHandle<'ctx> {
    imp: __sdk::TableHandle<RateLimit>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rate_limit`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RateLimitTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RateLimitTableHandle`], which mediates access to the table `rate_limit`.
    fn rate_limit(&self) -> RateLimitTableHandle<'_>;
}

impl RateLimitTableAccess for super::RemoteTables {
    fn rate_limit(&self) -> RateLimitTableHandle<'_> {
        RateLimitTableHandle {
            imp: self.imp.get_table::<RateLimit>("rate_limit"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RateLimitInsertCallbackId(__sdk::CallbackId);
pub struct RateLimitDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RateLimitTableHandle<'ctx> {
    type Row = RateLimit;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RateLimit> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RateLimitInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RateLimitInsertCallbackId {
        RateLimitInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RateLimitInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RateLimitDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RateLimitDeleteCallbackId {
        RateLimitDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RateLimitDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RateLimitUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RateLimitTableHandle<'ctx> {
    type UpdateCallbackId = RateLimitUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RateLimitUpdateCallbackId {
        RateLimitUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RateLimitUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `rate_limit`,
/// which allows point queries on the field of the same name
/// via the [`RateLimitIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rate_limit().id().find(...)`.
pub struct RateLimitIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RateLimit, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RateLimitTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `rate_limit`.
    pub fn id(&self) -> RateLimitIdUnique<'ctx> {
        RateLimitIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RateLimitIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RateLimit> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RateLimit>("rate_limit");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RateLimit>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RateLimit>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RateLimit`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait rate_limitQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RateLimit`.
    fn rate_limit(&self) -> __sdk::__query_builder::Table<RateLimit>;
}

impl rate_limitQueryTableAccess for __sdk::QueryTableAccessor {
    fn rate_limit(&self) -> __sdk::__query_builder::Table<RateLimit> {
        __sdk::__query_builder::Table::new("rate_limit")
    }
}
