// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RefundCreditArgs {
    pub principal: String,
}

impl From<RefundCreditArgs> for super::Reducer {
    fn from(args: RefundCreditArgs) -> Self {
        Self::RefundCredit {
            principal: args.principal,
        }
    }
}

impl __sdk::InModule for RefundCreditArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `refund_credit`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait refund_credit {
    /// Request that the remote module invoke the reducer `refund_credit` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`refund_credit:refund_credit_then`] to run a callback after the reducer completes.
    fn refund_credit(&self, principal: String) -> __sdk::Result<()> {
        self.refund_credit_then(principal, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `refund_credit` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn refund_credit_then(
        &self,
        principal: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl refund_credit for super::RemoteReducers {
    fn refund_credit_then(
        &self,
        principal: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RefundCreditArgs { principal }, callback)
    }
}
