// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateProfileDetailsArgs {
    pub bio: String,
    pub website_url: String,
    pub profile_pic_url: String,
}

impl From<UpdateProfileDetailsArgs> for super::Reducer {
    fn from(args: UpdateProfileDetailsArgs) -> Self {
        Self::UpdateProfileDetails {
            bio: args.bio,
            website_url: args.website_url,
            profile_pic_url: args.profile_pic_url,
        }
    }
}

impl __sdk::InModule for UpdateProfileDetailsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_profile_details`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_profile_details {
    /// Request that the remote module invoke the reducer `update_profile_details` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_profile_details:update_profile_details_then`] to run a callback after the reducer completes.
    fn update_profile_details(
        &self,
        bio: String,
        website_url: String,
        profile_pic_url: String,
    ) -> __sdk::Result<()> {
        self.update_profile_details_then(bio, website_url, profile_pic_url, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_profile_details` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_profile_details_then(
        &self,
        bio: String,
        website_url: String,
        profile_pic_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_profile_details for super::RemoteReducers {
    fn update_profile_details_then(
        &self,
        bio: String,
        website_url: String,
        profile_pic_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateProfileDetailsArgs {
                bio,
                website_url,
                profile_pic_url,
            },
            callback,
        )
    }
}
