// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::video_gen_request_status_type::VideoGenRequestStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateVideoGenStatusArgs {
    pub principal: String,
    pub counter: u64,
    pub status: VideoGenRequestStatus,
}

impl From<UpdateVideoGenStatusArgs> for super::Reducer {
    fn from(args: UpdateVideoGenStatusArgs) -> Self {
        Self::UpdateVideoGenStatus {
            principal: args.principal,
            counter: args.counter,
            status: args.status,
        }
    }
}

impl __sdk::InModule for UpdateVideoGenStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_video_gen_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_video_gen_status {
    /// Request that the remote module invoke the reducer `update_video_gen_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_video_gen_status:update_video_gen_status_then`] to run a callback after the reducer completes.
    fn update_video_gen_status(
        &self,
        principal: String,
        counter: u64,
        status: VideoGenRequestStatus,
    ) -> __sdk::Result<()> {
        self.update_video_gen_status_then(principal, counter, status, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_video_gen_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_video_gen_status_then(
        &self,
        principal: String,
        counter: u64,
        status: VideoGenRequestStatus,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_video_gen_status for super::RemoteReducers {
    fn update_video_gen_status_then(
        &self,
        principal: String,
        counter: u64,
        status: VideoGenRequestStatus,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateVideoGenStatusArgs {
                principal,
                counter,
                status,
            },
            callback,
        )
    }
}
