// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::post_v_2_type::PostV2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertPostV2Args {
    pub post: PostV2,
}

impl From<UpsertPostV2Args> for super::Reducer {
    fn from(args: UpsertPostV2Args) -> Self {
        Self::UpsertPostV2 { post: args.post }
    }
}

impl __sdk::InModule for UpsertPostV2Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_post_v_2`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_post_v_2 {
    /// Request that the remote module invoke the reducer `upsert_post_v_2` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_post_v_2:upsert_post_v_2_then`] to run a callback after the reducer completes.
    fn upsert_post_v_2(&self, post: PostV2) -> __sdk::Result<()> {
        self.upsert_post_v_2_then(post, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_post_v_2` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_post_v_2_then(
        &self,
        post: PostV2,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_post_v_2 for super::RemoteReducers {
    fn upsert_post_v_2_then(
        &self,
        post: PostV2,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertPostV2Args { post }, callback)
    }
}
