// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_follow_type::UserFollow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_follows`.
///
/// Obtain a handle from the [`UserFollowsTableAccess::user_follows`] method on [`super::RemoteTables`],
/// like `ctx.db.user_follows()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_follows().on_insert(...)`.
pub struct UserFollowsTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserFollow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_follows`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserFollowsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserFollowsTableHandle`], which mediates access to the table `user_follows`.
    fn user_follows(&self) -> UserFollowsTableHandle<'_>;
}

impl UserFollowsTableAccess for super::RemoteTables {
    fn user_follows(&self) -> UserFollowsTableHandle<'_> {
        UserFollowsTableHandle {
            imp: self.imp.get_table::<UserFollow>("user_follows"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserFollowsInsertCallbackId(__sdk::CallbackId);
pub struct UserFollowsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserFollowsTableHandle<'ctx> {
    type Row = UserFollow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserFollow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserFollowsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserFollowsInsertCallbackId {
        UserFollowsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserFollowsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserFollowsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserFollowsDeleteCallbackId {
        UserFollowsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserFollowsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserFollowsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserFollowsTableHandle<'ctx> {
    type UpdateCallbackId = UserFollowsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserFollowsUpdateCallbackId {
        UserFollowsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserFollowsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `user_follows`,
/// which allows point queries on the field of the same name
/// via the [`UserFollowsKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_follows().key().find(...)`.
pub struct UserFollowsKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserFollow, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserFollowsTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `user_follows`.
    pub fn key(&self) -> UserFollowsKeyUnique<'ctx> {
        UserFollowsKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserFollowsKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserFollow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserFollow>("user_follows");
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserFollow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserFollow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserFollow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_followsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserFollow`.
    fn user_follows(&self) -> __sdk::__query_builder::Table<UserFollow>;
}

impl user_followsQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_follows(&self) -> __sdk::__query_builder::Table<UserFollow> {
        __sdk::__query_builder::Table::new("user_follows")
    }
}
