// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_request_counter_type::UserRequestCounter;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_request_counter`.
///
/// Obtain a handle from the [`UserRequestCounterTableAccess::user_request_counter`] method on [`super::RemoteTables`],
/// like `ctx.db.user_request_counter()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_request_counter().on_insert(...)`.
pub struct UserRequestCounterTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserRequestCounter>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_request_counter`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserRequestCounterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserRequestCounterTableHandle`], which mediates access to the table `user_request_counter`.
    fn user_request_counter(&self) -> UserRequestCounterTableHandle<'_>;
}

impl UserRequestCounterTableAccess for super::RemoteTables {
    fn user_request_counter(&self) -> UserRequestCounterTableHandle<'_> {
        UserRequestCounterTableHandle {
            imp: self
                .imp
                .get_table::<UserRequestCounter>("user_request_counter"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserRequestCounterInsertCallbackId(__sdk::CallbackId);
pub struct UserRequestCounterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserRequestCounterTableHandle<'ctx> {
    type Row = UserRequestCounter;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserRequestCounter> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserRequestCounterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserRequestCounterInsertCallbackId {
        UserRequestCounterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserRequestCounterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserRequestCounterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserRequestCounterDeleteCallbackId {
        UserRequestCounterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserRequestCounterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserRequestCounterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserRequestCounterTableHandle<'ctx> {
    type UpdateCallbackId = UserRequestCounterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserRequestCounterUpdateCallbackId {
        UserRequestCounterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserRequestCounterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `user_request_counter`,
/// which allows point queries on the field of the same name
/// via the [`UserRequestCounterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_request_counter().id().find(...)`.
pub struct UserRequestCounterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserRequestCounter, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserRequestCounterTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `user_request_counter`.
    pub fn id(&self) -> UserRequestCounterIdUnique<'ctx> {
        UserRequestCounterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserRequestCounterIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<UserRequestCounter> {
        self.imp.find(col_val)
    }
}

/// Access to the `principal` unique index on the table `user_request_counter`,
/// which allows point queries on the field of the same name
/// via the [`UserRequestCounterPrincipalUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_request_counter().principal().find(...)`.
pub struct UserRequestCounterPrincipalUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserRequestCounter, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserRequestCounterTableHandle<'ctx> {
    /// Get a handle on the `principal` unique index on the table `user_request_counter`.
    pub fn principal(&self) -> UserRequestCounterPrincipalUnique<'ctx> {
        UserRequestCounterPrincipalUnique {
            imp: self.imp.get_unique_constraint::<String>("principal"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserRequestCounterPrincipalUnique<'ctx> {
    /// Find the subscribed row whose `principal` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserRequestCounter> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserRequestCounter>("user_request_counter");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("principal", |row| &row.principal);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserRequestCounter>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserRequestCounter>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserRequestCounter`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_request_counterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserRequestCounter`.
    fn user_request_counter(&self) -> __sdk::__query_builder::Table<UserRequestCounter>;
}

impl user_request_counterQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_request_counter(&self) -> __sdk::__query_builder::Table<UserRequestCounter> {
        __sdk::__query_builder::Table::new("user_request_counter")
    }
}
