// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserRequestCounter {
    pub id: u64,
    pub principal: String,
    pub counter: u64,
}

impl __sdk::InModule for UserRequestCounter {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserRequestCounter`.
///
/// Provides typed access to columns for query building.
pub struct UserRequestCounterCols {
    pub id: __sdk::__query_builder::Col<UserRequestCounter, u64>,
    pub principal: __sdk::__query_builder::Col<UserRequestCounter, String>,
    pub counter: __sdk::__query_builder::Col<UserRequestCounter, u64>,
}

impl __sdk::__query_builder::HasCols for UserRequestCounter {
    type Cols = UserRequestCounterCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserRequestCounterCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            principal: __sdk::__query_builder::Col::new(table_name, "principal"),
            counter: __sdk::__query_builder::Col::new(table_name, "counter"),
        }
    }
}

/// Indexed column accessor struct for the table `UserRequestCounter`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserRequestCounterIxCols {
    pub id: __sdk::__query_builder::IxCol<UserRequestCounter, u64>,
    pub principal: __sdk::__query_builder::IxCol<UserRequestCounter, String>,
}

impl __sdk::__query_builder::HasIxCols for UserRequestCounter {
    type IxCols = UserRequestCounterIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserRequestCounterIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            principal: __sdk::__query_builder::IxCol::new(table_name, "principal"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserRequestCounter {}
