// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::subscription_plan_type::SubscriptionPlan;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserProfileDetailsV4 {
    pub principal_text: String,
    pub bio: String,
    pub website_url: String,
    pub profile_picture_url: String,
    pub followers_count: u64,
    pub following_count: u64,
    pub subscription_plan: SubscriptionPlan,
    pub is_ai_influencer: bool,
    pub caller_follows_user: bool,
    pub user_follows_caller: bool,
}

impl __sdk::InModule for UserProfileDetailsV4 {
    type Module = super::RemoteModule;
}
