// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::subscription_plan_type::SubscriptionPlan;
use super::user_profile_type::UserProfile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_profiles`.
///
/// Obtain a handle from the [`UserProfilesTableAccess::user_profiles`] method on [`super::RemoteTables`],
/// like `ctx.db.user_profiles()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_profiles().on_insert(...)`.
pub struct UserProfilesTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserProfile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_profiles`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserProfilesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserProfilesTableHandle`], which mediates access to the table `user_profiles`.
    fn user_profiles(&self) -> UserProfilesTableHandle<'_>;
}

impl UserProfilesTableAccess for super::RemoteTables {
    fn user_profiles(&self) -> UserProfilesTableHandle<'_> {
        UserProfilesTableHandle {
            imp: self.imp.get_table::<UserProfile>("user_profiles"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserProfilesInsertCallbackId(__sdk::CallbackId);
pub struct UserProfilesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserProfilesTableHandle<'ctx> {
    type Row = UserProfile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserProfile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserProfilesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserProfilesInsertCallbackId {
        UserProfilesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserProfilesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserProfilesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserProfilesDeleteCallbackId {
        UserProfilesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserProfilesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserProfilesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserProfilesTableHandle<'ctx> {
    type UpdateCallbackId = UserProfilesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserProfilesUpdateCallbackId {
        UserProfilesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserProfilesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `principal_text` unique index on the table `user_profiles`,
/// which allows point queries on the field of the same name
/// via the [`UserProfilesPrincipalTextUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_profiles().principal_text().find(...)`.
pub struct UserProfilesPrincipalTextUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserProfile, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserProfilesTableHandle<'ctx> {
    /// Get a handle on the `principal_text` unique index on the table `user_profiles`.
    pub fn principal_text(&self) -> UserProfilesPrincipalTextUnique<'ctx> {
        UserProfilesPrincipalTextUnique {
            imp: self.imp.get_unique_constraint::<String>("principal_text"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserProfilesPrincipalTextUnique<'ctx> {
    /// Find the subscribed row whose `principal_text` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserProfile> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserProfile>("user_profiles");
    _table.add_unique_constraint::<String>("principal_text", |row| &row.principal_text);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserProfile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserProfile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserProfile`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_profilesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserProfile`.
    fn user_profiles(&self) -> __sdk::__query_builder::Table<UserProfile>;
}

impl user_profilesQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_profiles(&self) -> __sdk::__query_builder::Table<UserProfile> {
        __sdk::__query_builder::Table::new("user_profiles")
    }
}
