// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::token_type_type::TokenType;
use super::video_gen_request_status_type::VideoGenRequestStatus;
use super::video_gen_request_type::VideoGenRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `video_gen_request`.
///
/// Obtain a handle from the [`VideoGenRequestTableAccess::video_gen_request`] method on [`super::RemoteTables`],
/// like `ctx.db.video_gen_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.video_gen_request().on_insert(...)`.
pub struct VideoGenRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<VideoGenRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `video_gen_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VideoGenRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VideoGenRequestTableHandle`], which mediates access to the table `video_gen_request`.
    fn video_gen_request(&self) -> VideoGenRequestTableHandle<'_>;
}

impl VideoGenRequestTableAccess for super::RemoteTables {
    fn video_gen_request(&self) -> VideoGenRequestTableHandle<'_> {
        VideoGenRequestTableHandle {
            imp: self.imp.get_table::<VideoGenRequest>("video_gen_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VideoGenRequestInsertCallbackId(__sdk::CallbackId);
pub struct VideoGenRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VideoGenRequestTableHandle<'ctx> {
    type Row = VideoGenRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VideoGenRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VideoGenRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VideoGenRequestInsertCallbackId {
        VideoGenRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VideoGenRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VideoGenRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VideoGenRequestDeleteCallbackId {
        VideoGenRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VideoGenRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VideoGenRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VideoGenRequestTableHandle<'ctx> {
    type UpdateCallbackId = VideoGenRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VideoGenRequestUpdateCallbackId {
        VideoGenRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VideoGenRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `video_gen_request`,
/// which allows point queries on the field of the same name
/// via the [`VideoGenRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.video_gen_request().id().find(...)`.
pub struct VideoGenRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VideoGenRequest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VideoGenRequestTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `video_gen_request`.
    pub fn id(&self) -> VideoGenRequestIdUnique<'ctx> {
        VideoGenRequestIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VideoGenRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<VideoGenRequest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VideoGenRequest>("video_gen_request");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VideoGenRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VideoGenRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VideoGenRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait video_gen_requestQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VideoGenRequest`.
    fn video_gen_request(&self) -> __sdk::__query_builder::Table<VideoGenRequest>;
}

impl video_gen_requestQueryTableAccess for __sdk::QueryTableAccessor {
    fn video_gen_request(&self) -> __sdk::__query_builder::Table<VideoGenRequest> {
        __sdk::__query_builder::Table::new("video_gen_request")
    }
}
