// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::token_type_type::TokenType;
use super::video_gen_request_status_type::VideoGenRequestStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct VideoGenRequest {
    pub id: u64,
    pub principal: String,
    pub counter: u64,
    pub model_name: String,
    pub prompt: String,
    pub status: VideoGenRequestStatus,
    pub created_at: u64,
    pub updated_at: u64,
    pub payment_amount: Option<String>,
    pub token_type: Option<TokenType>,
}

impl __sdk::InModule for VideoGenRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `VideoGenRequest`.
///
/// Provides typed access to columns for query building.
pub struct VideoGenRequestCols {
    pub id: __sdk::__query_builder::Col<VideoGenRequest, u64>,
    pub principal: __sdk::__query_builder::Col<VideoGenRequest, String>,
    pub counter: __sdk::__query_builder::Col<VideoGenRequest, u64>,
    pub model_name: __sdk::__query_builder::Col<VideoGenRequest, String>,
    pub prompt: __sdk::__query_builder::Col<VideoGenRequest, String>,
    pub status: __sdk::__query_builder::Col<VideoGenRequest, VideoGenRequestStatus>,
    pub created_at: __sdk::__query_builder::Col<VideoGenRequest, u64>,
    pub updated_at: __sdk::__query_builder::Col<VideoGenRequest, u64>,
    pub payment_amount: __sdk::__query_builder::Col<VideoGenRequest, Option<String>>,
    pub token_type: __sdk::__query_builder::Col<VideoGenRequest, Option<TokenType>>,
}

impl __sdk::__query_builder::HasCols for VideoGenRequest {
    type Cols = VideoGenRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        VideoGenRequestCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            principal: __sdk::__query_builder::Col::new(table_name, "principal"),
            counter: __sdk::__query_builder::Col::new(table_name, "counter"),
            model_name: __sdk::__query_builder::Col::new(table_name, "model_name"),
            prompt: __sdk::__query_builder::Col::new(table_name, "prompt"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            payment_amount: __sdk::__query_builder::Col::new(table_name, "payment_amount"),
            token_type: __sdk::__query_builder::Col::new(table_name, "token_type"),
        }
    }
}

/// Indexed column accessor struct for the table `VideoGenRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct VideoGenRequestIxCols {
    pub id: __sdk::__query_builder::IxCol<VideoGenRequest, u64>,
}

impl __sdk::__query_builder::HasIxCols for VideoGenRequest {
    type IxCols = VideoGenRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        VideoGenRequestIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for VideoGenRequest {}
