[package]
name = "yral-metadata-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-agent = { workspace = true }
identity = { workspace = true, default-features = false, features = [
  "ic-agent",
] }
reqwest = {
  workspace = true,
  default-features = false,
  features = [
    "http2",
    "json",
  ]
}
thiserror = { workspace = true }
types = { package = "yral-metadata-types", path = "../types" }

[features]
default = []
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls"]
