---
apiVersion: v1
kind: Service
metadata:
  name: snowplow-collector
  namespace: snowplow
spec:
  selector:
    app: snowplow-collector
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: ClusterIP
