apiVersion: ENC[AES256_GCM,data:B0A=,iv:laUmxd411nvPonb099vx0SwbVgFkWk/4SQE87hf39TU=,tag:pRARstWY5xhQqp/84kU47w==,type:str]
kind: ENC[AES256_GCM,data:0OQKZz1s,iv:NYRA9/eoOX4wOZVPgVdjNURHPASPYs4YwOH+C8nmOqM=,tag:A+j5QDlkZE2JpFLsvOqZFA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:K5JG6gPmSP2j1pRnGIUD4dRCpA==,iv:rnunnDXyXwoaTTLvPW9nssU3dWFXc9pJsUUvaBUz3kY=,tag:qMkriU1CLnTIMjCAMRpecg==,type:str]
    namespace: ENC[AES256_GCM,data:Ajj8NFwCddo=,iv:DUFWE6CKOIoH//9DW8nVJAXyr0nFJKdMQq7j7NOe3zc=,tag:LEQ2PohjVABZIimTWLY18w==,type:str]
stringData:
    account-id: ENC[AES256_GCM,data:xMdG4s711w==,iv:SM3nEdZitqMVvO8tW1v70ylyDWUONcBIrobneT/8qOo=,tag:YqIEa842LTC6qq6dIp7ciw==,type:str]
    license-key: ENC[AES256_GCM,data:4XOV7PWNok20EsOuVfB80tlkxpXJnqviaCYLmjWpDOOgquoj3GAzFQ==,iv:DD4f9iVgQNsOcbKH/PdYykjrfqWaco1poDQ44gBK0Qk=,tag:CvVKD9nhCJ3TmAGFmQChRQ==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VUJmOHdJMzhON3Z0WVk2
            TjYwWWFCcTE2dDFWSVloSUkrcXVjRG1Tanc0CnM0MkpXNnBRaFNPSWJHb2hkaEFw
            M2xYRks0NXRUUnl1OHJlMnZhVk5IcEEKLS0tIFh4OTh2bktNenVaUXJJOVlsSVNz
            Mk9WOEQrbDZqRktmMUh3QUVVanBQcEEKd7R0C1CNTSImaaOUzqU4/nllSiVOxKDc
            HoOiaL7D52MYPUzWlCxvFYUzH3ZJ6IOzqciL9MaVKZhkcKhCbn+E1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T17:44:57Z"
    mac: ENC[AES256_GCM,data:HHVLsQE4ZbCAqE2YTGVJBlwhtxDwtQiVGnOLPA2HiSWUYz71zEpFhN12Ea3oJdejsmSVTyoCcIGWSZ0Fz09Y79Y/IxYJuTZk5NGkeYYuMNfPfI/SzG38Zjm+WxpAbCwlJu111tNwo5l9c1pduNT9BDXB9fYkJiyHW7tFpWydv2c=,iv:VBeXSAt6D9l/r24iCng8ukn2QIOVUWTAGjVSV+xZN6Q=,tag:6gJ0NMKhuuF8fvm8KCqboA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
