apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hubble-ui.yaml
  - grafana.yaml
  - headlamp.yaml
  - snowplow-collector.yaml
  - dashboard.yaml
  - kafka-console.yaml
  - metabase.yaml
  - bytebase.yaml
  - harbor.yaml
  - cloudbeaver.yaml
  - kafka.yaml
  - kafka-referencegrant.yaml
  - kafka-bridge.yaml
  - kafka-bridge-referencegrant.yaml
  - yral-auth.yaml
  - yral-auth-build.yaml
  - yral-legacy.yaml
  - yral-legacy-build.yaml
  - yral-metadata.yaml
  - yral-metadata-build.yaml
  - off-chain-agent.yaml
  - off-chain-agent-build.yaml
  - my-website.yaml
  - my-website-build.yaml
