apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hubble-ui.yaml
  - grafana.yaml
  - ceph-dashboard.yaml
  - headlamp.yaml
  - snowplow-collector.yaml
  - dashboard.yaml
  - kafka-console.yaml
  - metabase.yaml
  - bytebase.yaml
  - rust-counter.yaml
  - harbor.yaml

