apiVersion: ENC[AES256_GCM,data:YT4=,iv:DUM3agFBD7zMrVxS8H2ksH58BwAJyk/ubA9na5VVEbc=,tag:rGUSqCnh9rP7aa7i15OQxg==,type:str]
kind: ENC[AES256_GCM,data:cygig683,iv:ZmuCDRauT8qLqKG8t2V10ZGAOmVpBOh6g2V/EozJGQg=,tag:fK2e8L313G6nqWikqDLX5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TmaAzqPH+SMQoZjYGzqUWhkADOfld2anmPqTsA==,iv:8Dha81KeP5qj2xZDEw1agpMt7GnIwnJo1dUi7uK5LKg=,tag:Zw4bmn0wBdcX9LsDbNy7IA==,type:str]
    namespace: ENC[AES256_GCM,data:EdrVh8s2LmMafQ==,iv:ChFtChCBAyOGGbeCDTjvoyCP27MQfkB8gFAH5LQal1U=,tag:xcpXFP/OixYtjLjVRGaTsQ==,type:str]
stringData:
    kafka-sasl-password: ENC[AES256_GCM,data:Nfn66xtSLLoeT+C5ESOHyxvhGWvhcVqSurqZR4Vzy0Ih78zkS7Zaug==,iv:DuG01dPrKuZzbRxlUo2QvQQGar5jxKsmZrlw9LWuOgo=,tag:yRK9078QQO5KLcFbdr2OZQ==,type:str]
type: ENC[AES256_GCM,data:JgAIeYrz,iv:D/G2vQygqkShwqO1B3SM+PzTl5jfPihc3HBGTlQkSes=,tag:KPH2ZVBLko2RWDg3raaRWg==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaFBkL0luc29TQkdDWUxl
            eWYvbFZSdHV2Q1ArbEF6cU1UY1pia2VtU21jCngybm51RlRPazJFa2M0TDN4MHAr
            TytrdjZmUDJzNGRFL0EwaEdjTmtDTFkKLS0tIGhiOVVOR3l4dU5iaG91cUdYYWtL
            Qzk3M3c4anVScWxDQ3Bsd25Cc0h6VmcKxIolcTTXsgWIjxOqOslg+MI985iFU/3F
            MZ5ywpZHB6yRPw95Fhq9a3LSms+gHS28EEHxPD6l272/V+x1cJk0EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T16:49:53Z"
    mac: ENC[AES256_GCM,data:bjzS3Tc90NHFWVZ6pdKSVNkN4sNkAC3PfXvLeHQDhQ57i0R8diX2k86BTBNcnK4i/IhYJLQk93xRvxiyYdwaykFQi6cMA1pRDEgkxfamB1KBHwNBm23usLrvpVXpOT5We26mRMxIjRhI8iQ6ceBY42KURA+VL0HIHEsjzDVJAEc=,iv:5VpNQ6O1ftgNwJHj62HTyc4uzC8BygGW25yUx8urw4w=,tag:t7/R02Fmdt3KSa6dLnwA3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
