apiVersion: ENC[AES256_GCM,data:9Ys=,iv:ulwZYdLuMQkpwiYGersfJ6Ko+oBWuZa0EjYwK031yGU=,tag:S6Ke99YBNwdMYjOCAWxCcA==,type:str]
kind: ENC[AES256_GCM,data:JhmkBX9r,iv:qntKLlSBu6V/oQrjhpdcmOEQwW0ffRrWMJf5KUpZpfM=,tag:T5JfI9iYrgmnD1kwb2XX7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RzhJHVtSEtjWWN7s1A647WNe2Q==,iv:+CeiXEKLvX3rSYvUs9sIxA2wyyR6NeB/CaJCWyY0kiM=,tag:pzwjdewMTY1XlPwa2WJrQg==,type:str]
    namespace: ENC[AES256_GCM,data:4WapZA==,iv:VplpbzTnHOWkA/Ps/84pHMjnuepwe6eJ9osnWCvy/nk=,tag:TbbkUKlLfjNzK2trv06v2A==,type:str]
type: ENC[AES256_GCM,data:Wk2QTzO3,iv:FQToT8ACDWL/aatyHypvourOODEXKnlPkVwtFoQbaho=,tag:YtP1iOKlW4LN04K1jOGhRQ==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SqUI44oTlcM3jOZ23uclCy0PUcE=,iv:Vtz2HHskwD7ACOz9x7BWf9AIocHLUdbOf40oTNgSylk=,tag:4IY9yb8qrKViXu22Br+uTQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mjXeVKJcefzUzE3ZsThs4i5EhXP82Id1d6GuT/M+WL5GXVEmJeWDxA==,iv:kFnosyIuHlUHF5AmNjuwB8xWU0MF1fLHzXb0hba9YUU=,tag:JnwmruwVXvSJjtTXr3UEOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRnlVWVFHR0JGcDA5L1Nn
            dFFKdVNmLzk3bnlEK21XZkxvWHY5VHdCd1hzCmo0ZGFRcWF4NGU0WTJoa1VCVndj
            aEo3Mzd5dyt6MDV3b3JxY0I1UUZnQkUKLS0tIFNrZDV1YzA4NFVTUXllMVNWRVV0
            ZkhaRENvZjZRU0Eyb3I3Q0ViVC9xek0K7Z41fmksgN44ZZt/6xsDM+wtid0s3hAZ
            /jUizX/XipAq2D+mlORmxCtE+8u3G490BtVzqdX3tt7FE1PO86TSQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-20T05:47:02Z"
    mac: ENC[AES256_GCM,data:bP8gnTvIC0LTKe3Vg8AlY5gN1pn1MPVhkcob2byDypRlmOk3IEOHLmzTzEHMCFIS5q97arbfw6MbiCEJAksdg2fNKuGUFdIFNqTloY3QOFVm0hsIkxxwgVIZjjgl/nWOfSyR+jAQUzBy2uGQi+YxZwFAuMuSknDOtPsflut8pgE=,iv:qO55eQArxKIwEtF7qfgtguEL+S8yJ02ofBQhQ8cvfuw=,tag:8e+tRzUR15g1/SstFAW7Hg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
