apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-0
  namespace: loki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-1replica
  resources:
    requests:
      storage: 50Gi
