apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
  namespace: my-website
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: my-website
          image: harbor.yral.com/my-website/my-website:20260821203913-26b537cb # {"$imagepolicy": "flux-system:my-website"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
