apiVersion: ENC[AES256_GCM,data:tg0=,iv:HMRAjQzvLrY8sPIXaVoa8f7rB3lVZLBHAvNrDR+REPk=,tag:4eW2XbtR8W21ZSRb/b38PQ==,type:str]
kind: ENC[AES256_GCM,data:vGE7diN4,iv:LpEOrWNm6B7Z1HmrO1BFhkKX01OlCg1A1E6kfrgfJgI=,tag:BYkiC18cF6ZaKUv4vzOpYw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PISww+9RQ7Pe8dQt5XEB1yI35Q==,iv:rTgxDNWUI5Vg+s5iVWcxuhxPddyRZp9jFmRyZvH8whU=,tag:bCbsajHkeN0yv0Ex8gDjuA==,type:str]
    namespace: ENC[AES256_GCM,data:DGpDRbwI2OvJVQ==,iv:f832JrhxmIb+JDhrgjM3qL85aGgrRSh6i/dX3l99J/k=,tag:tpajxG+UzZaCvvf74MzyLA==,type:str]
type: ENC[AES256_GCM,data:5TIpSuBFzSQtmgfeF0ozAqfOrk297r8f,iv:yDQLrgEdlJ7DwFdC9ENmLkKFba/FyDZSj1QBf/5S2vY=,tag:E516SNkgxa4TaoyzGcTzOg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:jTur,iv:SasWLdhxsEYYgKbqxsYnfEjWtn+Wd0AOOUV6cB+kxbc=,tag:+DlemvT7R2vMGP24utdouQ==,type:str]
    password: ENC[AES256_GCM,data:j4Qv3dAUpcSv/4x+vKEcsqtOe4jvBRJyVyE3wEgQ1bwUTc5MrJWLG+P4s796jH8sKfoA/54beTXCT3AI3YWy0FILpfBbB4oOTXCXMWfRNkXI4RHGA+cUSvRnFUwe,iv:N9ld70CEjELwAdRImh3y58lF2B6U7uCVGBwLY9v9eBY=,tag:jzn8A+9nA4HNCl6GKRbOlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROUV3WHdMT0ZRWjdTSGVD
            M0FWODNHVHcwS3hHbWRIRUtPK2h4Y2ZzVnhvCkxnVytTL1ZqNFI5QUJBQkxXUTZW
            dkE2MUdnWVl3cHorU25OS3B4czdTbWMKLS0tIHNGdmhUN01Cd210ZkZOTTE2VTRK
            azhZSEt1VElpY1NEb0d0SlVKTTMzckUKD8UfTGeVMeyUS52ZgIMg/BoDO42yA8BK
            A1/yMG78BlpMtYBoPVwrijRIIhcb9A64EGN7VjV1lVuTanr8omOWjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-24T03:49:15Z"
    mac: ENC[AES256_GCM,data:2MLFerjOANzMVc2dsF7JXFuv1ziKCh6zmw9+o+K2n1MeCe0Y888HkjSpyJXwQTtGXG+7TjIJ/2zrxQ34Ec99tLmLk96Ln5nvUjshnCIb6hgWGouaj7xKRzVZ66pksbi0KrIOtOYR/4/NjkMlbfh1Y6Iytb3Thkbes+ArkbN8gjo=,iv:O298SiTMM/RBfORKRGGItQnk8cpwng2JdSQYwSAAZMk=,tag:hCC0BOEKguxfcTN+Odjncg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
