apiVersion: v1
kind: Secret
metadata:
    name: github-ssh-secret
    namespace: my-website
type: kubernetes.io/ssh-auth
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:fU0DzDLFOw99iIC/bKfJVq8tO40MLJYBJzCT55B5VBCNwKh5iQULPBkzNLntbz9r2daBhpydWlhYL79t8Drq7TKYKmgDwWQjniuDHAEpqOmgPQhT/h7aFH7799sHsjV7HdMMnb1lUqy9WcvQl5JriPesK7jg7GLkZ15BD0qnnriyhMzetruIAn7N8Ume9SAZwNEskWY8IyACQyShebc7HHuZGvUPMHwKISmo7185qsGw9Aiet4GEjg324SkIj3reSaeS9AsHepP2PFkTdtwVHW07Z+beFzCXxX34N5uYbNDTziqN2sEExaRwR/z3XFsK0Tk2C+ZZwcwgtrvR807JvlExllMOsvgZ6jNRtmgEwDj35MUjuU2hykN/B+8i7JN4KagJIebTbWLlKvI3NLwSXJfhg7dNQseyuMYsRsShrW9wlh1KGNd/fXyo2nTXSaeOEz4zt4PQ2MehWDy4aR0wuCILtjTZFKx+TNfFKPQIF+2+y3xJ0s2+bHasK05mXs/ybqY7NDpX+oTmEnTWdnW67Yzve7Dt9riyyNac72V8xtXBqimd,iv:Os7fvJUEguWrI2ESfaMBvCJfNWyZOCITFS3qTbKD684=,tag:Ib8v4IPvhz7dnHUJhCM3Jw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eS9DcDlsYlIxQldGUWFy
            RGF2Ym9zVUN4Z1A5MisrVjZxTWQ0UTVNRGd3CmNOOUZDMDJ0NnhqL25peWd3WTg5
            a2huOE5Bb1dzNjRKcUhZblZOaUtMd2MKLS0tIHIwY3FPY09QU09DSXQ4LzZjb3Er
            Z1ZVRWxiWmxZcjJ6eVJobUwveVYyakUKCMwFLtS/4pMsdqsL9x+HZnnFIR6sWOXk
            eLjKORRtnUqV8wPDTkEES6ygJ/xiQ/LuCisN4z6e3LQ7NYfxQHyZEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T10:20:47Z"
    mac: ENC[AES256_GCM,data:wZxDtvQO5FvuRIeXc78mTlbWlLU1YYknbhzq/z/zCnjvHrdw/wnPVtUf5X6LPmO9hw8ktpC+wwgpuFqG2rUILKBhJBPCRfkYcusMcf+Bm2hJKIrztsdaAMwWKdNH/gqYl93abJNMntMjyzrsZk1c8ROq8AexN18MnPsv4SlPjRI=,iv:jwX7rgWepWPNrgxKztC4R99l5W+gzpdigSE6aLK5x04=,tag:5k6VP4CifUMlPHV7yda6RQ==,type:str]
    version: 3.13.2
