apiVersion: v1
kind: Secret
metadata:
    name: harbor-pull-secret
    namespace: my-website
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:30Da8Kp9/8QYfQvh8plNAw+4sHXTjna6XHyZfZ/Inam1jccirobWJoQJpxL4p1M7JM7PmhMK6SpSyRDsGT48YNiTsF9cLR1mEdq2dRdHTJVwHG48axOmcGBCGJsQ0in7P6ubDgTBjyGQ8zog0iJTaAKx60FH9Yh+ld7zRA6felJi5uq4GpO5lV1zANvZhfeXAZvBlxIEctFE0VLb6EwVxpviVgX60jDp5eAE35NsnzyiLf6oS/Pnqhdip11Fv+2WuguO4xDYRKI=,iv:eIF3ZguGERlQIb7CrKEFQu5jsh6y90qwwIoQ8BXccBk=,tag:xJWBKEM/f2CV30HQg4v9fQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cWVxTkhlSnJzVnYya1ha
            RnluVHJ3bVhtay9MY2p0eFhTWUc0eWx6dnprCk05ZW03d3c1azdqaGhvV3dmSlFH
            S25KWDZiUFd0ZWU2N3g4cU54UVpGNkEKLS0tIDd4TVU5ai9aU0JhTnl3d3dwU3M2
            V3RYdE00bDduZXgyd011YWUwL0h4aWsKpSZRDgdll6oHKL/QqK40lO4jYHYeS/ja
            +v/ChTGLPIZzPvIkLIYoyA/iMp88UBzY/shRvXdTJQ/HtWnGUREvvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:52:28Z"
    mac: ENC[AES256_GCM,data:sS+/TWw9J61H55AzW7H2qGFvxRwTH02GTSlUEh5vm4QE4kDzCq12T3VKLLyhrC++3CbidqPP8OSjqaL/fbIKigJcPw8rLMzV/SgPHAMgx0piGipnltRlf11GFU7wu89J68EUKaAUozCWU/qbQZcUptnQD8iY63MNkLFmNT3jpN0=,iv:RExmzRZKJI0MCXBxnsRhlkiM203cjfRklY8er0xeWbI=,tag:1r+5HOaqOZ3r2LT6CLNEHg==,type:str]
    version: 3.13.2
