apiVersion: v1
kind: Secret
metadata:
    name: harbor-pull-secret
    namespace: my-website
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:CL2VHA6i+DwIIsg5MZsUS7QWOXTqSMmQzcgxeog1SdlBdHwRo5m0UGBxGF5tJf7EEDQSdgF6gt8ucNx1Oas27dd+wXa9fDXtSBK3DI5tHZ6mxn1I4voNtRrb5ChpK9oofTglyzV3srdQ851emNgen9jiH4yQCqEmDAyB89P1JxJuEEayVdLRJhaRUosoMc5GcpN0V9zwf9ap23BRkHSSPSlA5cdrwTNkm8ekrR0OrybS6QdngeHGIYYGNeJV/c9XCub+Kjvn5uw=,iv:g+vHoV0uX1V6sl2sPbysb15J5Odo0vpRx6Jriys6HCo=,tag:a8JU0+kjmBda/92SOxk9LA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWTN0YUZLbU9MUzZVWWN3
            Wjc0S1dDZXlvQ1BCZStmdDFZWERZNnI3Z21jCmo2aVViV3IxaUNHc3hHbUJ1UHdK
            dy9FZE5VY2ZCcEFDUGhySDlTYzF4MlUKLS0tIFROUkx3NDNoWkErK09HZVNlVXpk
            RHlQWGVaUCtvVW9LajBnZjg2K3doZG8KhPvN/JIJntuenL8faVjX2wG3ixpQfFbk
            yFUJEqKdVv+thdxDKBvj/QJy78+KGEwFXPePxw/ugs1YXPJlhKdFSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:41:04Z"
    mac: ENC[AES256_GCM,data:Kww29elfyMqf87PIKyofYg/WdmPudZFdilxvRbGaOaT1NFjKy4frAh5zrfO97PPz160ub+9ZJVV6IhjqVGXATZcrb7/gq4lhjcXeGfoaZ+F0QIBIQez1hOPJJ96B2D4eeOr1sTEtNDr7Hbt4OBAHYkMFGgu2w+PldyIvjFwFoaI=,iv:aLjknqC/ykUBvL43MZJdvgMsKgH8fPXeSXd7wrDLFUs=,tag:fY57jXYsdFK8+rCgvpl6cQ==,type:str]
    version: 3.13.2
