apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-tekton-pipelines
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/tekton-pipelines
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system