apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
patches:
  - path: patch-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: coredns
      namespace: kube-system
  - path: patch-service.yaml
    target:
      version: v1
      kind: Service
      name: kube-dns
      namespace: kube-system
patches:
  - path: patch-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: coredns
      namespace: kube-system
  - path: patch-service.yaml
    target:
      version: v1
      kind: Service
      name: kube-dns
      namespace: kube-system
