[package]
name = "off-chain-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "icp-off-chain-agent"
path = "src/main.rs"

[[bin]]
name = "generate_jwt"
path = "src/bin/generate_jwt.rs"

[[bin]]
name = "backfill_video_counts"
path = "src/bin/backfill_video_counts.rs"

[dependencies]
anyhow = { workspace = true }
async-channel = { workspace = true }
aws-config = { workspace = true, features = ["behavior-version-latest"] }
aws-sdk-s3 = { workspace = true, features = ["behavior-version-latest"] }
axum = { workspace = true, features = ["json", "macros"] }
base64 = { workspace = true }
bb8 = { workspace = true }
bb8-redis = { workspace = true }
candid = { workspace = true }
canisters-client = { workspace = true, features = ["full"] }
chrono = { workspace = true, features = ["serde"] }
chrono-tz = { workspace = true }
config = { workspace = true, features = ["toml"] }
futures = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
ic-agent = { workspace = true, features = ["pem"] }
ic-utils = { workspace = true }
image = { workspace = true }
jsonwebtoken = { workspace = true, features = ["use_pem"] }
k256 = { workspace = true, features = ["jwk"] }
log = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
redis = {
  workspace = true,
  features = [
    "acl",
    "aio",
    "cluster",
    "cluster-async",
    "json",
    "sentinel",
    "tls-rustls-webpki-roots",
    "tokio-rustls-comp",
  ]
}
regex = { workspace = true }
reqwest = {
  workspace = true,
  default-features = false,
  features = [
    "json",
    "multipart",
    "rustls",
    "stream",
  ]
}
rustls = { workspace = true, features = ["ring"] }
serde = { workspace = true, features = ["derive"] }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
storj-interface = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["cors", "limit"] }
tracing = { workspace = true }
tracing-futures = { workspace = true }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
urlencoding = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
uuid = { workspace = true, features = ["fast-rng", "v4"] }
yral-canisters-common = { workspace = true }
yral-metadata-client = {
  workspace = true,
  features = [
    "rustls-tls",
  ]
}
yral-metadata-types = { workspace = true }
yral-metrics = { workspace = true }
types = { workspace = true }
username-gen = { workspace = true }

[features]
prod-bin = []
