apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - google-chat-webhook.sops.yaml
  - receiver.yaml
  - alert.yaml
  - httproute.yaml
  - networkpolicy.yaml
