apiVersion: ENC[AES256_GCM,data:VVQ=,iv:R4HagKigHqUNlEBK9s3wW2aeCmLsQKRH0xpp95BNU+s=,tag:CGPmlFa4MaVcs4TYncZHtA==,type:str]
kind: ENC[AES256_GCM,data:AY7PhHKS,iv:wgpxinPcyxVnMApyRrCSYPmkJgXuWh/qHn5uYFv+2Qc=,tag:BM9PDNIK0oXIv7albVcHhg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xkKSyMy7ggfiCR3e7Q==,iv:8Ck2/+I/T0irfTUYwLGfnYjtxFsuWBvbV3nfbOmX0Z4=,tag:Rap9lhfZVnGm9ELYKQCZwg==,type:str]
    namespace: ENC[AES256_GCM,data:IA4mBW+4tqCJUpw=,iv:sIPOb1tF4jttrNzprhas+3BWVSdmX7zSr5DXoUl6ACA=,tag:K7tlcsF8pJo9TsxF7oo53A==,type:str]
type: ENC[AES256_GCM,data:JV3H7S2K,iv:+Tnc2nLENui3f19nQf3hfwm6DYg3H57X6t+bivd9b80=,tag:U1Iz706EHvMWdPlHvK4xLA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:QrLmT+o/MYfLWf3fuqC3vkXkhN1nYP20WhlZTD4BfNZo11++IyxuPprmwvRzrfoIKN+cyfoCDE05XbnZYHR8hw==,iv:dn8M1Z3cuopFzp1clq3L2lflMxLgjpyplNsEEdTC0uc=,tag:+fZu0mDqWGmIdJkTwIihrA==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONUp2b2dJZ1FSVE9HczRB
            dXpCdWIwTjNqdEVYTzdlRURYN2hpcHpoYUVVCmQxY0VFdFc3YkdQWFFhcitYd1Jt
            REVsK2RZUzF0MThnZDZHRTdUdmJBek0KLS0tIEdDeHUrQ2UrbFRyeis1N2cxOU1o
            aDNtRnJVeHJlcDVFNGdBL295Y0g1ODAKQkVzUKCE29WejKcIngI6JJPYjdKzPWP3
            8sh88vBUDRC/35M8pfzoHHb5ki/1Knib/njQ1TQ2v/+/knmKGORfig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T14:59:17Z"
    mac: ENC[AES256_GCM,data:QiXtEgoxK1GYd6m2YA80ArM18GUHd6a5G2/vYwIxypvBQxjGVLtIl1UZ3dN/okBnvQqsBnCtUSZV4rQrcSSiM5dA8fZXZGtm7tLeOUsCE1lK/TO8rMBs605bVsqpvyCuGtCatlNP9dN+2DQ2CMR660zleBl7g4JPwdro8GrPIJE=,iv:Eeph7sS3uC39wtLRu0jjNe9bAwRrj93hkEwDQsoEy1w=,tag:rg6lM5ojv5HWDCdVKLexrg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
