apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: timer-counter
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: timer-counter
  filterTags:
    pattern: '^[0-9]{14}-[a-f0-9]+'
    extract: '$0'
  policy:
    alphabetical:
      order: asc
