[package]
name = "component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
auth = { path = "../auth" }
axum = { workspace = true, features = ["macros"], optional = true }
axum-extra = {
  workspace = true,
  features = [
    "cookie",
    "cookie-private",
    "cookie-signed",
    "typed-header",
  ],
  optional = true
}
chrono = "0.4"
codee = { workspace = true, features = ["json_serde"] }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
consts = { path = "../consts" }
dotenv = { workspace = true, optional = true }
enum_dispatch = { workspace = true, optional = true }
futures = { workspace = true }
gloo = { workspace = true, features = ["futures", "net"] }
gob-cloudflare = { workspace = true, optional = true }
hex = { workspace = true }
http = { workspace = true }
icondata = { workspace = true }
icondata_core = { workspace = true }
identity = { workspace = true, features = ["wasm-bindgen"] }
js-sys = { workspace = true }
jsonwebtoken = { workspace = true, optional = true }
leptos = { workspace = true, features = ["nightly"] }
leptos_axum = { workspace = true, optional = true }
leptos_icons = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true, features = ["nightly"] }
leptos-use = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
openidconnect = { workspace = true, optional = true }
rand_chacha = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
reqwest = { workspace = true, features = ["http2", "json", "multipart"] }
send_wrapper = { workspace = true, features = ["futures"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
simple_logger = { workspace = true }
speedate = { workspace = true, optional = true }
state = { path = "../state" }
thiserror = { workspace = true }
tokio = {
  workspace = true,
  features = ["rt-multi-thread", "signal", "time"],
  optional = true
}
tower = { workspace = true, features = ["full"], optional = true }
tower-http = { workspace = true, features = ["cors", "fs"], optional = true }
tracing = { workspace = true, optional = true }
types = { workspace = true }
urlencoding = { workspace = true }
utils = { path = "../utils" }
uts2ts = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = {
  workspace = true,
  features = [
    "Clipboard",
    "Document",
    "Navigator",
    "ShareData",
    "ValidityState",
    "Window",
    "Worker",
    "XmlHttpRequest",
    "XmlHttpRequestUpload",
  ],
  optional = true
}
web-time.workspace = true
yral-database-spacetime-bindings = { workspace = true, optional = true }

[features]
backend-admin = [
  "consts/backend-admin",
  "state/backend-admin",
  "utils/backend-admin",
]
cloudflare = [
  "consts/cloudflare",
  "dep:gob-cloudflare",
  "state/cloudflare",
  "utils/cloudflare",
]
hydrate = [
  "consts/hydrate",
  "dep:rand_chacha",
  "dep:web-sys",
  "leptos/hydrate",
  "send_wrapper/futures",
  "speedate",
  "state/hydrate",
  "utils/hydrate",
]
oauth-hydrate = [
  "consts/oauth-hydrate",
  "state/oauth-hydrate",
  "utils/oauth-hydrate",
]
oauth-ssr = [
  "auth/oauth-ssr",
  "consts/oauth-ssr",
  "dep:openidconnect",
  "state/oauth-ssr",
  "utils/oauth-ssr",
]
redis-kv = ["consts/redis-kv", "state/redis-kv", "utils/redis-kv"]
release-bin = [
  "backend-admin",
  "cloudflare",
  "consts/release-bin",
  "gob-cloudflare/rustls-tls",
  "oauth-ssr",
  "ssr",
  "state/release-bin",
  "utils/release-bin",
]
release-lib = [
  "backend-admin",
  "cloudflare",
  "consts/release-lib",
  "dep:openidconnect",
  "hydrate",
  "oauth-hydrate",
  "state/release-lib",
  "utils/release-lib",
]
ssr = [
  "auth/ssr",
  "axum-extra",
  "consts/ssr",
  "dep:axum",
  "dep:dotenv",
  "dep:enum_dispatch",
  "dep:jsonwebtoken",
  "dep:leptos_axum",
  "dep:rand_chacha",
  "dep:regex",
  "dep:tokio",
  "dep:tower",
  "dep:tower-http",
  "dep:tracing",
  "dep:yral-database-spacetime-bindings",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "leptos-use/axum",
  "leptos-use/ssr",
  "leptos/ssr",
  "reqwest/rustls",
  "speedate",
  "state/ssr",
  "utils/ssr",
]
