apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-contact-point
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  contact-point.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: google-chat
        receivers:
          - uid: google-chat-receiver
            type: googlechat
            settings:
              url: $GOOGLE_CHAT_WEBHOOK_URL
            disableResolveMessage: false
