apiVersion: ENC[AES256_GCM,data:SzA=,iv:4yhhTvQ2DZTQTOGjCt0huYlQ3SB95u54U8P7zHF269A=,tag:ZuFchq5mt7Zi5WQXRl88OQ==,type:str]
kind: ENC[AES256_GCM,data:ev2iHr3F,iv:gD4fSAkAOwHv7IponNeQ6nMRxRcMaZ1PMaNNqEgrIVU=,tag:cjCPh5hoG7LQZj/4qKdEXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bkXJZvE45B/4DcTgOfrNveU90S7E22BGXxvWSNE/,iv:0POtpjN2g0fGo6pRjqyP80xK0hE23pMCngb6NArqvIU=,tag:ZWoIhbzCFRLeQdIvO7Nfgw==,type:str]
    namespace: ENC[AES256_GCM,data:H4TLfYuZQZAuDg==,iv:jiPOfVINRcaaVXD3QbEQ/UYmIQVGaK4bakdZbu1hnAM=,tag:0I+/WrSWWAZ00CwP7YIMUA==,type:str]
type: ENC[AES256_GCM,data:ONTwDPl5,iv:uXrApHyYb2z0uz5fK3TXxwqNzZKhcRE55MpHFXKiBWk=,tag:nvNBLtmtwmN2SKTRO8fAOw==,type:str]
stringData:
    GOOGLE_CHAT_WEBHOOK_URL: ENC[AES256_GCM,data:XNeLcasFeTo3CnlHFDi2hQiizQQh7CBce1iTgGffQzYcEdLdZ9nIuXXIuCXoqi7s4R6xfvnKmKgxNXJYwimJDdBwMXTBnpov52K0vzseUnFffcNdQOsMajhCWYSbneYCu2cOh+V1sw5ZrNf0coNWeatLDLTVGVOmTLK8+w5RDlKL1oopcq4PHHDaD7y3XxtWucGaAgnAeg4=,iv:dnw+rJm1HMTNhJ/1jOpKdx7VWEAFdAuMR1aSuBo/Jqc=,tag:eoKOYE0z6irj5TzqoRU0Lw==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaENCZ29KQXV6dU5uaTNE
            c0dLY3g2N0t1Tm42c1NUczFCREpXUDIra0drCmdPZWxMcVppTlAwaGJHQXNSWkVZ
            WWJrN1hvN3RnOGp6bEJreDh2R2w2Uk0KLS0tIHhMUWJ4eW4rcTIzL1JwbG5EQzNq
            eWJOV2JQWnN3R3R5QU9JUGlkODNvQVUK9giUCZSEC+693QWOLHsXPOr1NF/hX/SK
            fzR3qxSXWNcD0OZir75Wf5k6WvmzZp3TwiYyK3AUKTn8nWCAKtR/+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T10:21:40Z"
    mac: ENC[AES256_GCM,data:+PO8KYx79ZycApiqZD8mSH3sYF+v7IpjaEEe+F42etse1Cy8XiUk1Pgnteo9hZi92yUePtr6XIdqb8qtAEso/sUPn+WLiByZePDR3G4yra+tW1iX5hUtdFX9hACnGEz1gOKe1ZkjYTmoFQ29EhxA/zpHXutdMOFIvg0jdqsA47g=,iv:9j2MLtrooCsy0UCI8xGcrdb3IIw9M2EfSSHvhluAQ8c=,tag:r+Rj+D8LDdIgbUSSTKPeNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
