apiVersion: ENC[AES256_GCM,data:m/k=,iv:70lZdMzHujegsXQpILos/wGKfnTNQFkC+yoTl0C+d7U=,tag:5AXF+Oi2BNlsAh832KauJQ==,type:str]
kind: ENC[AES256_GCM,data:bbn22q2V,iv:5Hhei8UWnjjnxmiGxh2asUDV7ChOZ5uTq/bZnbqsGrg=,tag:L8QVhm+oG7Nt3x2iL5lEhQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cRNOgTbXsyeF/8lzf8ErzxeyPtQyksIsItVOFIzx,iv:XoWo2Te15hpN+TnWohVavsELzuwFdqd9Cxp5IPy60l0=,tag:gNyPQc2YGUb2TMTSfnvI4Q==,type:str]
    namespace: ENC[AES256_GCM,data:ZVcmts9jLcWYcA==,iv:M1/ZQiple0gTlM6vfyOa+JS8FeaNt24c2uTtnfpTxXU=,tag:zIjSagW4O1rUfLpke3Qb6w==,type:str]
type: ENC[AES256_GCM,data:4T6ZzNhe,iv:cOCr2heJM6s7ZkVeWYXqfpDBUQcsCcyn9Q2tmwUho7w=,tag:kwDr8KG/K/REFk1CNpoK+g==,type:str]
stringData:
    GOOGLE_CHAT_WEBHOOK_URL: ENC[AES256_GCM,data:LNXrad9wscjO47b2gCUoUpzmaIc7MLAM7oLhPT3xyCgiAEnZPuqKKUD6UF0h9DpCNXzT/yzxWexHm3t2rK8FSa5GXwxcE6VRSsNlK1pnfNgNetnashW7ofmHbwHqgY7UcNomde6nxSYxbxh+IrEzzgU4W89fKKewL14chW9LDwLRTx01RQNO21elSWNV4Azuha7UEacf2kY=,iv:So5FNrd50g+5Q+kfhzC6lO9aJbKSJhclJ0arflMzbCE=,tag:RKphRy/GKS+6wTKZjtvm7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNGNxQXNFUWxDRko1M2pr
            M3k2Q1NyNTZmMzFhYWRvSTI5cXFyaVZ2b3lrCm1aODBLbDdwYXFLUkpzZWxmTXF5
            UmpwS0xBdFRJc3FtdkdCTCt6eEprWGsKLS0tIFNydWFUTnVpVDZvQVBha2Y0V0tr
            a2RJVzdhekUzSW4xc0p4ZEhHL1FnMWcKrv+kMEO5xdRJYH26BrNZTWM2SojJCemS
            kTPXDJywbmpU1UQWY/Bw4lH14WDXJxe15nMfIav2HG5Smt9/1f/gnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-24T07:51:33Z"
    mac: ENC[AES256_GCM,data:J2ywEtZpGfnI/t6FaeCs2fAj6SWiH+zCPe8ZE62EgNjJPhY6CxEj6oLfU3cqyHcO6/rJ514FgIVCOc86RgiBX3oViUQHFmIradsthJmHzFi+C4B7Bimq7XNfxQ9X64Sx3lZgDG1SWqTqNG+OJYVxV5XwSzKSTtyw8ox6p5iBpw0=,iv:Ik7vKzywfVbn+hUl7V6fHseF51rzTlazYIsXlTL7OFY=,tag:7rUmyLkc6azo6FR57niAFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
