apiVersion: ENC[AES256_GCM,data:OMI=,iv:INSE3HRdCWWuMoKJIm+unC/PFX6UZVDcOQV0dsvnOsA=,tag:jtCE5NBaHTLXMKvjekbYQg==,type:str]
kind: ENC[AES256_GCM,data:QeknKGIf,iv:qPxZqhTT4312B1rM1aAFFrQ6ONORGdEh5kdmzmfYsUM=,tag:DfWujKINs1eR6p0SAuwvMA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:it5dw5mqTnCfHZAlLLamxQGHgSHM+LbXx6HaqhR9,iv:DxvLpG6zqJRAt62NQxJV9V4dSl3zV0XLqB6UJuaazVo=,tag:sF575qSSELdXbpIxpqCDqQ==,type:str]
    namespace: ENC[AES256_GCM,data:JvCMEJWPCYgyWQ==,iv:aay+69gto4EQ3fkZ709osWtfUYup43DrXUoOKogBRXo=,tag:DLHjjCZ3dmClV6NgZcciRg==,type:str]
type: ENC[AES256_GCM,data:UmYLOaky,iv:IkMkdRL0C1qYpkfwjULP18LZWO8X8g89wbcJOpoD4Fo=,tag:43g7Vg+TVZMn6I+gyJCxyQ==,type:str]
stringData:
    GOOGLE_CHAT_WEBHOOK_URL: ENC[AES256_GCM,data:RZrWW3S6oavirfYlncRdW/Tb2PJe8qeBT1VCqHgW59UPlOQIXaZ9s1acLLVFtBZGOzSZ6yF8KY9qTPumB/El6e+xBxTfM+9N1u3JQHRvQf3yqWncn9NHgg0bRCMrbhw+EEv9yxtI3FNW13VPXkzNOcyzE/slWViuwiWKIvezq1UvmQF5qOD21GCPvqKijL1gvEAh8T/PcUE=,iv:DvaG5Mme1k/APOlOgz2Odeo7wdD1G+xROWORxxt1ssI=,tag:EF9ChJuyo/MTzPsGJGavMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcVA2WkVpVGkydTdHbHRF
            d2ZWMEw5RG5XQmxpb2JONXVEeWs4YVYzNlJZCmRqcUhIMERCL0lXWGc3SkNabU1m
            R2dvUEc0RFRoN25GZjJsTUZubm0rcEkKLS0tIGQvUjhFTWtvaXRVNmRiSm10c0NN
            aDdnbGxSSW1mSUoxdXZJekN2OEsvcTgKLXrYwO/M93tq4L8PuSHgbCdDg9muiCn5
            N/RuoNombjG/1HE+Idz9+9YpkdDHFTWM3kuXWBSAONMLdxjX1R85Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-20T08:03:32Z"
    mac: ENC[AES256_GCM,data:uHlFnMVSwN3P97n06Y3Fk2Ft0tq739tNzC1YndL11u5ffCh/pRcqNCEqHOUFTw748laU9pLKQv+/aAxB+m6/82hD8qIn9i0zNAmQ3VZ7QxtKOg4oNKyzmZL7rD3wcxrfwDx3MpeRLu2XdI8QIYLRYPDWh+hxZRkLOHCKRcvDyn4=,iv:EoceeElMbwbkDEy7hh2QJ8HLDT3LeEt8KE5fuDhTzgE=,tag:Gv8QBhEb9RaFVfSTtxeaEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
