apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbx-data
  namespace: dbx
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi