apiVersion: ENC[AES256_GCM,data:EwY=,iv:K7yN75XJai6ALkAN5KzX90o9gBSuqOG9GLX6bDGaT5M=,tag:q2eoHWKCi1NE2ITT0EK8+Q==,type:str]
kind: ENC[AES256_GCM,data:EEr8BWRJ,iv:2q0gRf59ISctUEza7IEe1No8o/tZgmUa5jOWGD129Bs=,tag:1PdMjqWgBQmsAqrFBYsOYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zts9tJpxDmlw77Qi6QqqTmV+,iv:zWoarNjWxR0yHk2/qUgJVJ/A+2Ya9x9b5bztKx365Ts=,tag:wp281pyojA03v6BKVEf/4Q==,type:str]
    namespace: ENC[AES256_GCM,data:ncVw,iv:j9fHD3Xnm2ZLC4m2Mb323Pk4VscgsYBSOOKFlqKSSew=,tag:GO7F8JGmFu6XYRc+vClQMg==,type:str]
type: ENC[AES256_GCM,data:z+ROgZHR,iv:EH0994ZcxIUSaPnO8aQe2LDDqAt2Cey385Nc5qNZxsA=,tag:LRhfQR0iOdxNQiCxo+VMqg==,type:str]
stringData:
    BYTEBASE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:/pXAGbN+nizc69dcZ8UNwCrn,iv:aNYEP4+DQg2LYpmlHTOxcjiV4ws7cxLjwR17waT0Iyo=,tag:nlPIDOFbED6NT+IYh3awbA==,type:str]
    KAFKA_SASL_PASSWORD: ENC[AES256_GCM,data:hzBTtQsxXp061J7ChaM2Uef6cydRrFdAu1o3Ph8mytjLyXs0QjISbjj75g==,iv:c/NZ8kTZW198NQ2E+fGd4x+9HE4VHj2Hd7SRRqrl/EY=,tag:6Jb3yKYkfO8KlsU5jrQD0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MTV2Wm1kYk11NTJ2blU5
            Ym82VGdZVWc5SEttMWNRMm9td0tOWXRZblQ0CjBEWFZMYjFGMk9qRnNVMkNDTDAz
            RXJQSHJKS1NOUzQ3R3daNjNsSHc4NkkKLS0tIE9NYmE1N3ZFVzZNUmYyRnZSYllL
            UjkyaktOSmVncHU3VFFVczJucCtvSkUKpgUO/34WCNLalilCqv+SvhaMpbyaGZJN
            ejfDhQMaQtiW4Bvszbf7kzhKjxoK0gk72KNEj3dzDn0NiFSH2F+evg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-04T03:33:47Z"
    mac: ENC[AES256_GCM,data:3jvI55CmXGaBd7fLeoinqQRdEwWy5xdZRQaNPC939F22obY+l6mblyg86QQrqUFNOZkq+T8s3cbOru/5/WsQbtUGlyGO4IUct4TAjcfzvyH1meQCXTOTI7SASoxzG9/NAMZ+4GevqCRGU/BOgfWl/JkHEwhXSopnPdWwad2CAjY=,iv:/yLLYMrWzGkUVDdEcba3YSMC4iO13BexPQV96wFCTPk=,tag:1bUrClUhH89k5SGXQ7oMFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
