apiVersion: ENC[AES256_GCM,data:T94=,iv:sbIXHDKJahsm4g0kks505RQD436uw0ZuCS6XR3V7qCw=,tag:1kmgbNUqRWJZyuy6nuMfaw==,type:str]
kind: ENC[AES256_GCM,data:2mWqwhqf,iv:W5kOUAyr3G7a1qNv99z5b2mfVA2lcImpJtvgMAyQ7JE=,tag:Qhpis2uRnzIs3EVYGXYyxw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cZSQtooXzl0hHZcGyq3RxhkK,iv:BXNcdX1ZameSjGKddh2Kt692g5dBJm3ktRREAcLDP2I=,tag:LPUoTm3Zb3KP8SFFtPPQdA==,type:str]
    namespace: ENC[AES256_GCM,data:MCGL,iv:RCCLtTdqFiF/22RgO9MJeRTm1oQXRWHugOTLI1oN7d0=,tag:YSu2vjE+vCnXCjULP7nYbQ==,type:str]
type: ENC[AES256_GCM,data:fTJwfm2K,iv:wxf8vVTh2YzXGD1Gf2XxB9FN/1bZtSV3TwNqd3fULbs=,tag:9IJysJmAPCKOARtXmwdA/A==,type:str]
stringData:
    KAFKA_SASL_PASSWORD: ENC[AES256_GCM,data:BUWOhGqp0oc6Mnjs8LbtLmW06twL1z9ojKTGvOM8wqf8kOd0gdj2xYC6Eg==,iv:P1lTliEVFMAkTHp5nxU1c4ZvBbyL9WWHYw5HYCWW5kE=,tag:5LkAdElepSUewGKhDPCvJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNHNvb3ZMd0dodGVLL2lL
            LzkrQ2lpZHpsdUtzeU9hVGhMZ2dJV3hqbTJnCldDS2U4U3dEYVMyRnFBVFU3Mm92
            QjR1d1pPQlEvc0szdjgxM2NwWWlVN00KLS0tIEFyMDRBK3pKd2lhZjJUK1haVGlt
            UHhSYitrUWZGaWJwRGVqdktNK1d5eEUKEShGFkZhHgdtbo8ZS6hI1tkgbUlVAYCs
            Sqd9pddrJi1ias0ouo/evPnuSYG0NipzyIVJZeDmxoikq5fxGvpfXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-04T13:15:14Z"
    mac: ENC[AES256_GCM,data:CWCYGV+eBH1ChDbl1nnX87ip6tZ9NKztEOdkeWiSWgy7CknuQt2NH6Dqx5HMTCFTn44ofWfG/ri/arNII9l7M1ybGNvx3J3G5y6jvFRW4235qIrbkpn7oAXoNdOjupjEQdzgt66W4riEs/KoDV+FGbp/D5d+/jVc63D9Stse2RI=,iv:PH/aGxDfpYfpmtt2zq40xhkxENffNRMnuGCafcOtfoE=,tag:1qJkso5vYlriWYZa/3aoLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
