[package]
name = "yral-canisters-common"
version = "0.1.0"
edition = "2021"

[dependencies]
candid.workspace = true
canisters-client = { workspace = true, features = ["full"] }
global-constants.workspace = true
hon-worker-common = { workspace = true, features = ["client"] }
ic-agent.workspace = true
identity = {
  workspace = true,
  default-features = false,
  features = [
    "ic-agent",
  ]
}
pump-n-dump-common = { workspace = true }
url = { workspace = true, features = ["serde"] }
username-gen.workspace = true

yral-metadata-client = {
  path = "../../yral-metadata/client",
  default-features = false
}
yral-metadata-types = {
  path = "../../yral-metadata/types",
  default-features = false
}

async-trait = { workspace = true }
ciborium = "0.2.2"
crc32fast = "1.4.0"
enum_dispatch = { workspace = true }
futures-util.workspace = true
getrandom = "0.2.15"
k256 = { workspace = true, default-features = false }
log.workspace = true
num-bigint = { workspace = true }
once_cell = "1.21.3"
reqwest = {
  version = "0.12",
  default-features = false,
  features = [
    "http2",
    "json",
  ]
}
rust_decimal = "1.36.0"
send_wrapper = { version = "0.6.0", features = ["futures"], optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
sns-validation.path = "../sns-validation"
thiserror.workspace = true
tracing = "0.1.41"
types.workspace = true
web-time.workspace = true

[features]
default = ["rustls-tls"]
js = ["dep:send_wrapper", "getrandom/js", "ic-agent/wasm-bindgen"]
local = []
rustls-tls = ["reqwest/rustls-tls", "yral-metadata-client/rustls-tls"]
