// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::subscription_plan_type::SubscriptionPlan;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ChangeSubscriptionPlanArgs {
    pub principal_text: String,
    pub plan: SubscriptionPlan,
}

impl From<ChangeSubscriptionPlanArgs> for super::Reducer {
    fn from(args: ChangeSubscriptionPlanArgs) -> Self {
        Self::ChangeSubscriptionPlan {
            principal_text: args.principal_text,
            plan: args.plan,
        }
    }
}

impl __sdk::InModule for ChangeSubscriptionPlanArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `change_subscription_plan`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait change_subscription_plan {
    /// Request that the remote module invoke the reducer `change_subscription_plan` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`change_subscription_plan:change_subscription_plan_then`] to run a callback after the reducer completes.
    fn change_subscription_plan(
        &self,
        principal_text: String,
        plan: SubscriptionPlan,
    ) -> __sdk::Result<()> {
        self.change_subscription_plan_then(principal_text, plan, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `change_subscription_plan` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn change_subscription_plan_then(
        &self,
        principal_text: String,
        plan: SubscriptionPlan,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl change_subscription_plan for super::RemoteReducers {
    fn change_subscription_plan_then(
        &self,
        principal_text: String,
        plan: SubscriptionPlan,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ChangeSubscriptionPlanArgs {
                principal_text,
                plan,
            },
            callback,
        )
    }
}
