// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::user_profile_details_v_7_type::UserProfileDetailsV7;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct GetUserProfileByUserIdArgs {
    pub user_id: String,
}

impl __sdk::InModule for GetUserProfileByUserIdArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `get_user_profile_by_user_id`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait get_user_profile_by_user_id {
    fn get_user_profile_by_user_id(&self, user_id: String) {
        self.get_user_profile_by_user_id_then(user_id, |_, _| {});
    }

    fn get_user_profile_by_user_id_then(
        &self,
        user_id: String,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Option<UserProfileDetailsV7>, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl get_user_profile_by_user_id for super::RemoteProcedures {
    fn get_user_profile_by_user_id_then(
        &self,
        user_id: String,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Option<UserProfileDetailsV7>, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Option<UserProfileDetailsV7>>(
                "get_user_profile_by_user_id",
                GetUserProfileByUserIdArgs { user_id },
                __callback,
            );
    }
}
