// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct GetNotificationTokensArgs {
    pub user_id: String,
}

impl __sdk::InModule for GetNotificationTokensArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `get_notification_tokens`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait get_notification_tokens {
    fn get_notification_tokens(&self, user_id: String) {
        self.get_notification_tokens_then(user_id, |_, _| {});
    }

    fn get_notification_tokens_then(
        &self,
        user_id: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Vec<String>, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl get_notification_tokens for super::RemoteProcedures {
    fn get_notification_tokens_then(
        &self,
        user_id: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Vec<String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp.invoke_procedure_with_callback::<_, Vec<String>>(
            "get_notification_tokens",
            GetNotificationTokensArgs { user_id },
            __callback,
        );
    }
}
