// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.1 (commit 052c83fe984a4c4eb7bb4f9afa5c6b1903891d87).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod accept_new_user_registration_v_2_reducer;
pub mod add_post_reducer;
pub mod add_pro_plan_free_video_credits_reducer;
pub mod add_view_details_reducer;
pub mod auth_kv_entry_type;
pub mod change_subscription_plan_reducer;
pub mod delete_post_reducer;
pub mod delete_user_info_reducer;
pub mod fetch_posts_procedure;
pub mod fetch_posts_result_type;
pub mod follow_user_reducer;
pub mod follower_item_type;
pub mod followers_page_type;
pub mod following_item_type;
pub mod following_page_type;
pub mod get_draft_posts_of_user_by_principal_procedure;
pub mod get_draft_posts_of_user_procedure;
pub mod get_followers_procedure;
pub mod get_following_procedure;
pub mod get_individual_post_details_by_id_procedure;
pub mod get_notification_tokens_procedure;
pub mod get_post_by_id_procedure;
pub mod get_posts_of_user_by_principal_procedure;
pub mod get_posts_of_user_procedure;
pub mod get_profile_details_v_4_procedure;
pub mod get_user_profile_by_user_id_procedure;
pub mod get_user_profile_by_username_procedure;
pub mod get_user_profile_details_v_7_procedure;
pub mod get_users_profile_details_procedure;
pub mod kv_delete_reducer;
pub mod kv_get_procedure;
pub mod kv_get_result_type;
pub mod kv_set_reducer;
pub mod link_user_id_reducer;
pub mod nsfw_info_type;
pub mod post_details_for_frontend_type;
pub mod post_list_offset_type;
pub mod post_page_type;
pub mod post_status_type;
pub mod post_type;
pub mod post_v_2_type;
pub mod post_view_details_from_frontend_type;
pub mod posts_table;
pub mod posts_v_2_table;
pub mod profile_picture_data_type;
pub mod register_new_user_reducer;
pub mod register_notification_token_reducer;
pub mod remove_pro_plan_free_video_credits_reducer;
pub mod set_email_reducer;
pub mod set_username_reducer;
pub mod subscription_plan_type;
pub mod unfollow_user_reducer;
pub mod unregister_notification_token_reducer;
pub mod update_post_status_reducer;
pub mod update_profile_ai_influencer_status_reducer;
pub mod update_profile_details_reducer;
pub mod update_profile_details_v_2_reducer;
pub mod update_profile_picture_nsfw_info_reducer;
pub mod update_user_last_access_time_reducer;
pub mod upsert_post_reducer;
pub mod upsert_post_v_2_reducer;
pub mod upsert_posts_batch_reducer;
pub mod upsert_posts_v_2_batch_reducer;
pub mod upsert_user_follow_batch_reducer;
pub mod upsert_user_profile_batch_reducer;
pub mod user_account_type_type;
pub mod user_follow_batch_entry_type;
pub mod user_follow_type;
pub mod user_follows_table;
pub mod user_notification_token_type;
pub mod user_notification_tokens_table;
pub mod user_profile_batch_entry_type;
pub mod user_profile_details_v_4_type;
pub mod user_profile_details_v_7_type;
pub mod user_profile_type;
pub mod user_profiles_table;
pub mod yral_pro_subscription_type;

pub use accept_new_user_registration_v_2_reducer::accept_new_user_registration_v_2;
pub use add_post_reducer::add_post;
pub use add_pro_plan_free_video_credits_reducer::add_pro_plan_free_video_credits;
pub use add_view_details_reducer::add_view_details;
pub use auth_kv_entry_type::AuthKvEntry;
pub use change_subscription_plan_reducer::change_subscription_plan;
pub use delete_post_reducer::delete_post;
pub use delete_user_info_reducer::delete_user_info;
pub use fetch_posts_procedure::fetch_posts;
pub use fetch_posts_result_type::FetchPostsResult;
pub use follow_user_reducer::follow_user;
pub use follower_item_type::FollowerItem;
pub use followers_page_type::FollowersPage;
pub use following_item_type::FollowingItem;
pub use following_page_type::FollowingPage;
pub use get_draft_posts_of_user_by_principal_procedure::get_draft_posts_of_user_by_principal;
pub use get_draft_posts_of_user_procedure::get_draft_posts_of_user;
pub use get_followers_procedure::get_followers;
pub use get_following_procedure::get_following;
pub use get_individual_post_details_by_id_procedure::get_individual_post_details_by_id;
pub use get_notification_tokens_procedure::get_notification_tokens;
pub use get_post_by_id_procedure::get_post_by_id;
pub use get_posts_of_user_by_principal_procedure::get_posts_of_user_by_principal;
pub use get_posts_of_user_procedure::get_posts_of_user;
pub use get_profile_details_v_4_procedure::get_profile_details_v_4;
pub use get_user_profile_by_user_id_procedure::get_user_profile_by_user_id;
pub use get_user_profile_by_username_procedure::get_user_profile_by_username;
pub use get_user_profile_details_v_7_procedure::get_user_profile_details_v_7;
pub use get_users_profile_details_procedure::get_users_profile_details;
pub use kv_delete_reducer::kv_delete;
pub use kv_get_procedure::kv_get;
pub use kv_get_result_type::KvGetResult;
pub use kv_set_reducer::kv_set;
pub use link_user_id_reducer::link_user_id;
pub use nsfw_info_type::NsfwInfo;
pub use post_details_for_frontend_type::PostDetailsForFrontend;
pub use post_list_offset_type::PostListOffset;
pub use post_page_type::PostPage;
pub use post_status_type::PostStatus;
pub use post_type::Post;
pub use post_v_2_type::PostV2;
pub use post_view_details_from_frontend_type::PostViewDetailsFromFrontend;
pub use posts_table::*;
pub use posts_v_2_table::*;
pub use profile_picture_data_type::ProfilePictureData;
pub use register_new_user_reducer::register_new_user;
pub use register_notification_token_reducer::register_notification_token;
pub use remove_pro_plan_free_video_credits_reducer::remove_pro_plan_free_video_credits;
pub use set_email_reducer::set_email;
pub use set_username_reducer::set_username;
pub use subscription_plan_type::SubscriptionPlan;
pub use unfollow_user_reducer::unfollow_user;
pub use unregister_notification_token_reducer::unregister_notification_token;
pub use update_post_status_reducer::update_post_status;
pub use update_profile_ai_influencer_status_reducer::update_profile_ai_influencer_status;
pub use update_profile_details_reducer::update_profile_details;
pub use update_profile_details_v_2_reducer::update_profile_details_v_2;
pub use update_profile_picture_nsfw_info_reducer::update_profile_picture_nsfw_info;
pub use update_user_last_access_time_reducer::update_user_last_access_time;
pub use upsert_post_reducer::upsert_post;
pub use upsert_post_v_2_reducer::upsert_post_v_2;
pub use upsert_posts_batch_reducer::upsert_posts_batch;
pub use upsert_posts_v_2_batch_reducer::upsert_posts_v_2_batch;
pub use upsert_user_follow_batch_reducer::upsert_user_follow_batch;
pub use upsert_user_profile_batch_reducer::upsert_user_profile_batch;
pub use user_account_type_type::UserAccountType;
pub use user_follow_batch_entry_type::UserFollowBatchEntry;
pub use user_follow_type::UserFollow;
pub use user_follows_table::*;
pub use user_notification_token_type::UserNotificationToken;
pub use user_notification_tokens_table::*;
pub use user_profile_batch_entry_type::UserProfileBatchEntry;
pub use user_profile_details_v_4_type::UserProfileDetailsV4;
pub use user_profile_details_v_7_type::UserProfileDetailsV7;
pub use user_profile_type::UserProfile;
pub use user_profiles_table::*;
pub use yral_pro_subscription_type::YralProSubscription;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AcceptNewUserRegistrationV2 {
        new_principal_text: String,
        authenticated: bool,
        main_account_text: Option<String>,
    },
    AddPost {
        id: String,
        description: String,
        hashtags: Vec<String>,
        video_uid: String,
        creator: __sdk::Identity,
        status: PostStatus,
    },
    AddProPlanFreeVideoCredits {
        principal_text: String,
        credits: u32,
    },
    AddViewDetails {
        post_id: String,
        details: PostViewDetailsFromFrontend,
    },
    ChangeSubscriptionPlan {
        principal_text: String,
        plan: SubscriptionPlan,
    },
    DeletePost {
        post_id: String,
    },
    DeleteUserInfo {
        principal_to_delete_text: String,
    },
    FollowUser {
        followee_text: String,
    },
    KvDelete {
        key: String,
    },
    KvSet {
        key: String,
        value: String,
    },
    LinkUserId {
        principal_text: String,
        user_id: String,
    },
    RegisterNewUser,
    RegisterNotificationToken {
        token: String,
    },
    RemoveProPlanFreeVideoCredits {
        principal_text: String,
        credits: u32,
    },
    SetEmail {
        principal_text: String,
        email: String,
    },
    SetUsername {
        principal_text: String,
        username: String,
    },
    UnfollowUser {
        followee_text: String,
    },
    UnregisterNotificationToken {
        token: String,
    },
    UpdatePostStatus {
        post_id: String,
        status: PostStatus,
    },
    UpdateProfileAiInfluencerStatus {
        principal_text: String,
        is_ai_influencer: bool,
    },
    UpdateProfileDetails {
        bio: String,
        website_url: String,
        profile_pic_url: String,
    },
    UpdateProfileDetailsV2 {
        bio: Option<String>,
        website_url: Option<String>,
        profile_picture: Option<ProfilePictureData>,
    },
    UpdateProfilePictureNsfwInfo {
        principal_text: String,
        nsfw_info: NsfwInfo,
    },
    UpdateUserLastAccessTime,
    UpsertPost {
        post: Post,
    },
    UpsertPostV2 {
        post: PostV2,
    },
    UpsertPostsBatch {
        posts: Vec<Post>,
    },
    UpsertPostsV2Batch {
        posts: Vec<PostV2>,
    },
    UpsertUserFollowBatch {
        follows: Vec<UserFollowBatchEntry>,
    },
    UpsertUserProfileBatch {
        profiles: Vec<UserProfileBatchEntry>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AcceptNewUserRegistrationV2 { .. } => "accept_new_user_registration_v_2",
            Reducer::AddPost { .. } => "add_post",
            Reducer::AddProPlanFreeVideoCredits { .. } => "add_pro_plan_free_video_credits",
            Reducer::AddViewDetails { .. } => "add_view_details",
            Reducer::ChangeSubscriptionPlan { .. } => "change_subscription_plan",
            Reducer::DeletePost { .. } => "delete_post",
            Reducer::DeleteUserInfo { .. } => "delete_user_info",
            Reducer::FollowUser { .. } => "follow_user",
            Reducer::KvDelete { .. } => "kv_delete",
            Reducer::KvSet { .. } => "kv_set",
            Reducer::LinkUserId { .. } => "link_user_id",
            Reducer::RegisterNewUser => "register_new_user",
            Reducer::RegisterNotificationToken { .. } => "register_notification_token",
            Reducer::RemoveProPlanFreeVideoCredits { .. } => "remove_pro_plan_free_video_credits",
            Reducer::SetEmail { .. } => "set_email",
            Reducer::SetUsername { .. } => "set_username",
            Reducer::UnfollowUser { .. } => "unfollow_user",
            Reducer::UnregisterNotificationToken { .. } => "unregister_notification_token",
            Reducer::UpdatePostStatus { .. } => "update_post_status",
            Reducer::UpdateProfileAiInfluencerStatus { .. } => {
                "update_profile_ai_influencer_status"
            }
            Reducer::UpdateProfileDetails { .. } => "update_profile_details",
            Reducer::UpdateProfileDetailsV2 { .. } => "update_profile_details_v_2",
            Reducer::UpdateProfilePictureNsfwInfo { .. } => "update_profile_picture_nsfw_info",
            Reducer::UpdateUserLastAccessTime => "update_user_last_access_time",
            Reducer::UpsertPost { .. } => "upsert_post",
            Reducer::UpsertPostV2 { .. } => "upsert_post_v_2",
            Reducer::UpsertPostsBatch { .. } => "upsert_posts_batch",
            Reducer::UpsertPostsV2Batch { .. } => "upsert_posts_v_2_batch",
            Reducer::UpsertUserFollowBatch { .. } => "upsert_user_follow_batch",
            Reducer::UpsertUserProfileBatch { .. } => "upsert_user_profile_batch",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AcceptNewUserRegistrationV2 {
                new_principal_text,
                authenticated,
                main_account_text,
            } => __sats::bsatn::to_vec(
                &accept_new_user_registration_v_2_reducer::AcceptNewUserRegistrationV2Args {
                    new_principal_text: new_principal_text.clone(),
                    authenticated: authenticated.clone(),
                    main_account_text: main_account_text.clone(),
                },
            ),
            Reducer::AddPost {
                id,
                description,
                hashtags,
                video_uid,
                creator,
                status,
            } => __sats::bsatn::to_vec(&add_post_reducer::AddPostArgs {
                id: id.clone(),
                description: description.clone(),
                hashtags: hashtags.clone(),
                video_uid: video_uid.clone(),
                creator: creator.clone(),
                status: status.clone(),
            }),
            Reducer::AddProPlanFreeVideoCredits {
                principal_text,
                credits,
            } => __sats::bsatn::to_vec(
                &add_pro_plan_free_video_credits_reducer::AddProPlanFreeVideoCreditsArgs {
                    principal_text: principal_text.clone(),
                    credits: credits.clone(),
                },
            ),
            Reducer::AddViewDetails { post_id, details } => {
                __sats::bsatn::to_vec(&add_view_details_reducer::AddViewDetailsArgs {
                    post_id: post_id.clone(),
                    details: details.clone(),
                })
            }
            Reducer::ChangeSubscriptionPlan {
                principal_text,
                plan,
            } => __sats::bsatn::to_vec(
                &change_subscription_plan_reducer::ChangeSubscriptionPlanArgs {
                    principal_text: principal_text.clone(),
                    plan: plan.clone(),
                },
            ),
            Reducer::DeletePost { post_id } => {
                __sats::bsatn::to_vec(&delete_post_reducer::DeletePostArgs {
                    post_id: post_id.clone(),
                })
            }
            Reducer::DeleteUserInfo {
                principal_to_delete_text,
            } => __sats::bsatn::to_vec(&delete_user_info_reducer::DeleteUserInfoArgs {
                principal_to_delete_text: principal_to_delete_text.clone(),
            }),
            Reducer::FollowUser { followee_text } => {
                __sats::bsatn::to_vec(&follow_user_reducer::FollowUserArgs {
                    followee_text: followee_text.clone(),
                })
            }
            Reducer::KvDelete { key } => {
                __sats::bsatn::to_vec(&kv_delete_reducer::KvDeleteArgs { key: key.clone() })
            }
            Reducer::KvSet { key, value } => __sats::bsatn::to_vec(&kv_set_reducer::KvSetArgs {
                key: key.clone(),
                value: value.clone(),
            }),
            Reducer::LinkUserId {
                principal_text,
                user_id,
            } => __sats::bsatn::to_vec(&link_user_id_reducer::LinkUserIdArgs {
                principal_text: principal_text.clone(),
                user_id: user_id.clone(),
            }),
            Reducer::RegisterNewUser => {
                __sats::bsatn::to_vec(&register_new_user_reducer::RegisterNewUserArgs {})
            }
            Reducer::RegisterNotificationToken { token } => __sats::bsatn::to_vec(
                &register_notification_token_reducer::RegisterNotificationTokenArgs {
                    token: token.clone(),
                },
            ),
            Reducer::RemoveProPlanFreeVideoCredits {
                principal_text,
                credits,
            } => __sats::bsatn::to_vec(
                &remove_pro_plan_free_video_credits_reducer::RemoveProPlanFreeVideoCreditsArgs {
                    principal_text: principal_text.clone(),
                    credits: credits.clone(),
                },
            ),
            Reducer::SetEmail {
                principal_text,
                email,
            } => __sats::bsatn::to_vec(&set_email_reducer::SetEmailArgs {
                principal_text: principal_text.clone(),
                email: email.clone(),
            }),
            Reducer::SetUsername {
                principal_text,
                username,
            } => __sats::bsatn::to_vec(&set_username_reducer::SetUsernameArgs {
                principal_text: principal_text.clone(),
                username: username.clone(),
            }),
            Reducer::UnfollowUser { followee_text } => {
                __sats::bsatn::to_vec(&unfollow_user_reducer::UnfollowUserArgs {
                    followee_text: followee_text.clone(),
                })
            }
            Reducer::UnregisterNotificationToken { token } => __sats::bsatn::to_vec(
                &unregister_notification_token_reducer::UnregisterNotificationTokenArgs {
                    token: token.clone(),
                },
            ),
            Reducer::UpdatePostStatus { post_id, status } => {
                __sats::bsatn::to_vec(&update_post_status_reducer::UpdatePostStatusArgs {
                    post_id: post_id.clone(),
                    status: status.clone(),
                })
            }
            Reducer::UpdateProfileAiInfluencerStatus {
                principal_text,
                is_ai_influencer,
            } => __sats::bsatn::to_vec(
                &update_profile_ai_influencer_status_reducer::UpdateProfileAiInfluencerStatusArgs {
                    principal_text: principal_text.clone(),
                    is_ai_influencer: is_ai_influencer.clone(),
                },
            ),
            Reducer::UpdateProfileDetails {
                bio,
                website_url,
                profile_pic_url,
            } => __sats::bsatn::to_vec(&update_profile_details_reducer::UpdateProfileDetailsArgs {
                bio: bio.clone(),
                website_url: website_url.clone(),
                profile_pic_url: profile_pic_url.clone(),
            }),
            Reducer::UpdateProfileDetailsV2 {
                bio,
                website_url,
                profile_picture,
            } => __sats::bsatn::to_vec(
                &update_profile_details_v_2_reducer::UpdateProfileDetailsV2Args {
                    bio: bio.clone(),
                    website_url: website_url.clone(),
                    profile_picture: profile_picture.clone(),
                },
            ),
            Reducer::UpdateProfilePictureNsfwInfo {
                principal_text,
                nsfw_info,
            } => __sats::bsatn::to_vec(
                &update_profile_picture_nsfw_info_reducer::UpdateProfilePictureNsfwInfoArgs {
                    principal_text: principal_text.clone(),
                    nsfw_info: nsfw_info.clone(),
                },
            ),
            Reducer::UpdateUserLastAccessTime => __sats::bsatn::to_vec(
                &update_user_last_access_time_reducer::UpdateUserLastAccessTimeArgs {},
            ),
            Reducer::UpsertPost { post } => {
                __sats::bsatn::to_vec(&upsert_post_reducer::UpsertPostArgs { post: post.clone() })
            }
            Reducer::UpsertPostV2 { post } => {
                __sats::bsatn::to_vec(&upsert_post_v_2_reducer::UpsertPostV2Args {
                    post: post.clone(),
                })
            }
            Reducer::UpsertPostsBatch { posts } => {
                __sats::bsatn::to_vec(&upsert_posts_batch_reducer::UpsertPostsBatchArgs {
                    posts: posts.clone(),
                })
            }
            Reducer::UpsertPostsV2Batch { posts } => {
                __sats::bsatn::to_vec(&upsert_posts_v_2_batch_reducer::UpsertPostsV2BatchArgs {
                    posts: posts.clone(),
                })
            }
            Reducer::UpsertUserFollowBatch { follows } => __sats::bsatn::to_vec(
                &upsert_user_follow_batch_reducer::UpsertUserFollowBatchArgs {
                    follows: follows.clone(),
                },
            ),
            Reducer::UpsertUserProfileBatch { profiles } => __sats::bsatn::to_vec(
                &upsert_user_profile_batch_reducer::UpsertUserProfileBatchArgs {
                    profiles: profiles.clone(),
                },
            ),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    posts: __sdk::TableUpdate<Post>,
    posts_v_2: __sdk::TableUpdate<PostV2>,
    user_follows: __sdk::TableUpdate<UserFollow>,
    user_notification_tokens: __sdk::TableUpdate<UserNotificationToken>,
    user_profiles: __sdk::TableUpdate<UserProfile>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "posts" => db_update
                    .posts
                    .append(posts_table::parse_table_update(table_update)?),
                "posts_v2" => db_update
                    .posts_v_2
                    .append(posts_v_2_table::parse_table_update(table_update)?),
                "user_follows" => db_update
                    .user_follows
                    .append(user_follows_table::parse_table_update(table_update)?),
                "user_notification_tokens" => db_update.user_notification_tokens.append(
                    user_notification_tokens_table::parse_table_update(table_update)?,
                ),
                "user_profiles" => db_update
                    .user_profiles
                    .append(user_profiles_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.posts = cache
            .apply_diff_to_table::<Post>("posts", &self.posts)
            .with_updates_by_pk(|row| &row.id);
        diff.posts_v_2 = cache
            .apply_diff_to_table::<PostV2>("posts_v2", &self.posts_v_2)
            .with_updates_by_pk(|row| &row.id);
        diff.user_follows = cache
            .apply_diff_to_table::<UserFollow>("user_follows", &self.user_follows)
            .with_updates_by_pk(|row| &row.key);
        diff.user_notification_tokens = cache
            .apply_diff_to_table::<UserNotificationToken>(
                "user_notification_tokens",
                &self.user_notification_tokens,
            )
            .with_updates_by_pk(|row| &row.key);
        diff.user_profiles = cache
            .apply_diff_to_table::<UserProfile>("user_profiles", &self.user_profiles)
            .with_updates_by_pk(|row| &row.principal_text);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "posts" => db_update
                    .posts
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "posts_v2" => db_update
                    .posts_v_2
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user_follows" => db_update
                    .user_follows
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user_notification_tokens" => db_update
                    .user_notification_tokens
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user_profiles" => db_update
                    .user_profiles
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "posts" => db_update
                    .posts
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "posts_v2" => db_update
                    .posts_v_2
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user_follows" => db_update
                    .user_follows
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user_notification_tokens" => db_update
                    .user_notification_tokens
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user_profiles" => db_update
                    .user_profiles
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    posts: __sdk::TableAppliedDiff<'r, Post>,
    posts_v_2: __sdk::TableAppliedDiff<'r, PostV2>,
    user_follows: __sdk::TableAppliedDiff<'r, UserFollow>,
    user_notification_tokens: __sdk::TableAppliedDiff<'r, UserNotificationToken>,
    user_profiles: __sdk::TableAppliedDiff<'r, UserProfile>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Post>("posts", &self.posts, event);
        callbacks.invoke_table_row_callbacks::<PostV2>("posts_v2", &self.posts_v_2, event);
        callbacks.invoke_table_row_callbacks::<UserFollow>(
            "user_follows",
            &self.user_follows,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UserNotificationToken>(
            "user_notification_tokens",
            &self.user_notification_tokens,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UserProfile>(
            "user_profiles",
            &self.user_profiles,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        posts_table::register_table(client_cache);
        posts_v_2_table::register_table(client_cache);
        user_follows_table::register_table(client_cache);
        user_notification_tokens_table::register_table(client_cache);
        user_profiles_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "posts",
        "posts_v2",
        "user_follows",
        "user_notification_tokens",
        "user_profiles",
    ];
}
