// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LinkUserIdArgs {
    pub principal_text: String,
    pub user_id: String,
}

impl From<LinkUserIdArgs> for super::Reducer {
    fn from(args: LinkUserIdArgs) -> Self {
        Self::LinkUserId {
            principal_text: args.principal_text,
            user_id: args.user_id,
        }
    }
}

impl __sdk::InModule for LinkUserIdArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `link_user_id`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait link_user_id {
    /// Request that the remote module invoke the reducer `link_user_id` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`link_user_id:link_user_id_then`] to run a callback after the reducer completes.
    fn link_user_id(&self, principal_text: String, user_id: String) -> __sdk::Result<()> {
        self.link_user_id_then(principal_text, user_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `link_user_id` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn link_user_id_then(
        &self,
        principal_text: String,
        user_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl link_user_id for super::RemoteReducers {
    fn link_user_id_then(
        &self,
        principal_text: String,
        user_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            LinkUserIdArgs {
                principal_text,
                user_id,
            },
            callback,
        )
    }
}
