// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::post_status_type::PostStatus;
use super::post_v_2_type::PostV2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `posts_v2`.
///
/// Obtain a handle from the [`PostsV2TableAccess::posts_v_2`] method on [`super::RemoteTables`],
/// like `ctx.db.posts_v_2()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.posts_v_2().on_insert(...)`.
pub struct PostsV2TableHandle<'ctx> {
    imp: __sdk::TableHandle<PostV2>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `posts_v2`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PostsV2TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PostsV2TableHandle`], which mediates access to the table `posts_v2`.
    fn posts_v_2(&self) -> PostsV2TableHandle<'_>;
}

impl PostsV2TableAccess for super::RemoteTables {
    fn posts_v_2(&self) -> PostsV2TableHandle<'_> {
        PostsV2TableHandle {
            imp: self.imp.get_table::<PostV2>("posts_v2"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PostsV2InsertCallbackId(__sdk::CallbackId);
pub struct PostsV2DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PostsV2TableHandle<'ctx> {
    type Row = PostV2;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PostV2> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PostsV2InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PostsV2InsertCallbackId {
        PostsV2InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PostsV2InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PostsV2DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PostsV2DeleteCallbackId {
        PostsV2DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PostsV2DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PostsV2UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PostsV2TableHandle<'ctx> {
    type UpdateCallbackId = PostsV2UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PostsV2UpdateCallbackId {
        PostsV2UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PostsV2UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `posts_v2`,
/// which allows point queries on the field of the same name
/// via the [`PostsV2IdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.posts_v_2().id().find(...)`.
pub struct PostsV2IdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PostV2, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PostsV2TableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `posts_v2`.
    pub fn id(&self) -> PostsV2IdUnique<'ctx> {
        PostsV2IdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PostsV2IdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PostV2> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PostV2>("posts_v2");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PostV2>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PostV2>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PostV2`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait posts_v_2QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PostV2`.
    fn posts_v_2(&self) -> __sdk::__query_builder::Table<PostV2>;
}

impl posts_v_2QueryTableAccess for __sdk::QueryTableAccessor {
    fn posts_v_2(&self) -> __sdk::__query_builder::Table<PostV2> {
        __sdk::__query_builder::Table::new("posts_v2")
    }
}
