// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::profile_picture_data_type::ProfilePictureData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateProfileDetailsV2Args {
    pub bio: Option<String>,
    pub website_url: Option<String>,
    pub profile_picture: Option<ProfilePictureData>,
}

impl From<UpdateProfileDetailsV2Args> for super::Reducer {
    fn from(args: UpdateProfileDetailsV2Args) -> Self {
        Self::UpdateProfileDetailsV2 {
            bio: args.bio,
            website_url: args.website_url,
            profile_picture: args.profile_picture,
        }
    }
}

impl __sdk::InModule for UpdateProfileDetailsV2Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_profile_details_v_2`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_profile_details_v_2 {
    /// Request that the remote module invoke the reducer `update_profile_details_v_2` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_profile_details_v_2:update_profile_details_v_2_then`] to run a callback after the reducer completes.
    fn update_profile_details_v_2(
        &self,
        bio: Option<String>,
        website_url: Option<String>,
        profile_picture: Option<ProfilePictureData>,
    ) -> __sdk::Result<()> {
        self.update_profile_details_v_2_then(bio, website_url, profile_picture, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_profile_details_v_2` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_profile_details_v_2_then(
        &self,
        bio: Option<String>,
        website_url: Option<String>,
        profile_picture: Option<ProfilePictureData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_profile_details_v_2 for super::RemoteReducers {
    fn update_profile_details_v_2_then(
        &self,
        bio: Option<String>,
        website_url: Option<String>,
        profile_picture: Option<ProfilePictureData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateProfileDetailsV2Args {
                bio,
                website_url,
                profile_picture,
            },
            callback,
        )
    }
}
