// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_notification_token_type::UserNotificationToken;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_notification_tokens`.
///
/// Obtain a handle from the [`UserNotificationTokensTableAccess::user_notification_tokens`] method on [`super::RemoteTables`],
/// like `ctx.db.user_notification_tokens()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_notification_tokens().on_insert(...)`.
pub struct UserNotificationTokensTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserNotificationToken>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_notification_tokens`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserNotificationTokensTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserNotificationTokensTableHandle`], which mediates access to the table `user_notification_tokens`.
    fn user_notification_tokens(&self) -> UserNotificationTokensTableHandle<'_>;
}

impl UserNotificationTokensTableAccess for super::RemoteTables {
    fn user_notification_tokens(&self) -> UserNotificationTokensTableHandle<'_> {
        UserNotificationTokensTableHandle {
            imp: self
                .imp
                .get_table::<UserNotificationToken>("user_notification_tokens"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserNotificationTokensInsertCallbackId(__sdk::CallbackId);
pub struct UserNotificationTokensDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserNotificationTokensTableHandle<'ctx> {
    type Row = UserNotificationToken;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserNotificationToken> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserNotificationTokensInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserNotificationTokensInsertCallbackId {
        UserNotificationTokensInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserNotificationTokensInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserNotificationTokensDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserNotificationTokensDeleteCallbackId {
        UserNotificationTokensDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserNotificationTokensDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserNotificationTokensUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserNotificationTokensTableHandle<'ctx> {
    type UpdateCallbackId = UserNotificationTokensUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserNotificationTokensUpdateCallbackId {
        UserNotificationTokensUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserNotificationTokensUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `user_notification_tokens`,
/// which allows point queries on the field of the same name
/// via the [`UserNotificationTokensKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_notification_tokens().key().find(...)`.
pub struct UserNotificationTokensKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserNotificationToken, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserNotificationTokensTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `user_notification_tokens`.
    pub fn key(&self) -> UserNotificationTokensKeyUnique<'ctx> {
        UserNotificationTokensKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserNotificationTokensKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserNotificationToken> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<UserNotificationToken>("user_notification_tokens");
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserNotificationToken>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserNotificationToken>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserNotificationToken`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_notification_tokensQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserNotificationToken`.
    fn user_notification_tokens(&self) -> __sdk::__query_builder::Table<UserNotificationToken>;
}

impl user_notification_tokensQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_notification_tokens(&self) -> __sdk::__query_builder::Table<UserNotificationToken> {
        __sdk::__query_builder::Table::new("user_notification_tokens")
    }
}
