// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::subscription_plan_type::SubscriptionPlan;
use super::user_account_type_type::UserAccountType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserProfile {
    pub principal_text: String,
    pub bio: String,
    pub website_url: String,
    pub profile_picture_url: String,
    pub followers_count: u64,
    pub following_count: u64,
    pub subscription_plan: SubscriptionPlan,
    pub is_ai_influencer: bool,
    pub is_nsfw: bool,
    pub nsfw_ec: String,
    pub nsfw_gore: String,
    pub csam_detected: bool,
    pub last_access_time: __sdk::Timestamp,
    pub account_type: UserAccountType,
    pub username: Option<String>,
    pub email: Option<String>,
    pub user_id: Option<String>,
}

impl __sdk::InModule for UserProfile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserProfile`.
///
/// Provides typed access to columns for query building.
pub struct UserProfileCols {
    pub principal_text: __sdk::__query_builder::Col<UserProfile, String>,
    pub bio: __sdk::__query_builder::Col<UserProfile, String>,
    pub website_url: __sdk::__query_builder::Col<UserProfile, String>,
    pub profile_picture_url: __sdk::__query_builder::Col<UserProfile, String>,
    pub followers_count: __sdk::__query_builder::Col<UserProfile, u64>,
    pub following_count: __sdk::__query_builder::Col<UserProfile, u64>,
    pub subscription_plan: __sdk::__query_builder::Col<UserProfile, SubscriptionPlan>,
    pub is_ai_influencer: __sdk::__query_builder::Col<UserProfile, bool>,
    pub is_nsfw: __sdk::__query_builder::Col<UserProfile, bool>,
    pub nsfw_ec: __sdk::__query_builder::Col<UserProfile, String>,
    pub nsfw_gore: __sdk::__query_builder::Col<UserProfile, String>,
    pub csam_detected: __sdk::__query_builder::Col<UserProfile, bool>,
    pub last_access_time: __sdk::__query_builder::Col<UserProfile, __sdk::Timestamp>,
    pub account_type: __sdk::__query_builder::Col<UserProfile, UserAccountType>,
    pub username: __sdk::__query_builder::Col<UserProfile, Option<String>>,
    pub email: __sdk::__query_builder::Col<UserProfile, Option<String>>,
    pub user_id: __sdk::__query_builder::Col<UserProfile, Option<String>>,
}

impl __sdk::__query_builder::HasCols for UserProfile {
    type Cols = UserProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserProfileCols {
            principal_text: __sdk::__query_builder::Col::new(table_name, "principal_text"),
            bio: __sdk::__query_builder::Col::new(table_name, "bio"),
            website_url: __sdk::__query_builder::Col::new(table_name, "website_url"),
            profile_picture_url: __sdk::__query_builder::Col::new(
                table_name,
                "profile_picture_url",
            ),
            followers_count: __sdk::__query_builder::Col::new(table_name, "followers_count"),
            following_count: __sdk::__query_builder::Col::new(table_name, "following_count"),
            subscription_plan: __sdk::__query_builder::Col::new(table_name, "subscription_plan"),
            is_ai_influencer: __sdk::__query_builder::Col::new(table_name, "is_ai_influencer"),
            is_nsfw: __sdk::__query_builder::Col::new(table_name, "is_nsfw"),
            nsfw_ec: __sdk::__query_builder::Col::new(table_name, "nsfw_ec"),
            nsfw_gore: __sdk::__query_builder::Col::new(table_name, "nsfw_gore"),
            csam_detected: __sdk::__query_builder::Col::new(table_name, "csam_detected"),
            last_access_time: __sdk::__query_builder::Col::new(table_name, "last_access_time"),
            account_type: __sdk::__query_builder::Col::new(table_name, "account_type"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
        }
    }
}

/// Indexed column accessor struct for the table `UserProfile`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserProfileIxCols {
    pub principal_text: __sdk::__query_builder::IxCol<UserProfile, String>,
}

impl __sdk::__query_builder::HasIxCols for UserProfile {
    type IxCols = UserProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserProfileIxCols {
            principal_text: __sdk::__query_builder::IxCol::new(table_name, "principal_text"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserProfile {}
