// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::subscription_plan_type::SubscriptionPlan;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserProfileBatchEntry {
    pub principal_text: String,
    pub bio: String,
    pub website_url: String,
    pub profile_picture_url: String,
    pub followers_count: u64,
    pub following_count: u64,
    pub subscription_plan: SubscriptionPlan,
    pub is_ai_influencer: bool,
    pub is_nsfw: bool,
    pub nsfw_ec: String,
    pub nsfw_gore: String,
    pub csam_detected: bool,
    pub last_access_time: __sdk::Timestamp,
}

impl __sdk::InModule for UserProfileBatchEntry {
    type Module = super::RemoteModule;
}
