apiVersion: v1
kind: Secret
metadata:
    name: github-ssh-secret
    namespace: yral-metadata
type: kubernetes.io/ssh-auth
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:6FIgR5bWwP4KkcZSjJ7eQ0ygAv5ILW2RhOXimkOVYsLss1R7gFCDRvm3DzQ1ULW2nx4Ub++NjsbofoFcaNmS3hJK8/aDNbTOfnKR3pprJAePDNOzycNnkX+CZiD2ns2ColSbKCVCnw+KLFQVAlL2LBuA/aTf4RegUaljv1E4aakbhtt9L9bV08Aq8zkbL/9eVL2eRK9+fntTYWS4uvlChP7M3DtCDTIAWYCjnErsRh09bky7ReBBmOGwXm+/LgkfF6Cp5POYhvxyH/T2btH5V9LFHmdQn098DD6NNd9AHvv6VXxDM26nzBXe+Vh63QMP4hlHDvdNVbWffhWVfLH5/3ImE9qx7jLKH1DMEoJVoEJh8aqnGL44Z03+N6Nv4UA47a/ZibFCoVcxzD3CKp/Tb9MY/CJlR98jK0LPt3UEcDuUgv+8N304vyF11eVypU+tEQqdnDVFxZRWmKV3AFPqDEP8IIKR8YCkw0BWpwl06KwNm9IlZkLXbZ/Y8vK3IKmwIY1BmrZ4vUBGC8ItUPQtSTtlQnU/GiVhb0AwAV28hfS5gRyO,iv:B7y3NCLmsV2mMcrReAI+7JURm+qsfguHSv9Q16pCgSI=,tag:9feOBrOn5Ca4m2lFq32V3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R2tqbnhhdXFkY2dza0FP
            ZWtMYVpnVnluQzgzMU43enc3dTJQc0wyNXg0Ckw3T3l6QWR6c1UwM3VqZEg0MnJP
            bUFHSnNpQnduUHV6WHRhR21kT1NSTVUKLS0tICs3eklFQ0VScms2akk4c29STlpw
            TUkxMXFWMTcxcUlFTXhpby9SYmdNczAKV8N7mv6Rx/07AtFllbeDvxsaAFM5cEoW
            OwIiTX/vEUSKpeTv0St/NKMXNwkMJWIB/j30crWV0doKTsQDIKgD3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T10:20:47Z"
    mac: ENC[AES256_GCM,data:Ahwaod0lsKECwKlbK8k33eqoSkfd1xKMX3pQ0TsSTQO4GPWb5DFWESN/mb+NhBeuiEDLvr8lrcSf9pNrfMrpuXsIDnGVxOv+SLBZ6NwSR/5ISiMWUuQbQuMhroSX1yOJQy1BUmuJM6BJd1DvR7iT1QPVbs/32ZPTAOIqEyUBuYo=,iv:KyUFl4wU0YHyO2+NvIA4U+niq76/1ai/9+5SwjmwacI=,tag:LaBUjX/2ggvaQRCqEV25ag==,type:str]
    version: 3.13.2
