apiVersion: ENC[AES256_GCM,data:cEs=,iv:KGCpHU+yFvBbfF13ul06OVwkLm2Oj9rBx1afyBVpPw4=,tag:h5sqm2qmEi6We77GThk0vQ==,type:str]
kind: ENC[AES256_GCM,data:8YicT5DO,iv:ld6mLM9pPzsfRvKrby7QcMXfowx6Y0S8z1vhRZp4GWA=,tag:RVW3YixnfqznB9T3PQy7Vw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0tj1x7ExclA49eIsBQ/Vb3DJ1Q==,iv:gDKSBfK5VqvwLXETBS6DBBRQ8pD4SBo2vvKM4q527Mo=,tag:AXcfibcXgvO7Gl1OacJDcg==,type:str]
    namespace: ENC[AES256_GCM,data:86NKM5f3EHHYtHXSkw==,iv:yh8f8KQWz58N9NkwKXKTmuQdThxLhc6oBvzUaSyRxsY=,tag:jYtFnKLTycesGfkCC5tqJw==,type:str]
type: ENC[AES256_GCM,data:c0isxZ7FI4DLARTKkvYwxgpn004xU2fa,iv:i6r1rQFZdii/Hk3DT37PaX1pUK/oaW1Edtfw9IdNCcU=,tag:xaiy+8KaMfaA+lFu15c8Yw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:9QZn,iv:9zo+xh+KJNRHzsbDHV+8NfQ5itxRhd816OnQlwzL+t0=,tag:elo9EXh1DNSk6A+RTQzWQQ==,type:str]
    password: ENC[AES256_GCM,data:QeuRsc0nc6Whi7Wq3ZI7gYLZc4VQBRIROP8Tg4tzU5pp2rbQfHxihRYMkjH10GNCFiL2BYH9r1yzjg2w/1Kim7qNEiWv8GJ81Xwy7WI7hh0R5PwkrYELYg3NXsoH,iv:KfxNXQkZ1cjJPFh5uCK50Q3M9UMivoQQOb1dFb02MEM=,tag:Q6oNPH5kYmkxMyfm3s5UdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN2dkZ0FiamRiK1F3MUFu
            eDloVCtPNzFjY1Mxa0pxaG0xNVcwMnNNMXpnCnZWM1RWYk1raE13Z0daQlVvcGJN
            UnIwbUFGbVpQV2tDT3ZwSTFVc09HWWcKLS0tIFBUZGsxR0FSZzhtdHZHNEFNYVQv
            Wi9iVEVLTytyNWd6MURZVG0vNS8rWlEKD8Ng8/DGF8Mx4jE1m2K5Fy0wCvvmk6uO
            QSmVVwS893f7TSqzEZyhM3o3KzJZL/4MHgvlEylbbK06rocAa6cTMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-16T11:00:02Z"
    mac: ENC[AES256_GCM,data:RnAtJWqOw5rwjH3bvIl2IumOmIRJ7TAm8UwXPi8mY31jvbN8F4MiNbIqkPOq9jYUm8QO+uttk6ybjpxdmRAz4SBnZo5FyjrQW6dEEWRTlvqPLNNJhhCC3mBgF1j9HbPpX49Wh9aPBIkE4nX3tvAhll85zxAonn5RT8KtDjoIgDE=,iv:Xl4G5e9gv93Iy0e9KRS6l431VZQ3B0DwQz+htfTMqAk=,tag:NACtnooPOUl7JIk+HGIgTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
