apiVersion: v1
kind: Secret
metadata:
    name: harbor-scan-secret
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:CAFsHe58KS/1IGw8cFkYM6ucCGFuVjE=,iv:k5kGWcITNUvfPYZlibjkgAArOgqg/kwRz52fDpNhSX0=,tag:V4RvalC/ynNyn2kDa0/sFw==,type:str]
    password: ENC[AES256_GCM,data:tSzDyORTPnkDcwMvm04Q0yx4y9oLy87xnRKfct+t0ng=,iv:5hcW6bleNCsVFHVVgq4FY+emYRZM8oFrjvxEKqDRzJ4=,tag:ftwTsLaykhSPEcg09KDvcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRmlDNW43OTV3Smo0VDVR
            TW5JOUNvNGNGUmJsbVpvRkpmMDhEWTRSYmp3CjBvRW80ajR1bTBBR0JZRVpjbDN4
            bFUzOGJ5Um5MSW82c1dHZUsycTUwWUUKLS0tIDJjeVRNOVpBZzNGRmNEalViaG5R
            NmFKaWtaRFJNTFVGRkdVNkV4ZCs3cncKY9CqYnuAyJIoOPVCfwqjQ7zS2dmMAXAs
            SIh8icTjadG8Ac6RVCaph8Eghqlr7TbjMyjZ4PRziGugda6DwsQpeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:41:36Z"
    mac: ENC[AES256_GCM,data:BMdyjXiTmcwDDzFjPPunjtWTIM6DYRY/0sqRZexnTX3T/FDpgK+s5i7hcvd+0XPIfz/wvwYO0xcebSBOMDi8nq6gtZTbjiF7SJDiJ1+EZ0X2Z0sQ9kTeyidyyoBThHy+vA0aNDnUFgeSj8N7/7phu+ftPvhpWrplIRbW+vgB/8I=,iv:0ta5jQ59bKz1Na9YUgC2YfntAXZxHB4IpbZIupti7LQ=,tag:GJYJvFQWEOWBQRuLjScoXA==,type:str]
    version: 3.13.2
