apiVersion: ENC[AES256_GCM,data:M7g=,iv:kGQFAiv3Sx00xQFc4IDirXC0/wc7jRaq/pfsi99eEAk=,tag:aph/AcitmjtE5lIYuwswJQ==,type:str]
kind: ENC[AES256_GCM,data:YsvX52aa,iv:B9yFgeNKniNL7J6DF1k+e/oYBZRWwqDeybxwaSuJUeo=,tag:Q8URDS1Lj1nu0nTaSISFSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ly5KH3yPYujC7YxDdzOhPG+O,iv:Qxj9gEzU3P0SOHCeeKjG7ZGZKX2TwDfIUUnaBVtexwE=,tag:X1XCtY+mL3fN+BienyzIxg==,type:str]
    namespace: ENC[AES256_GCM,data:04vtMYe+9zSYHZo=,iv:MjZx3q7jmJiRiVKq4ip/Ngwf4ah3X+0yLDNHDDIZ8Go=,tag:7g0ubtwkOOF3UiqZTwndqA==,type:str]
type: ENC[AES256_GCM,data:FfH/niUxcQypLciciF36PZL+pCO9N/OrySAptgHZ,iv:i1ARgqqeo+YrEQWq76bq9TXrDZTAIgmtU7KdwfM6yk0=,tag:xUBEiWnHTtJcFvzvefwgfA==,type:str]
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:XeTqlqmf+YRZILatvanombnHwxOC5aBbbbdIW/+3r7qxQP1fJGBmuEeI3H3iSYcvPMqkbs2f+cYNK1QDWx3fOt+TKrLrgQKw4ZmSZuSMlxiQqsJpvPetKlxL61M39jI=,iv:9X8Hkv6M8jus0zWMqyfK0Afsh7J/biwJJlsZ4SC+gY4=,tag:Sla5jsz6McfYE+YFxVR7tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbDMxU0E5Y2pjWlh1SkhC
            eGJnWmNsV05MTmFyQi9qdW9WaWFvS3JvR1N3ClVqalN6dHVSVlg3cW9rNlZlWTYy
            ZUo0S0JBOGcyYm9EWDRaVTIzSDJIQ0UKLS0tIGVvcXc1c1ZBai9HZGQ4blJoTEZP
            T3lEbFQxQldNL1cyV0lUcUcwVWh4aDgKBm09m/2X5eo4FTEU3MEpfjwBiT2MSSQO
            h45uYVo96UFl4/aBA73gQy9GLKZ2ZFrHLsfRqEcn5KiWnzf/xInooA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-16T11:00:02Z"
    mac: ENC[AES256_GCM,data:2Up2NXPEUBrB3O9+V4ipRap5rsae3kvkKQuI+FBrcmcGDqKgeCgDwqICSaSaGQDISUZjZQ8pjKfjZ2OWp8E7VJFcSGqovQNwgyWqgpDM/01gpqWV4Ps95KVaZ9FREdsqHBc3gDtuy4Nlyf2TPNWD88rPqirv9za9Uwb9EnPrx5E=,iv:bkWhTr96VOGFLWPDtqyxh1G0+2MXp8OBZtgWImwV5gY=,tag:ebdE13Xzy/4Gk5MxpJRTjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
