apiVersion: v1
kind: Secret
metadata:
    name: harbor-scan-secret
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:94heKHzzx4DQBhLGxoGUvshrjF4gx9Y=,iv:wpOjCWMZFIrzzbUu8Afee+AUZqaF+Lp69cmKkqp1Muc=,tag:787SyaynPWbxpyabNGhKxw==,type:str]
    password: ENC[AES256_GCM,data:hjDVPnB6V0qIhO8KwnQWyshY+VlgOCF+vgBA6hw867U=,iv:FfKcdVZGPkyoCWPiwfHw2LH4fK1mCo197RDdw2mohmk=,tag:uRYyQuEIpusYX8MQqOoRcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWkxCOThZd0NNOXBDb2F5
            ZWk1Y1BSSktsakJTMEorcFpRcGlyRHgrMWpjCm12Zk5VODBDWi9md2dhcG9pQmU0
            VEtZOGpINnVJbHN0cllTMDlsNVg1UXcKLS0tIDgyMG5yUlNTa3NqMi8zcVhxYUlW
            ZitTdXFEejE4TUxVY3ZtVjJqM2xTd3MKwBb3aBic1+zaoxaiiUDjFC6kp1NfE2+S
            K+KZ0xuKDXXR/QqnK8hMoEnRL6iZ0tz/w4NFPJ+Ek16VQ4KDzoy3Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:52:28Z"
    mac: ENC[AES256_GCM,data:bR9pNB6kop/DL1t+z0udrTkcVlT/ajkwx4Kc3yPGrwTUfoI7L28URA3oK9LuvzYX66crigdoiwXcxVkI+gWH0JPzLfOWUUgPCsi+wWiB6ES8Yio7pakJ3QyKu4TOYbl/ykzEgwc03fc0kAi8IRMMKZeB829UrpLfVOtpJorbB+8=,iv:bcaUGZMyBRATZCMeNMq/fCrm8W0u4TI5Ch+uprmALJw=,tag:J8fDmiP9zJIQj1A/gEsuwA==,type:str]
    version: 3.13.2
