apiVersion: v1
kind: Secret
metadata:
    name: harbor-pull-secret
    namespace: yral-metadata
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:amvWMR3nmsVY2k7gFiqi92Do3kUsqf5aZkM8eI7sys3E5whs3tmQI/e/h+BpY3UxnO34Up+q4qUbuiIttHG7dALxQn4OBSh1xGJa4bc89KUibproe+XGSZ9Pq6ySUjv9bP8zWoPaysDzigzCDF74NYiB8VJ5bEOjSeVBWDOC5WjdOoz7imQobfBqTy/rWYF6Hd/EdqG/m5U8TqXjPG5MEoI7eRjbYnZO4//IuZ7MaLgctxFEnkjb+iyr39+MJ29mnguDcigjkg4=,iv:xv9wX13coq8g/cXe+a0oNJUgb/dojdaXwDTOtvRBhJU=,tag:vtLUlPYsl22HDVHZObvdwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQlhJWXpYWHYvMzIzVStV
            N1FSRk0rK0dSQ2hsbVZzNjBnRmdqMXZGQjBJCmt0QjNkTWJVcVdGYW5zb0VWM1Z0
            MWplTzBkSllPRnFrQ2RSaCtOU0RSTG8KLS0tIDFDN0NkbEhieHFWcGdOdE1sZkY3
            STBtaEUzaTA1VGQ2akNxRVBEK2NFQjAKAfW3do2ifWIdnPrWo9yHgrW5YHno/PeR
            WIox/sXjNiNpM9l2tpbrpaf09lmRTLVJCCEvjq7egIaBHeSRUa8wOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:52:28Z"
    mac: ENC[AES256_GCM,data:ZTNfBnn0BnZdKyPLMZVJgif8XU3vs+4jDqJWy4xJeSz+dlUVlklrg2xZS+KE682sIJhkNcHkMWJl1WVa5ucfkDl7WRqflTK3ec7izM99IAC4K8Bju2A1jwrGFbNH0xHC8otfE66Z9ES82kyH86n2EfsFMnPZIF/mauCcFzUBMxc=,iv:i26CfxcoBPCfVmdwGRzuiFJEGEUSFhqvqlIdWbbwhgI=,tag:ULyStxSVbzFtwGwgcOrZGg==,type:str]
    version: 3.13.2
