apiVersion: ENC[AES256_GCM,data:VuM=,iv:siS0ug75SwxQBQA+Xv6jd84UBBt3pV46ULRJ60f/A5U=,tag:k9wLAjWsDpjtd1t6wWn2Zg==,type:str]
kind: ENC[AES256_GCM,data:5NjgPsFV,iv:L6gz/mCOUgZjQaCiDvTx40C0bXj9Ch6htCWIMFiRT+E=,tag:eBmNJbVWz9pGrEyJiavnaQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:21m+Ok1swCBHNQ9IR+HwXFSg,iv:vkmRg3WAyyg6e9hTJY21oj1cspqqx4SirUJhruteaN4=,tag:6ZpxSuYyF6LQf7x0llIIYA==,type:str]
    namespace: ENC[AES256_GCM,data:kVGu4bmmRuklinKljw==,iv:JEfZnPXOTwab+9Yzo+aNGustRQZ9vbsJ3Tk7Y0T9pRA=,tag:rwzocPK4hSOXlLzC4ozRXw==,type:str]
type: ENC[AES256_GCM,data:6I3ieZhPBI7CALzKBrqouBx2yhVnjSV5bH0E99AF,iv:j4WgDROzSAbv+KLSnPfMC9+7L4EUj7WM4XJ01w1Amq4=,tag:Kbp9557/l+WmCGgvrmvKtQ==,type:str]
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:6UomRd4SuWxCsHMpMyKM+oeTJeay73a40ePyWfBIT/zlbVh6rJlfTpNMMNjnmKBYQhA9dZKfK6S7VfRpJtMcfyU6G1+eGZe/FqBk3f8tk4P/PjAHtBOsmLdCdhejALQwC0RR7SewEJpvUeaTyWzeLRxJogZ7CUHLNq6+uShuuGT7ILypY1Va7taqQZVmBLwo3tfd4oG1yzik9gQCWxCwUvgghDPQafpr8i8g5tw6mwf3QG3q9hcV62dg/zVx2uyqYbM0XHf/Iq8Khz282mcjux48vNKfnad+yMUbcseRbAhQmRuMrzolLrNGVMg3//Pmn4Y=,iv:1sG02uMcp1eaG4GpFz3RnksUc0+gnqRG5uSB69IIzx4=,tag:2cizB/iLg8/4XBwJy6xrnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMGVDU0x5cGJhWFlIaHdH
            QlNiWHRqTklYaE1ieGRLM0FHNTUzQ1cwRGhrClQvdzNqcW84OXMvMURBZkIwanJs
            RHpFeUhGRDMzOExnbG9YaE5uTTZTczgKLS0tIEhGa1JjSkhPM3lIbGRFU2cycjk1
            Z2tvQjJhWGhmcG9IMVFxMWJ1bHBlVk0K8rR1Oz/VKKBON/ROV+UeISvBPkeKRcqt
            C+GaNOwg+r70mnRu+rLeq+BWuA3njHcTSrIjzPnZpEcYef6I239p1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-08T07:41:37Z"
    mac: ENC[AES256_GCM,data:G5NyJn+G8yaszV1+jpLsJumNgWChnYDPkWVB7RW16k4+7nBc0MlmTyCGA1ZZxeTRhat2SBJdvKA8atYIwWBG60ELw779oX3XrATUuaKZ78LxcOQO6mDxg2zB2XTjwoDiMT/wZFl1OSpInHeAJRbyDqx6LgvmgH4lnYWQWf1Xur0=,iv:QTJ1yiSypDttX2cD7afcFuVtaPxfUD+YxrqLf0TmQOc=,tag:mL/PiPLJxfvwwEbC1l/L7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
