apiVersion: ENC[AES256_GCM,data:fKE=,iv:fYPr+KvwwXt8SAr52H0IvPkv4XGBH8jXU9KmYXKmH44=,tag:8iitusfH99X5MeGKeprz/Q==,type:str]
kind: ENC[AES256_GCM,data:xcE51Qcp,iv:OMVpH5x1x4BQZB+JXbfAgwR4f+SIGeRmm8UW9KGoNBs=,tag:3newRg1iXksS2RToGbNvKg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8+2t98uOOO/OKO/1wzSn3PAu,iv:LeF5OW8HH8B7eUUPuJaLJcR06kU2opQOb2mh2Haur0c=,tag:XJFr+lYDPWuLA06MfbfVng==,type:str]
    namespace: ENC[AES256_GCM,data:I9LijMrCK0A1kfEtLQ==,iv:Lj7F087wnoUYG76TMmWhRg3ycUhT85xeyXaobLxtFUs=,tag:Qvl2IRlSEoUdgM4floPmXg==,type:str]
type: ENC[AES256_GCM,data:MXDvPHJayfg9TIIIsdapniWtAamMHaS0O9H43VK/,iv:vmh2eB65CM2wA9HqDdtbAQhgchoV+IJe3mhzrZ86TGU=,tag:0u8CB7YyRqS4r03O2w+g/Q==,type:str]
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:QwPnfV2XtnQC7i6Cdg+OzmQ6T8p0+cRQbnbHXGGS5oFw0xeSZfGkAZowpMlty0surbJ8p0TfEHssDXwZzvykMLale42eDuJSyZsJMWt/VfG3EQojc6UZzbPYcs6pfXqGuBq+usFiPWJcR30NJVPrRHC2pMVZHF4Q61ZaagiE9rIfAf+d6Lk+ugpkz/2QIHGODaxCbTnYUbh+g3XQrwpYAmuUko2AC4uK1CgRkHPOrzhmWXNJqhLN347BeHsfPerzfpsittQR,iv:em/NrYT7vevxhc7xsJAsWvYYLOA2yrna9mIF6Dgbgh0=,tag:RHyUjIdgaRSryZ1GJLw6Zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVEcwY1Q2U0Ryc2JWdGVz
            Y0pXVVIzRjNaOTVDM3lvY3FlY3pkK1V2OTE0CnY3UElXMXNSQ0thb2RUMnhyNUFa
            bkZlWTJqZndZVE82WnM4dXBidTZoc0kKLS0tIGtwQlJQd2VXVjlQSTU0aVFmNWJ2
            dFFWOTRjd0M2Q1VOZ0l2ZDVXVkJvYzQKPVLE9gZOtvl1f9T83mRCPsaAvQhA96/x
            1QnDqADwGmXZaYWsLqzPCEZxSM2GU0Dwq1OFKlnFb0UGx8x4lh+ffw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-16T11:00:02Z"
    mac: ENC[AES256_GCM,data:oXxQUR+OWYSg7Lv/N4HxKUsX99NJSIWuK56d3+f6Ukg1eyXG3ScfZzZkYgULXLvpjriVrOPOrg5wADFGWD/opLOiyGgwjAyoK7MTDI3F8L4cVUKFQmD8zk8B7Z5JYJvQ3hw+vUbQ3OBgsjey6kF7ms4k71797U/ZpfdzkUtXUQE=,iv:eup1U1TQBJxpjjOy/FisqPCl0hK6Svuj0rfidRhjc9U=,tag:nY8jYZnxU2TpfSbFaoWI8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
