#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANSIBLE_DIR="$REPO_ROOT/ansible"
VENV_BIN="$REPO_ROOT/.venv/bin"

export PATH="$VENV_BIN:$PATH"

cd "$REPO_ROOT"

echo "========================================="
echo "Monorepo mise bootstrap"
echo "========================================="

echo "Installing repo-managed toolchain via mise..."
mise install
mise trust -a || true

echo "Bootstrapping Python and automation tooling..."
mise run bootstrap

echo "✓ mise toolchain ready"

if [ ! -f "$ANSIBLE_DIR/.vault_pass" ]; then
    echo "⚠ Vault password file not found at $ANSIBLE_DIR/.vault_pass"
    echo "  Add it there and re-run to continue with vault-backed setup."
    exit 0
fi

# Generate .env from Ansible vault values.
echo ""
echo "Generating .env from vault..."
ANSIBLE_VAULT_PASSWORD_FILE="$ANSIBLE_DIR/.vault_pass"
if [ ! -f "$ANSIBLE_VAULT_PASSWORD_FILE" ]; then
    echo "⚠ Vault password file not found at $ANSIBLE_VAULT_PASSWORD_FILE"
    echo "  Skipping .env generation."
else
    export ANSIBLE_VAULT_PASSWORD_FILE
    ./.venv/bin/python - <<'PY'
import os
import subprocess
from pathlib import Path
import yaml

repo_root = Path.cwd()
ansible_dir = repo_root / 'ansible'
vault_path = ansible_dir / 'inventory' / 'group_vars' / 'all' / 'vault.yml'
vault_password_file = ansible_dir / '.vault_pass'

cmd = [
    str(repo_root / '.venv' / 'bin' / 'ansible-vault'),
    'view',
    str(vault_path),
    '--vault-password-file',
    str(vault_password_file),
]
result = subprocess.run(cmd, check=True, capture_output=True, text=True)
data = yaml.safe_load(result.stdout) or {}

env_path = repo_root / '.env'
items = {
    'GITHUB_TOKEN': data.get('vault_github_flux_token', ''),
    'CLOUDFLARE_API_TOKEN': data.get('vault_cloudflare_api_token', ''),
    'AWS_ACCESS_KEY_ID': 'XO5X9A1W8AMHY3DSTKMS',
    'AWS_SECRET_ACCESS_KEY': data.get('vault_hetzner_s3_secret_key', ''),
    'AWS_ENDPOINT_URL': 'https://fsn1.your-objectstorage.com',
    'AWS_DEFAULT_REGION': 'fsn1',
    'KUBECONFIG': os.path.expanduser('~/.kube/config'),
}

with env_path.open('w', encoding='utf-8') as fh:
    fh.write('# Generated by scripts/setup-local-env.sh — do not edit by hand, do not commit.\n')
    fh.write('# Re-run the script to refresh after vault changes.\n\n')
    for key, value in items.items():
        fh.write(f'{key}={value}\n')
PY
    echo "✓ .env generated"
fi

echo ""
echo "========================================="
echo "✓ Setup complete"
echo "  Run 'mise install' or 'mise run bootstrap' as needed."
echo "  Secrets are sourced from .env via the repo mise config."
echo "========================================="
