apiVersion: ENC[AES256_GCM,data:vR4=,iv:gYF4qcig2MKuiYIYcGdycmg5WjxC84rARZWJE97XAS8=,tag:5klppmQkFderZ3ohJCWdtg==,type:str]
kind: ENC[AES256_GCM,data:BiaRbOYR,iv:NoRkzfyBZPtUfDA6i9GlbJzT1d9vAvDamj4jl/Ikzug=,tag:sdDWowy4BkuqftEE2Gb3fA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:drVNHgLiP92CIgII,iv:ZlGW7RwJsGO7CDrcd31L+HPxSyLv+JUTVGN4qbrcydo=,tag:X7UNVoZOB4N1IiFmz1qkpA==,type:str]
    namespace: ENC[AES256_GCM,data:gyPaKqN+Z++qNOVr,iv:WRMzWVmR3g709Pd9zQ6V9DtTVUBaac5wEPBs19/cu3E=,tag:L+6WmXWM1D/q8r+MvzOYzw==,type:str]
type: ENC[AES256_GCM,data:gVuYmlRa,iv:jmS3VQns1ZssC8LFJtpiMRPOUjvNAYTNOA8ebPsV6oU=,tag:LVnnPBZu1mZocsm+iLOfWw==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:IRK1RyyvpaiK3P02lMG25hff8jHBuQCflVDaFwWMGUs=,iv:dzfUG4DmtjfOBIABluupa14WHBHeytQfhWUGttbUNCE=,tag:hS50Pj8ZQHef7PEy7cFrLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndExrenp0SXRqTzBvUXJo
            c015ZXpLUC8xdDZMN2FiVGRnWVhyQnIvVGlNCjNoMzV5OUJ1ZEd2TzJuUFRQSDFE
            cS9ueHQ2bGM3S0hyQlRvUW43Rng1b2sKLS0tIHMvNmZpZTBYSmxSTElDanVUYmZa
            TkxDNTBOdENTaFBjbVF3SEU4dnc0SHMKdeNNxAN+BF8FGaugN1aq47IxFp2F1DpW
            sMCeVLK2w4ZAd8/o4d4bkT5KbUmTE0jWEgljVaFJFMEQQK2guvahFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-25T04:30:51Z"
    mac: ENC[AES256_GCM,data:hOXP72ScPJpuhlsacQ6oA4Zw0ploo+58UymmDKnc8kt4FB6HSsX4H4Sm3LDh9LFsgM2lcjGD+T9yH9anQpjKzmRhHPAqph0i2vFLkadB0iZyO4epTTsgJheBQL0OYpFHSS36rUqBU4B4f+m7+rcsgZNAGaxGDv8T9oM0DQYZ07E=,iv:T0uXwWOvvnlcZpZ2bb1m6fCBIV2hgdYEZnkLESqeEUA=,tag:uykkS7NtWi5EfxsWEpxQWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
---
apiVersion: ENC[AES256_GCM,data:dZA=,iv:+1ZAPsLBTLW1lH+IXyRuB1R0bT/ZOkwwcUOe7fbVgFk=,tag:Ct6cD2mklKIlEjxim0CfAQ==,type:str]
kind: ENC[AES256_GCM,data:pNW7tgPb,iv:ojkkhadax4pnrDafDsOAeqaKJHYXelhxeXuHWSffLhc=,tag:J1FE6LZhUQR+ql1VyXX3VQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:p/q6DvHouu7p3JBeSg==,iv:62Wjv+wkbZ89utDtxzkDAT1LycHNM906pd0T7RQfkd4=,tag:MBTs/8Y704e+dA6QzD/g/w==,type:str]
    namespace: ENC[AES256_GCM,data:m7Mq7DolotvdmFl8,iv:NhLVVPwhO4NbY4DViRq6U2mKt+Sc9AcNvSl8ek2K4fk=,tag:FKRYUS6MNN29ueBkLZi7dQ==,type:str]
type: ENC[AES256_GCM,data:efYSiVEg,iv:J1Ve6pRM54DoYJxLS9zsHaz5gGjMBQWyo6dIMjeSvcg=,tag:gRJHpPrpKwv1DlmMu7bRIg==,type:str]
stringData:
    tsig-key: ENC[AES256_GCM,data:lH8QhKZUgEgyfdpFZhcATcrY3Z3H5pOkWQZ7IkWV10DKmq7129T2Q3YUaKNLCBZoq+Qui5TRXrwFWItwGry4Nuh7KKSq1KjduJzAUt8eMFA734MFuUfQtg==,iv:8qYCr4DZJXwh2Ci5dZPUEtgVJ8ivIYsmriYxSPiDacg=,tag:cQ19DeCzRIDI5Fu8jswGcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndExrenp0SXRqTzBvUXJo
            c015ZXpLUC8xdDZMN2FiVGRnWVhyQnIvVGlNCjNoMzV5OUJ1ZEd2TzJuUFRQSDFE
            cS9ueHQ2bGM3S0hyQlRvUW43Rng1b2sKLS0tIHMvNmZpZTBYSmxSTElDanVUYmZa
            TkxDNTBOdENTaFBjbVF3SEU4dnc0SHMKdeNNxAN+BF8FGaugN1aq47IxFp2F1DpW
            sMCeVLK2w4ZAd8/o4d4bkT5KbUmTE0jWEgljVaFJFMEQQK2guvahFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-25T04:30:51Z"
    mac: ENC[AES256_GCM,data:hOXP72ScPJpuhlsacQ6oA4Zw0ploo+58UymmDKnc8kt4FB6HSsX4H4Sm3LDh9LFsgM2lcjGD+T9yH9anQpjKzmRhHPAqph0i2vFLkadB0iZyO4epTTsgJheBQL0OYpFHSS36rUqBU4B4f+m7+rcsgZNAGaxGDv8T9oM0DQYZ07E=,iv:T0uXwWOvvnlcZpZ2bb1m6fCBIV2hgdYEZnkLESqeEUA=,tag:uykkS7NtWi5EfxsWEpxQWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
