apiVersion: ENC[AES256_GCM,data:0TI=,iv:30wcDKG3YK7tfqBbLBOI8eF0axlj9Zc68eZ7sG4Ae9w=,tag:Pr4QT8YLNPSiL2OErmpaow==,type:str]
kind: ENC[AES256_GCM,data:KlaVbOcN,iv:trwEfZRhb0FYkEWLLSXRmfEJN7J5q5NhPE0MI53MqXQ=,tag:GUQ36U/FxRJ+/5UycBsDVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sZHw0IhlGeb6le+S,iv:yuJpWohZyWpiUKAlo4AwZl3IP2D8zth1sfVlFq+goO8=,tag:pTBiWIWv3qKo6EGmM3y/xg==,type:str]
    namespace: ENC[AES256_GCM,data:6WQXvcxzqI7VOfJl,iv:F+PseTAvd1o1kLH8ovziKOkucRKMWpH/y55F4O28VDI=,tag:Oautf33MWQpRRK9CaySs+A==,type:str]
type: ENC[AES256_GCM,data:Z6Dgo47g,iv:oOTacSdKoqwfMnODdNgyIn4kYjRSTLI6k/pO2j6qGQA=,tag:DcJNmiJowpawh7LG90YYHw==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:g4PLm30I+PJPF7lccUyPbS+9iKfjJ6GX54zSvcX3eX0=,iv:jccjojya7OG2BbhLJ3M7Je+7RRJ3xaJ33cv1mjHruo8=,tag:zlvOiZDj86it6VhONe24Hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNlFHUjNEZ2g2Tlp5Nnpz
            UjEvQUNURGJIV2dsTzlodmtZV2dDWjdxWm5nCkt5cWhBU1Rid3JGZ2pibVloaWlp
            YThHSFBBdVFWQTcrSmsyczdnZGZuZG8KLS0tIGNtN3NlaU9vTXkyYW82cndhalh3
            Z0xRcXlja25zSzZRVm5CWmVkTTFSTXcKKMxFVj0WaRnOKktPuT2pJqg6jH+BXoSV
            oLNGwDCfP72bEdC25/DKEhisBqZ62dW6ZEM6zUB3DP3683b9sVV4sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-25T03:04:11Z"
    mac: ENC[AES256_GCM,data:XpF/aJC1gFcP6Klw4Wpg8BPITMjglADTzTOpjNAO49zBHtIt1oxwO1TPtX4gotgXsa/cAprQI8T29H0MLvdfxWKhpR7tjzMc4qr84xQLC/W74hK3zkbFkG3moru8iyG98dfJz/qgQtV/e+jwazbuih03HbBD1U9YvrfwibZaKcI=,iv:AmcQSJs4hBiAtRsCJ0bjc13OQQlhRksuIZ8PDUETB3g=,tag:uHEeIWsXEtDbA7NJqKmuLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
---
apiVersion: ENC[AES256_GCM,data:cbs=,iv:hJtZ5CVarpTytx00y8sHsHF3SFe0ZPjn1WOZT63e3g8=,tag:nKCRCDuuiCcHCm6fYUoj0g==,type:str]
kind: ENC[AES256_GCM,data:aIVIQzZ0,iv:S4nGUset4V77Xc1qLAQLZAyMDrNW+wdXgRzJ0XZs72k=,tag:zKN0Pfc2UklrGU6mZcREgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1DY3+M0OPKqnMfo0jA==,iv:FO9OGfO9L2EeK2tm7IOjrIZp0IJ9RDsjPydh/ySSHQE=,tag:+M+qqGVmKO69O9aknlc2yg==,type:str]
    namespace: ENC[AES256_GCM,data:6iqH84HhDjwJ1j+A,iv:rB35GNkIqBO/9Rn55JQADRxc+CXlBaPVQWxwENggxVQ=,tag:58WgmO0WcF8KUNlwzqUd3w==,type:str]
type: ENC[AES256_GCM,data:ORwhous3,iv:KXw0lUTQwr2IT/O3SXrd+YDY73O7ku6g/NIfPibTins=,tag:gL/79P7O5fDhdG8XC5FxQQ==,type:str]
stringData:
    tsig-key: ENC[AES256_GCM,data:NX4Jx1NBjmpzlRna/T5dpbeFfjF/T9HZJs+JC7sEm6zT4wQ2L+u08yPubX+sDZaOwSumT8QSsSkqWBel/wgGpyfhxIRvXfedAi/DMkbofo26gKjEKAQYsg==,iv:d6uyt1nG7Ukql4KZNSSmqfPIHwulM3f+skvSEgZpC74=,tag:yUHzP2m3dzQA5M+2mA8dYg==,type:str]
    saikat-dev-key.conf: ENC[AES256_GCM,data:0QqB4fkAVGV5tuTplg8bo/xSIhByZY2CZncfOJb6hZRrURCjxy3ZEwXyt8BY7t7sahx3YbPMQIm2uBpjHbS6C1YzeJSguZt5ZL48ffxGyYLEi2Wtg/DYoKTS4lhNMAgBjywOka+i8MQvUl6GabpbqJQ1u9+vyqk+AMLuMvUJvz+ysOahPc4/Bwyll1xaLKLMY+afA0HLpylXPOA=,iv:0fNSasBtUkuprM5hQ3yG+1FNV9cVcVKb2ZfHtPD/5fg=,tag:jbcc4C+PN/e3faAWhiE+HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNlFHUjNEZ2g2Tlp5Nnpz
            UjEvQUNURGJIV2dsTzlodmtZV2dDWjdxWm5nCkt5cWhBU1Rid3JGZ2pibVloaWlp
            YThHSFBBdVFWQTcrSmsyczdnZGZuZG8KLS0tIGNtN3NlaU9vTXkyYW82cndhalh3
            Z0xRcXlja25zSzZRVm5CWmVkTTFSTXcKKMxFVj0WaRnOKktPuT2pJqg6jH+BXoSV
            oLNGwDCfP72bEdC25/DKEhisBqZ62dW6ZEM6zUB3DP3683b9sVV4sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-25T03:04:11Z"
    mac: ENC[AES256_GCM,data:XpF/aJC1gFcP6Klw4Wpg8BPITMjglADTzTOpjNAO49zBHtIt1oxwO1TPtX4gotgXsa/cAprQI8T29H0MLvdfxWKhpR7tjzMc4qr84xQLC/W74hK3zkbFkG3moru8iyG98dfJz/qgQtV/e+jwazbuih03HbBD1U9YvrfwibZaKcI=,iv:AmcQSJs4hBiAtRsCJ0bjc13OQQlhRksuIZ8PDUETB3g=,tag:uHEeIWsXEtDbA7NJqKmuLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
