apiVersion: ENC[AES256_GCM,data:73g=,iv:UX922dZMiTktfy0psUErDOhFITByp6eF1nbflG8zZTE=,tag:Hi0wn3SJKKTi+4OBBQpmQA==,type:str]
kind: ENC[AES256_GCM,data:MxDFOuLW,iv:+EDoVjsREDKtdwwlpydAVqLQbdWdibAPpRSrcBOph+A=,tag:sI1gUrubTmctSo51McQt7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qpdy+QN7EGkprLFW,iv:obpE9vGkRtDcEJ5fYsd56XO9ghyPp9f83tCFTOnKmms=,tag:U5h6x5IbRPhkb5a1Rp7WFg==,type:str]
    namespace: ENC[AES256_GCM,data:0abjidBXQMuj+Tsw,iv:zFN6O7NsYFFY8Q/+9B1NdyxfWQEyA/eYzoJTGkvLTrs=,tag:Xo9se1xKQioV8wWqrWP2Og==,type:str]
type: ENC[AES256_GCM,data:Tis2FvbL,iv:u5NiI5dBLOfIM/4bvHeKYqmuMTaKiTAHkKWJbaBmjMI=,tag:054tFxrc3aioFoLHPHRF6w==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:1GWkANBFHdtwX4j4wHXW56J1xc36kn0HuMux/doXbOY=,iv:5REXH9gHQyX/oFzzzfkeyT1Ao/rXlgQMEp1mFBYm1Bw=,tag:LVqJ2Mj/bG20ddjkPaxf6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSlIwWFpQM3QrYnF1MnJp
            RXd6b2RMSm5ldUVwRXR6bno4MlRWeE1zOERBCmwrajA3ZDU5cmhuWitpcG5GSFB0
            WFQvTHgxQlRJVjhtSXVmNlR4Tzhja00KLS0tIGpSU1VFWTlLeWZkVmFYdnZJcGZW
            S2c2eXBVanQ0QWlXTDFaQTlmQWR3eVUKa23FXYohvscbzw8t3DD86UATtMxjLgPv
            GBNet3DFdWUxmZp/Q/F6xN5JdYPL1KDxaC9++K4DzX6ylcVZ1faRxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-24T04:32:42Z"
    mac: ENC[AES256_GCM,data:0Mel+wLPYTHfKqCz3Q1MxAXMDPk2em3CSIDtF29ThujswsEqeM4tvTZ57WxCXI939k0uUm2Gtr/kt3RyhxoH8QHqfDugLq5w3nQYNnAUjKnO4JZ0mlGsdU0x6ugclm7LYS+nsqdikbl4QOzc1D7lcVgXSfrPIMZeB9eQ6qSWMEc=,iv:j9osmMAncLpLaJnmL5tRYad2lFGSSnii1TSzE5uc1u8=,tag:RrMDep8yl5hdePhq0Ve7yA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
---
apiVersion: ENC[AES256_GCM,data:gQQ=,iv:1V8MH5lOKqO+9CctXlIRKfWx7KJVZT9+XQVJL3yXefI=,tag:tz1wcthHVqe93kEJvjFygQ==,type:str]
kind: ENC[AES256_GCM,data:ath7KzCL,iv:QuIblwNQPW28O+G9TH5NQ5ilS0PozBxo1jYuTL2JXrY=,tag:/i7AV0WqAKZ/RZ/fcrgong==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ea8iCMCKOlt1GjKR2w==,iv:Y6C0UejgvFw+s7E8vEK1JXAOl3DRG3TJg7R0vCTa/q8=,tag:R27nLg0s7D218pKNHWoenw==,type:str]
    namespace: ENC[AES256_GCM,data:NgnMIVHwkFmPhiqj,iv:RmGXMK0BNIny9PR+5813HNJR2k6oL4wsNnWWZvnx5iE=,tag:KFfAm3cgZJ1HgPpXXpAIRQ==,type:str]
type: ENC[AES256_GCM,data:7vg/seII,iv:g77FXWPbTZkvlFjM5Hv2hSPdfYUtS0+YJ8MLb+6CQ90=,tag:9F3EXPqVWY9ERCAaN7i95Q==,type:str]
stringData:
    saikat-dev-key.key: ENC[AES256_GCM,data:RYiJ1mC3xrzFQsBlmn6yAhte490SljRhy1lN6ySqW7/INrC4rJPFpMIhK8yEMVLAXU9WDZlIQixSyxbhfN5R4lQRDKs+7DuN8vEcrXne+tf+ATKnSYHjx1CEMHny6GbQAQ1tIR2aaPTO/g1GTs8oY7Hp0TAgD0yYpcXjCtKlgo4Gg2NCAHARB4RwF9Sd52oxOb1gHbSyt7x4hFY=,iv:cj3gSfOPbQ1hp6bOdmztdvMTdbmAct21LWg2Pc2ESkA=,tag:llGMpI7Su0rKea7DHRc82g==,type:str]
    tsig-key: ENC[AES256_GCM,data:rk7umQbpuyyn582Kip5/gnVjqsRUzfWO6blP8tszYqLYDBqUm03WmjydoFRwT+uOtqogOSl41ars+R0G5OYPlJfNkZKKul8GeAdvCymjaUVEk+5fWTwfgA==,iv:4QQDMsYA0G6ywyr9TNGuMKYf5hthLjIKF29DbSOa2uk=,tag:JigkvtmcM5+xkNhEZWw7OA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSlIwWFpQM3QrYnF1MnJp
            RXd6b2RMSm5ldUVwRXR6bno4MlRWeE1zOERBCmwrajA3ZDU5cmhuWitpcG5GSFB0
            WFQvTHgxQlRJVjhtSXVmNlR4Tzhja00KLS0tIGpSU1VFWTlLeWZkVmFYdnZJcGZW
            S2c2eXBVanQ0QWlXTDFaQTlmQWR3eVUKa23FXYohvscbzw8t3DD86UATtMxjLgPv
            GBNet3DFdWUxmZp/Q/F6xN5JdYPL1KDxaC9++K4DzX6ylcVZ1faRxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-24T04:32:42Z"
    mac: ENC[AES256_GCM,data:0Mel+wLPYTHfKqCz3Q1MxAXMDPk2em3CSIDtF29ThujswsEqeM4tvTZ57WxCXI939k0uUm2Gtr/kt3RyhxoH8QHqfDugLq5w3nQYNnAUjKnO4JZ0mlGsdU0x6ugclm7LYS+nsqdikbl4QOzc1D7lcVgXSfrPIMZeB9eQ6qSWMEc=,iv:j9osmMAncLpLaJnmL5tRYad2lFGSSnii1TSzE5uc1u8=,tag:RrMDep8yl5hdePhq0Ve7yA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
