apiVersion: v1
kind: Secret
metadata:
    name: github-ssh-secret
    namespace: yral-legacy
type: kubernetes.io/ssh-auth
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:ZxCPlyHfJ9VibFesiYUTKxkXhzXVZUbrxfJ/ZlJev3c1EQzHkzyUTPwK2r2acc4TwqYed+lC2VwJczGVBTBdONNysOLCGVd31j7dpHaQlZNId3Hiepgs4XAeqYYpHBLjJMTaR1Etec2AWZJjVhheGrDaXN5cbYmWcVTRi05TUehJ89s7++LZeH42+FCA9wOE/pMwvRTP881aqanUsPAcDOyWuwD4KYGWaYORp3bXzTnzYs/0733BZRBzes/4Bkgw/15t282Cxv7GP1STBWPd3AsdcLEl6mGlF4W5CPqxYhkeNFtQ3FJI6wnmvJHaDFeiH7OuEdC5DWkJ+Qub1tRV8yy9YRTrh7qtwH+HqyKvUVgxbbJwmigaiAzJGSFinlf1+tU7U3szEUqAs3eKpuSO4Nh//nqBAyizkkcT2T1IEJfAlmGy+yvaQp2yZ5t3N2jC2WyC+GKtHpevhdjJ42Dyy6eAnLAlvDjX6BStHJ60m/V4kD/Oinakx9+bYmSVvd+bvGT1ugart2NIx0VR22Op+mH+q26JT4RG7thyVF6JtFbDdAqX,iv:brggt260oBH8XdcTRXGOIrOR259707fXxVj7+8FOlxU=,tag:FyZC1gPguepGzvAyqKnxmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTm9CR1pXK2hOVU5IbHVS
            c3M1MXZLeVBMY05MemFNL3M5U3pkYkdBMkZBCmlWODhEaVNlS2hrQitzcDVybFRM
            VVZtbnBwMGVWUGFTWit5ZGQyOWVHd0kKLS0tIFMva2h5MkQrc3hKUkorN3BIOXNw
            dlFMVlFWNDBYSDZXc3M1WVorZU5VSFkKftHOVHVJRHUoDRV/0LYrGkqMpDoM5RuB
            RR2BpEJAGiio8mipBlDaHY19oCRxy8qPROyidiWNLpiOy4fkNOJpuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T10:18:41Z"
    mac: ENC[AES256_GCM,data:ClF8DbGVTiHFkOsFYxLwm5a4kPlw2JNUCa/qS4y/+rgMlNPgvU4xZtd/U4TLVfrHPBQv5FGU09t7kyrBybzGHPPvHdReolLEVW9roVbOIQ3W9UfjuLsuO+99ChyXv+8AE2vDDYo5nOxBVyaSIpPLxYe/dAd6uIqqmV6bYXy1BRs=,iv:MNWZDGbYbJYTk6OWz8F+lt1KDqFiznn9VuMYtVBvkE8=,tag:ZzMjDiXvS+iXVrg46eBVcA==,type:str]
    version: 3.13.2
