# Harbor pull/push secret for yral-legacy (robot$kubernetes-access).
# Recreated after Harbor DB purge with push+pull permissions.
apiVersion: v1
kind: Secret
metadata:
    name: harbor-pull-secret
    namespace: yral-legacy
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:gtbOlP1BkhzaFQi6v1h/h7umfnI6vQFKs1FwyxLW0KVLhk1Gtnbf2cczknD7WACAoy7qsA5qxG0w08u2NJDzfRrhCMaSOHJZd8BGuHF6OTtqOpAcmly3mkBU4opMLutrIg48EcSRENzBUTpfOrx1A8h6wPCWad/Vi/hP9tujcX8Act5LvA8N80BI36k5yhRHVSZk1bytrzsSBszHfy/j5KAgFnzNI4yt8j2quurrXS1qSVtZTtpjFkoPu0pmeIGR/df5duPRyUw=,iv:eKBC1F0d1aoMmJ7bDLb+TfkoNwIX/zUqkYlF1v9llmQ=,tag:X8U+C3pKQa4k5Ozj56KSTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN1ZnMkJveUl3SkpZWnNH
            YVJDUXVVM1JFRm5oOGRYTEVOVkNwK1Q0RFhvClpDQ3N0QU9XMG02WXpvQjhNd1Y5
            N3g3dkQ0YkErRHRrMGVGeGdNY1J0bnMKLS0tIGRQcUYwNS9sSnZtekpDRCtXL0lD
            MEZuaXNKbVZXTmxYQ0dBcW5rSkxHMFEK+4RSOh6do9BiitsXhBQ6O2QljlB4GkGZ
            kbqLTvY13Vct0BmIIBIvlwIMcqbHy/Tw5EvkUhejATmSvq74VhXxBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:52:27Z"
    mac: ENC[AES256_GCM,data:sbfzenS7xgAwtzskDNlwfL//QXYFeSux+kW1/84xGVZJcaYehkFB+NzCLSbVpNR4kvtDSzrv86LFBvBidP6Y7t/iP2DDpVqCB1pjvegEE6ZUzG8Oq+U9cODYs6YC66ElXOCHWPWfuhGVwaKs2S1lMxEdWu3qmOob+AIhDDV7DBc=,iv:36Ugq0aXlGGnldKsothl7Lauyy19hAL/vSp05DkvqVk=,tag:GUI3qMTCt74EH/gGXzcMTw==,type:str]
    version: 3.13.2
