apiVersion: v1
kind: Secret
metadata:
    name: harbor-pull-secret
    namespace: yral-legacy
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:E1qHc7WePAMrgq4pKoU2jKh6GwAFkWtkkg9ja+wi4p1iqrd9r2ZvwV/M70U+pRzJTNHHkNilVd8Zv08oW28ryqjwcKd+i0KTNqgXe6vLPJ5wu7JDrpngcd3SX/FuS3Ryi1mpMdveUyTfanMDwA+OS2ZVR3kFvW7j5WayLb/jBSPOYC/h1fITomyDoJ1SWtA268whXcUhenlJEOeJEQPnvit2SHPjp4zf/og53PwPSzXfrKWjIKVd4pKhORWSBAopjLrI5P9AbGY=,iv:niMoWU/8h97ipYHO4hNRpD5gpMd5JecjAttsNEQESPQ=,tag:UY/f2Y2fwZBDulw9bGMktg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NjhkLzgxQnpZbmdJNnY2
            WTZaZzlaQmNOdnFpOTlqblZERDAxV21CWTBrCjhGNDNNUXJacjFtc0lDTTZhbngx
            Sk92eGt0bm5yZFIxS29QTDRITXRMN3MKLS0tIFVQRXFuRkh6TCt3ZHdwRDFlcWpO
            NVp5bzR2SGJMajJvSGE4eTdyS3RRblEKWRdOdeDoL9NneHaNpg7T/Jq1ZVbzg4w7
            ZcA3J611Ouw3CllATvD+jfPkhlcdBX0SswHvpN8DMdBtuf/2GAnViQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:41:04Z"
    mac: ENC[AES256_GCM,data:+tKXOSab4Srd1wDvhwp7FevgjGvTCFci/UAZLf7e7wZsHr+JnvfXVbrfm1HfEOOtskWSpxpIu1W9JGpGVngtfiIb/BRgGLrLmFnOK+VELLcsicRfjQhP1unllMYUpprK1nvVqt5Fgb4j6iSAJOr5EUEIYH3Nl0m5U6pa3xiaqqA=,iv:4GG9jMOFoGfDscAdVb/48nfqdAfAL62vLrOjLnZEBTo=,tag:XUD9WjN0LQo/gaZ7Jaj7UA==,type:str]
    version: 3.13.2
