apiVersion: ENC[AES256_GCM,data:xM4=,iv:wofQwHhonF77Tr+OusNKuorBKEqA/wsZpUv75gNPRyE=,tag:sqcv5G60nPYAb+4nFdHxqg==,type:str]
kind: ENC[AES256_GCM,data:Q3SHfsfz,iv:N3iSclDOC0bChi7oapVAIJE8vucxL2+5yVbDnWBO9kU=,tag:ftVdl2+yIhyynp6JQx5qVw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pyHdCREW+75CMfpByFnSdu8mPg==,iv:SfCtW09hEPp1Re8nZV54XH+3euLLo5Zlut4Du2hiJxc=,tag:e/WUC56hcWCwukB92exioA==,type:str]
    namespace: ENC[AES256_GCM,data:R8Vq5BA2eCXR7Sc=,iv:CIMb+tAE2sAlU1Ok8XEWrv/8QK6Otvk0qGQzmRHOr7E=,tag:7PYKKceZ2zTJiRDcAMdG7Q==,type:str]
type: ENC[AES256_GCM,data:si8qFa9V,iv:P2C30L8w0j09n05G9fVkTyfN/JzTME/8Rt1M0wJ1GwY=,tag:bV7CZx+KBT0etrYT9nGL7A==,type:str]
stringData:
    COOKIE_KEY: ENC[AES256_GCM,data:hR4qKlO8Q6YXfECA3//hVfaHd+Hr7BSVXyoyA/IX+xoMiynz94C5kq+fSZKPl2LULcbhCA6VwaSk6FA4dDmE7q6Rgxz/IKTyZXWqXQ/q1BrsutQx2WBi0OYWSpoEu2e23/EA0s5bAQYGqZJru4DWKWrFnCsgaZ9JEIn0FU2awDM=,iv:uUNUbQ/oGBjqBlbpvTnPtgJcySLNAbAWLSMrFkcrg/w=,tag:tdApIu5kf27fbMSMxSnbGA==,type:str]
    HON_WORKER_JWT: ENC[AES256_GCM,data:wrDwWM73u7Np5mpu6F8pZGltHA==,iv:F3viMxvwR76W/tCJBICIpj4LcBar3yupLNSHJY1YBZk=,tag:sJYZcbvzUu71EcV8JRDxdA==,type:str]
    BACKEND_ADMIN_IDENTITY: ENC[AES256_GCM,data:J61i/S9rct9ZFWq3wqrz3w9WTw==,iv:NrqIua7eh1j/QW2Wupjk4NBcxoOVSLNh5CHEWer0Jxs=,tag:5Q+/No2A884WadPkrS4mdw==,type:str]
    CF_TOKEN: ENC[AES256_GCM,data:+x8ctyZjX9wxf/pAJo2emGQaXA==,iv:VWl26Rki5PWyvnK5JYuyHH24VPQXHYFQyxW5gnQ21Nk=,tag:jG22jkvm/TyPIVy0JoL4Rw==,type:str]
    CF_ACCOUNT_ID: ENC[AES256_GCM,data:b2In8vA9Kt68MrRwsxsgL0dyhQ==,iv:8yuh3DEMbeiHRBjHd/KWm7dpFFRsrmhCGqYJnGXmz1s=,tag:S8B5KkolQNYPF/ao1Q+5KA==,type:str]
    HETZNER_S3_ACCESS_KEY: ENC[AES256_GCM,data:UL1fl6uyAPJB3sIaQa9wYcWY1g==,iv:HdS2PPwDmCNzggv5ipttpS4TEKxfC3gc/IgIkqh0cP4=,tag:KCeMEL1zRrhLBB/SRIQsdA==,type:str]
    HETZNER_S3_SECRET_KEY: ENC[AES256_GCM,data:TbW7MFfVePaavfprEQCQM9q6Kw==,iv:vx04ilLlQ9Ijz0z11aBekhCLWy9RrL9ma5uvt21k3CI=,tag:kgVijkAQXvh9IeP6/5Xt/w==,type:str]
    GRPC_AUTH_TOKEN: ENC[AES256_GCM,data:ljUmhOYAvwyA2eqPodK/oJBMOg==,iv:70LmgBv8rKlWD5qIe4Bd15IB9/9MH0p9bRAqnsRr5kQ=,tag:IdAkAcU/mIhpZ8AU/Wz5gw==,type:str]
    ANALYTICS_SERVER_TOKEN: ENC[AES256_GCM,data:bvsWO89gactwShaIq2YC9tHAnA==,iv:QPXOxlh7gY/ZIaqsuUFoqzmf+VqZH4kpG8U+XyGoFMg=,tag:0Z64vUngn6lojOK+6+tVGA==,type:str]
    YRAL_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:neaV3IbVgm74hElr48bjoJWLRQ==,iv:TBBPAloZe1qXiIASYKEjuVUceuBOHE69yq7Rz7/gOK4=,tag:Aaj10NgA8pRIlQnGSkbUPA==,type:str]
    YRAL_AUTH_MIGRATION_ES256_PEM: ENC[AES256_GCM,data:FY6fVQ97QoGW/ijmSQOiG4GwtQ==,iv:fqZOXG1UN1A4CCJTNDnm8JkfK5ZlwB7cXmrQbHAeCTQ=,tag:3m2MqbxeWnn6Gh9+UjpyXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaStjcCt0K0EzZkJGdHlV
            OG8wNWFtL3pMS1ZQY3NtSU1YYjZIa1dxTmhnCkc3NmhxcWpOZWtQU0FSa1U0N1hT
            MzlDK3FlMG9pQXNJUnRhaWgxTjdzWjAKLS0tIEo3S2FnRFdTTWZRYnU3a0Rxdk4r
            YWtwUVRseVZKTi92K0RMb2ZiWG5ZamcKnU4rvdqAkmNKqXieALypJ7AXAS7tPcel
            l+yEXo+fHuSJDrC8DWUrLOpXnDY0/SxseoRgv7Q475sfB0jIhvo72Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-15T17:50:50Z"
    mac: ENC[AES256_GCM,data:w+8glnBp/+l4zpDXCLtrBNZRxwxZDBtQN+oI/hNLhOQj0PvOSz6CT2agwfNyYQ2BtMZZ1tjICX+gdp16XvfrdpmCuDYY18Ng5fae+XL8tF3QRMafg7DFtYBaHN5L4kG4zlxpt79Wb+3NHsZiOuQDRiN5u47EJVJ2AT+Ni2RjZdg=,iv:xsqnzXgGTpS6MJm889WvoC2hlgBdWDeDe5v1s41jP8s=,tag:b3k1oQ+RR9AYa0Tmx1gg4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
