apiVersion: ENC[AES256_GCM,data:Ak4=,iv:AgqLH+qQEofSINktwFL58swCa5tnD4PsOykZtfdCkAY=,tag:qqNq7AhpubY5ROlcS65fpw==,type:str]
kind: ENC[AES256_GCM,data:VUBWI77z,iv:dICz8AEFdL0wSw/Y8pWgdQmvq2WkmtyyOclTMP/dNBY=,tag:2ms7TQi9PUa+4j/sgQFKpA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4XaYidjoUl4qEMBjiPYP6gNFFg==,iv:NOujp5Q8bH5C+LrNKPqeKC4CSQwWUwO4QLMazBj57e0=,tag:zkz10Xno6LVf7s5oLEJJkg==,type:str]
    namespace: ENC[AES256_GCM,data:Y2tqmEaVkaYmQL4=,iv:lHHiKSAcQDpK+xYESl/8Di7XFqYEx6S+PNGCZhlIEzY=,tag:cfxyb1ksNgsrhFI9GPjDBg==,type:str]
type: ENC[AES256_GCM,data:vS6ycOw4,iv:5Xzy/JTlDjnitSS+Uk8K1hRhLi1BCyPRDmfL7875mto=,tag:zI+bwTWwMYlpJRTlSpFDeA==,type:str]
stringData:
    COOKIE_KEY: ENC[AES256_GCM,data:D6JrMH0n1vSvXlEqFz3BEuP+q7OqYEoUD2bz1BTmBJ/4o3yvJJ7UbVmf84Ug0B4w7AXWOMzo09JDrqklJClEx0vnON5ywtcnhCCIllBmLpkOPGsfLOd1ya9pEFHGuJ0IQg+sNZT1RgJ4mj+M87pveiIT4tu3MgNrRmWFMSmhZjg=,iv:nATiuoI0ML9BWbsivIyZcdDveAb9t0fQkuZK3psUO0I=,tag:Qh94xyOdtLVrlolXItscEg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:nY+L4WMVxpVINw7xqpCbGL4ZXA==,iv:rShTNNRugLjxOykfqix88bqj6Zv1ACOCokqfQ9NMw8Y=,tag:ZXqt4mPC9tt1VDiZisAl6g==,type:str]
    HON_WORKER_JWT: ENC[AES256_GCM,data:sKnS+AEjgY8iVl84G3uLx4S86g==,iv:WgtTIw2Gn2VaBYPYpo4fbR95J1lPJP7OG/2aZwwhjsM=,tag:6hlGARrrCWUIixShjZE+yA==,type:str]
    QSTASH_TOKEN: ENC[AES256_GCM,data:n/SxopPRqIK71B0VLihSgWB4MA==,iv:SyfmIZDJC54QlKdDWFhi8EAQCbDLpYfvS7IqfBUPjCM=,tag:GBdnsHsx7dFiVi8hxWjklA==,type:str]
    BACKEND_ADMIN_IDENTITY: ENC[AES256_GCM,data:SdA5TBl9hL2EtP5F0rLZDOIQUw==,iv:Uc5z2yMYzCSb6rNNmqBNOL4jOQAzNOgDY2oyyOVVOY8=,tag:3Rr3NfrQUl0+J92TTO7etw==,type:str]
    CF_TOKEN: ENC[AES256_GCM,data:NuSny/v7/Zw+y7CL3nsq2smv9g==,iv:huq/poNarMvV5hrmNzqGxfIZbSk1J3Xst3w+bmolqb8=,tag:MZe9zl+YPrxCE8eAuwZa9w==,type:str]
    CF_ACCOUNT_ID: ENC[AES256_GCM,data:K1DADgoM/8zzfIc7nNECKHjrdA==,iv:siYFoUnwcxq/26/NATsqIp2SZBzx1znE3pHN9dD67VA=,tag:J+ElVNFqEz9VLggAasPNOw==,type:str]
    HETZNER_S3_ACCESS_KEY: ENC[AES256_GCM,data:fv7Qrgf9+6Av1vp6ODU7+t34wA==,iv:OQRClwiv5FWepzcBREALymosq7uea9MMcWlqaqKOGnM=,tag:LOeQDgPH41by+yAxBkBPUA==,type:str]
    HETZNER_S3_SECRET_KEY: ENC[AES256_GCM,data:LScg2a9eac1vk0PQHA7DAZHuog==,iv:dYfiNJfv+BnSwq7jiFeGBxEIDzrFUQd0Lc+Zv5K4uKM=,tag:zoAfynv8IqM7T5N+QRczBg==,type:str]
    GRPC_AUTH_TOKEN: ENC[AES256_GCM,data:AEqck8e78p6h4I+kPFESMC+/XQ==,iv:C13iwNQSlnrQlwljzF8BDt9PYmtWlpqyFN2CuIiBPnQ=,tag:+aye8wBEoZu7i5Ns6nnKhA==,type:str]
    ANALYTICS_SERVER_TOKEN: ENC[AES256_GCM,data:AKCQtcNsCXnnAuaSXlP2GvsIpg==,iv:0jhTqvW780Hbc7S8mtdJ5fFFl+JYqX0MVdJ9aXLZi2A=,tag:+2GSQSszKNy2fFPDSNfzog==,type:str]
    YRAL_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Yngkc5RsTBFIQI9x8fElfEdWfg==,iv:fvnT+qk+PV13kPqqPt4c3AD+2E3CYrAE5ktfHsWYz3I=,tag:mFz7/3A5INAu4EiReIO0wA==,type:str]
    YRAL_AUTH_MIGRATION_ES256_PEM: ENC[AES256_GCM,data:y71btWKvIUfO7NQDhcTQ2Wdgvw==,iv:66WV6TQExKF6cJOh4H2s+91xjIQ6qdVuq/Kco9l3SIM=,tag:QR5iIEDBbbEaj3maG5Rokg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM3lESnlqaDVGMFArTHJY
            YzNqVEJ1U0hETGxoT04rOHFSZlBDdzQ4Z3pvCmJoU09uMXpZK1lHNHF6T0lLOFNN
            TjNzRVIyc3k3c3dRRXRYMWZHUER2aDAKLS0tIGc1YStMeHVmS0d0a0RsZ1Y5WDc0
            WmRSV2VObElWRHlrRWxCekkwY1d2Q28KhtdD9hjslYRJsYzvXsvPf1YKBkf0Hw5V
            jO4g+XMur7/au+X/kNOs/oz+6LTSJF8X6a8UwDRnEIcWjjjtPd9GWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-15T16:46:13Z"
    mac: ENC[AES256_GCM,data:ErbugdjAUVk0axzezaPOaWS1nzjOs45pAh+EM6cZMMy/5EeUBIl7CrVOMlaWGnVIKEhQGjkDd6811aMW/ADCyd1VHcjpQ0+XDADSn4WHnAb2zwuxgsotDWSNl60/r/k0OMXDOB43tRi5Ae50msrpkr6FumtisqDHRZpjq4cNxRc=,iv:jITOyTVlhIUUeajpHQ/vBTt3bn7Mf1o2T8IvyeX4dDo=,tag:dPxkMHORUOZ+1O2ViwASDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
