apiVersion: ENC[AES256_GCM,data:iZQ=,iv:4QuoBgCzVeulX+OCji/n68mD2A79FNgEoQleGMdx4mk=,tag:pgbe6o0vo6OTvjc7XFJ5IA==,type:str]
kind: ENC[AES256_GCM,data:E0zAUsPd,iv:UnVa5BdaD+9bGUPB38nGUnZxZLFGPSMdZvYoFk37xdg=,tag:DRGGrKlLtEHOZjv/cmsW6g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qs/c1sNGS9DUjsk6W2y9x6ldBg==,iv:yUQNO7doUviQptQ+WbuYyYihyb9v2M7fdFBHmPMixj0=,tag:lPNgzgOG+uqioRUFa3wMAQ==,type:str]
    namespace: ENC[AES256_GCM,data:USQJGD2cZWavertZmg==,iv:b/+TKAqrls+x7aAi6n7RjQ8FiTxe6eeq9NTjUsR/2iM=,tag:Mp16LN3FWrBI61FIouwixw==,type:str]
type: ENC[AES256_GCM,data:pHwCZDc5,iv:4jfxw0vKZR3l1YNvrKkmd4A+XDBQ40oq7V9kbgXMDS0=,tag:2cguMJRh5JANmjTre4IXew==,type:str]
stringData:
    kafka-connect-password: ENC[AES256_GCM,data:gFUriizhPUCwocByBVq29JuQXUGJXgImk+opfIbh9//tkWXzclS2xRnDE/4=,iv:eUxPIK2+jtZw1xmjiYcfYyfvZHZeAGRyGKOfLRnrJzs=,tag:Ld92v4S+UZ7Bql+Paz6mew==,type:str]
    kafka-connect-jaas-config: ENC[AES256_GCM,data:VEHG+ogoJHWA1l6AoQq5btcImigW8M7Eq+aItHulXGWtqRa0fJS5Bs8zZX7XLgG1JZkComkdyCFRvjOvKz6QldHTJeM1NoZ4DZc0Nps2vgotX/pPN9F1u3sHTxjpL4lbwBvAYjFAzMTwHqOrQfgKImXSjvAe+57Wxn4zF+z7fJebWyYN+De89Rig11YBiOKCppU=,iv:c4IV1OlyR/ftMg5PZ2Bx0qVExDGCfCPTlN6mZx0vkgA=,tag:G5kNJHmmgd1hKaO03NsIiQ==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:JAut9+Te/I8LYQ9rrqRySgjJ0mo=,iv:myFE0BxVK8I0q6yinP/qwmda+kkegYgDFJTPd9ZjkBI=,tag:YdBCUkrZeDLjBEDZNBJWdg==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:KJTvSuXjfxKETp0YkEYC7FCWirNrSJ/cQoA/gK9DaZirkcCzTsJibA==,iv:MeGmpQyJ0PV3BOG3WgqavkMz6cln+r0MDp8edZ6uPAY=,tag:lCyOcTMxSM+6QiYe9DDlCA==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTytZVmhGdHdZZkFwR3JU
            aHVTYW1wSzMrVUpmTlZHcUVtWldpcWRSUmxJCmFvT1R2MldwWUVlU0NXeUo4SlFi
            ZXFxdDRrZjJ4TXgxditLb0ZMNXBsWlEKLS0tIFQ2cjBveGVQeTBJejdMMjhZTW1E
            U1M2ODJ0N0VUWXBhR1d6cERpZXVXeFkKh1mXcaG13Yo/Hn/8glCaH7mjP+FD3/NY
            tVs7CVSxkTBUQHdFupwe51KOv6EA1cPGO5OcBimvg6PoUerfNBy7dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:23:41Z"
    mac: ENC[AES256_GCM,data:tgXRNheS9zoO9dTPP/WvQRHk5p3p/HZzoUbOt+X2Aw4ifw6Q/X+KqPPdyf7RRvR3sPH37+3OnymOc5CgYxmNl75gbaeV75oran4hC7l+4/HgDDraiGymVy0n3ATfV4u/9SCpH6m03sYwhYfYCBBLpKvmrMglSe2FagLNIFyO/pI=,iv:ak8HI0eqE1IsEoO+QmjpzPu+lKP4JZRFDHMLlo9uZg4=,tag:uLrti/dinSn9U4locWnFKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
