apiVersion: ENC[AES256_GCM,data:Yfw=,iv:qHmPKznOG/+9phCI9Ix1amuEsvo8dinABt8Nif6mXTs=,tag:aSb4Ejy1cpmFpwWj9w7Q+A==,type:str]
kind: ENC[AES256_GCM,data:THkifKvu,iv:g0tfwj1d02eUb+6Zce7mM/4whjOFPw5Wt2LBAMG7zEM=,tag:s7MtBY84uapWRHxyzexAJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3dVjTaj4TRTC99DRGRD4vpNE9Q==,iv:Q5oq0e8FkC5Yi36h8CxmBe8Lsz3/2VeI4RrBfz76Ou0=,tag:Djxa1sg7US12sRJwWJDb7Q==,type:str]
    namespace: ENC[AES256_GCM,data:Aos9ieX7JVAQ71jSUQ==,iv:vffwyqHdnVwzjUz8+x0RhJWVpuzr47M9LqqZ83fLSvw=,tag:AYVn80Klm8Cs0c+6gCzdUA==,type:str]
type: ENC[AES256_GCM,data:8+Sis05V,iv:ER1QXbfeoqSBwVPuMaXsOObGuZ2GdMr4QzZpFXBKyGs=,tag:QysmkyJHukeR5DPkdR7JsQ==,type:str]
stringData:
    kafka-connect-password: ENC[AES256_GCM,data:logI0W1wBo5ZORwshzay8PDNJ3q7+mSmX1FTebBCq/clKk3YRqYvyq3cA10=,iv:/Yl/fo5F4eG/RIqWCBfwRxWf8m6bjY9wLQeWVge9Az8=,tag:680G53rp1y0Keby7ahYezA==,type:str]
    kafka-connect-jaas-config: ENC[AES256_GCM,data:8gOqirGTSZXLgo5Mc/QhFqyjwsdyWWhZRFW5GfxBLyX4uvaSQGuNYdrTQRGPgjwHR41N3Fy60EkG2K7Zd9RikgV/BLhfAV8Q89oKbxS/ZduemrQcXs74TMEmmvIWQcKO0wpA3xYyrxsu1aRmFwFN7rx0eYV/MqVUgSxmcqUDscbRsDBLt33q58W52tX7ZZx4vyc=,iv:UYA1W9AclXlO/qUSJAVcIHCd9r1n7hEMzhCffcr2Rxo=,tag:WzVh5y6KtzJQGSwR0oY/wA==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:/V8ReF8v1xTN9NBxPtJz/KLE5ig=,iv:L2gckWoUR1DTfReOPAAhAYBt11Z5FzdlV4wrec1OF8k=,tag:FI5LwQiy17cCNUCUxErMvg==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:XdtyXnuGGD/lw7BK40CFau702oQfzaDjL1gmyu+f6uQ0GmbDkvj5vw==,iv:Rc5rqSny8YlhX9u/8nPytbsKekKkU7iK7GKfhfFMalA=,tag:4Lt1mBi2nnTpG/hziiaTzg==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3JkbmZOcmNzc0pBaFlE
            YWZyS21kMmxscDBjUFdvTUhRb0M2SlJoanlRCkwyZjJ5WHp0OU1XTmpGMk5YZmNU
            S3FJaC9UZHMvWHhXQnJSMGhRWTBqbHcKLS0tIHRkT25ZRmF5a3QrZ09vVmF1NFoy
            a3U1TTF2VWJKUEFyTFJqVUZYYk4vSXcK0wqwNXzmcUngZO4KxHDEACTVVHGwHPSx
            l0NcSn+7lY3Z+hx7dGoUO4+K6X2anB0kBzLUanMgH6irAVt8nMY5lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T08:51:29Z"
    mac: ENC[AES256_GCM,data:Vwoe42IybR/SjoDwJeQMl0iYKx60o2V5f7UP5dThjoR669tqsWqb3ovVw7MODiNg0Xev3iIF29rYKQT4BlU2CYFYihPwMVWbJq9a7ISa4sRxo1FrcEG7QLORGl1GV/AEDX9JjPnpNQwgRRGKHnrre5XOp4Q6JF0BV9JS6Kj1joc=,iv:notXnrcq+XLhbzvT1U4ND3/E/dmuXpHqdeBicvgfLM8=,tag:6osXqndSm+yG9WWeCPcaqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
