apiVersion: apps/v1
kind: Deployment
metadata:
  name: yral-web
  namespace: yral-web
  annotations:
    secret.reloader.stakater.com/reload: "yral-web-secrets"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yral-web
  template:
    metadata:
      labels:
        app: yral-web
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: yral-web
          image: harbor.yral.com/yral-web/yral-web:20260814080741-efe3d9a5 # {"$imagepolicy": "flux-system:yral-web"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: yral-web-config
            - secretRef:
                name: yral-web-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 4Gi
