apiVersion: ENC[AES256_GCM,data:Zps=,iv:UYbBePum6nYbQDkcVxkAZuZPpzDrZMNE5s+XQ0N6kuk=,tag:kKXHU1aTKCAxdLT/yLZW/Q==,type:str]
kind: ENC[AES256_GCM,data:AV3BnGRw,iv:RwQeMjVUqGXeT2yY55DZgl80IrRUw8DvwQnWLWNdDBc=,tag:rEOYbxJ8oU44ic9TRVO5nw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dCyQZZY/fTq5P6EG6xstncVYyA==,iv:19dO0NE4uwtziDVzFRirNF40+fI5aWdWC4BgSBBMUIo=,tag:38RKT2NCmNu/OHH7qP0b0w==,type:str]
    namespace: ENC[AES256_GCM,data:F98Lxph5WzY=,iv:XtuDmnBGC4GQW7HhkOznVuYNRDdEi5GSI8F4GIG31p0=,tag:gYxcXqPOJPIaYXVllSX6tg==,type:str]
type: ENC[AES256_GCM,data:/r9Qw4LIyaIgYeSTOVgJX2LIYRbB2iry,iv:LQPQOtMpN5lgVwnS9G3oLyAkf8nJllj3SzbuLXucvkI=,tag:Y28grZM+jSnD9WoxpPCBWQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:DT+j,iv:qP+Y6afHPy0+kxY3630MGmlF8R7/RMZocHFLC/rzdQ8=,tag:vADEwxRyHcni3/9xrsxNSw==,type:str]
    password: ENC[AES256_GCM,data:2ojMyvVAG3+NERBABslLV2oAugCKex000fyeNm5RlPxQOQ7VJRfjipBwBh3dPZKyS7z10lbDccUcxU2sDiQ/KEWK/sDGbX9y71FtSJ0mzZU1sOzDrhClECt/R1Qn,iv:t7n3+r15IbRDvEblNXk2mH4xGbOQh4hMiAaUsdFPFb4=,tag:UYx8B7QoJE0o5VBHmYYUdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aU9qNFNBOXU3MWZzM0c5
            ZWRYcVZVbHdJdHd3dXgzNGw3ZnVyV1dsVlNrCjBoMlBGcEJlaTBDaURPN0xZb2xK
            Y2R0ck5EWGR4amszbE5rdU9Eb1ZyWnMKLS0tIHNiTnRzZU91dXYyeFVwMDM3Zm0v
            Mys3TXMxdzBBNGtXcCtGUldHNmorcDQKwGE18Dg5PEAAh7nSrCNMRYvA8bRLYnni
            7O+PrqAVM79A4ZLlXpZL6mvRJhz/D8YCh/g1NxRATmtBULeHzuN2Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-08-17T12:17:23Z"
    mac: ENC[AES256_GCM,data:kW2MW+t3xa6xG94rTqRxNyDzsMHOu35s7R79Ar6N0u3T/s3ym5+ghpJQ5RAH/e1AhzxvC5GZmsafrIniG095RX4S4UGD8DqBsaJjHtO/A4bvqRX84lFky6aW6vgwynO1IOb6VgfLKVSUPXGAPT7q4x2rapFkyNSdAj9TxSDDVg8=,iv:utVJ+9HxTRU4ekU4lVUtGTCVYwzFl+JwSYCN6iPI7tU=,tag:q2MD0fE4mVj1+l/GpC0Wug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
