apiVersion: ENC[AES256_GCM,data:9Z8=,iv:hv7R7iNy6LHwuGJowt28/DZ1pEvygYuDcLHhukseexk=,tag:vKFA910acQYoVGgMa943fg==,type:str]
kind: ENC[AES256_GCM,data:hIbYjerF,iv:UVF4HToWutcHNGVsvOT0NBjmyG2FQumWVascFt0y2x8=,tag:a+g84ydtcNVWM3mitwyLGg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JFiW9muq7D6tLY9mu6hJLgpFsg==,iv:jRsntELAGBuPMHFenqbRfO+f0cGcyXUu0sy1UwVPysI=,tag:gPUiy9BSQV4pA7vdOwtJBg==,type:str]
    namespace: ENC[AES256_GCM,data:BSWSllU6aHMUFe4=,iv:IL6l+HHXkmgdDieVOhHHM0HIHQvtkye1YQtcuvixxnk=,tag:FB08avWlPVosa5h9FhtChg==,type:str]
type: ENC[AES256_GCM,data:6qoKLjMLYUyIP+mTMH2TBpfoluLvNnoA,iv:JFEjtJx/iL7HqXZTr3m1z9XKRm7seTtn8jjrGebpsfo=,tag:ehHm2JCWP6MaI2lWZkxG4Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:pY6+,iv:eBOySkip8gUydw3RVDb3N6be/yvNByMuMpGoiXLufrw=,tag:NlfbKYJCvldZluVdPuyoZQ==,type:str]
    password: ENC[AES256_GCM,data:rhsVQBZ5LjGHBGnNcioS11QKWoKskhtPhwfmsqvT7z9I4pq37Xw5mvZlCCHd6a1FZQrm18Y6sJcD1Q2KXuu5ND2eZ467BJLz3xJCt0X7HZJRkKEzfKuBqjkXPPcT,iv:kcWck//7vbHWFAt0S1RmEyIy+xjDCER+rrw6wQjiD5M=,tag:xAw1ZiY9nH+HD2mZ5epI9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLV0owRVRIWStXWjYwYU84
            VU0vVHVMYm1jZVViWnlLRDExS2ZEY0s2ZkZBClozVUwzWDdzN3pyTVN6TUtUWWlM
            b2J5bzVpY3FrTkovVnZUZkk2MXdLZWcKLS0tIDFiclJSUnRWNWZsQktLTnB0MGlD
            VUJKZUxDQVhmc1hPSnpxMldYR1lWc1EKtzjZYSKhX/Nk7puoftFx5/teIawxbV7W
            CLaWWIiVOj2Kb2/RJMXhuizuT2hNBEK6+xVMKvUJ3pQLYXDCrTq4eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-15T16:45:59Z"
    mac: ENC[AES256_GCM,data:c8kXRymfMjf3FZ0WtVN6HtLY9Tqf4Iuc34Yg3GMmqs4nQRfccj81h5nLIRVqfZBRZFjHvXD6jktjbtXbfS7RsD8IFT2UXy+Yf00/gbGaVkf8l4nzhfk1M/hlojF2QY8sn/lSTOgw9gZJmdd6na+ILZOB3mZp7wPC+SzTlilUI4E=,iv:ZcMG5cFDfMZvtMHFDa5MOuvCgcJwR8n7d9FHrt2m/Hc=,tag:NVM2vOhQlbsquxwRCbeTRw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
