[package]
name = "state"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
auth = { path = "../auth" }
axum = { workspace = true, features = ["macros"], optional = true }
axum-extra = {
  workspace = true,
  features = [
    "cookie",
    "cookie-private",
    "cookie-signed",
    "typed-header",
  ],
  optional = true
}
base64 = { workspace = true, optional = true }
codee = { workspace = true, features = ["json_serde"] }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
# workspace deps
consts = { path = "../consts" }
dotenv = { workspace = true, optional = true }
enum_dispatch = { workspace = true, optional = true }
futures = { workspace = true }
getrandom = { version = "0.3", default-features = false, features = ["wasm_js"], optional = true }
global-constants = { workspace = true }
gloo = { workspace = true, features = ["futures", "net"] }
gob-cloudflare = { workspace = true, optional = true }
hex = { workspace = true }
http = { workspace = true }
icondata = { workspace = true }
icondata_core = { workspace = true }
js-sys = { workspace = true }
jsonwebtoken = { workspace = true, optional = true, features = ["aws_lc_rs", "use_pem"] }
leptos = { workspace = true, features = ["nightly"] }
leptos_axum = { workspace = true, optional = true }
leptos_icons = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true, features = ["nightly"] }
leptos-use = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
openidconnect = { workspace = true, optional = true }
openssl-sys = { workspace = true, features = ["vendored"], optional = true }
rand = { workspace = true, default-features = false, features = ["small_rng"] }
rand_chacha = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
reqwest = { workspace = true, features = ["http2", "json", "multipart"] }
send_wrapper = { workspace = true, features = ["futures"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
simple_logger = { workspace = true }
spacetimedb-sdk = { workspace = true, optional = true }
speedate = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal", "time"], optional = true }
tower = { workspace = true, features = ["full"], optional = true }
tower-http = { workspace = true, features = ["cors", "fs"], optional = true }
tracing = { workspace = true, optional = true }
types = { workspace = true }
urlencoding = { workspace = true }
utils = { path = "../utils" }
uts2ts = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = {
  workspace = true,
  features = [
    "Clipboard",
    "Document",
    "HtmlDocument",
    "Navigator",
    "ShareData",
    "ValidityState",
    "Window",
    "Worker",
    "XmlHttpRequest",
    "XmlHttpRequestUpload",
  ],
  optional = true
}
web-time.workspace = true
yral-database-spacetime-bindings = { workspace = true, optional = true }

[build-dependencies]
anyhow = { workspace = true }

[features]
backend-admin = []
cloudflare = ["dep:gob-cloudflare"]
hydrate = [
  "consts/hydrate",
  "dep:base64",
  "dep:getrandom",
  "dep:rand_chacha",
  "dep:spacetimedb-sdk",
  "dep:web-sys",
  "dep:yral-database-spacetime-bindings",
  "leptos/hydrate",
  "send_wrapper/futures",
  "spacetimedb-browser",
  "speedate",
  "utils/hydrate",
]
oauth-hydrate = []
oauth-ssr = ["dep:openidconnect"]
redis-kv = []
release-bin = [
  "backend-admin",
  "cloudflare",
  "gob-cloudflare/rustls-tls",
  "oauth-ssr",
  "ssr",
]
release-lib = [
  "backend-admin",
  "cloudflare",
  "dep:openidconnect",
  "hydrate",
  "oauth-hydrate",
]
spacetimedb-browser = ["spacetimedb-sdk/browser"]
ssr = ["auth/ssr", "axum-extra", "consts/ssr", "dep:axum", "dep:dotenv", "dep:enum_dispatch", "dep:leptos_axum", "dep:openssl-sys", "dep:rand_chacha", "dep:regex", "dep:spacetimedb-sdk", "dep:tokio", "dep:tower", "dep:tower-http", "dep:tracing", "dep:yral-database-spacetime-bindings", "leptos_meta/ssr", "leptos_router/ssr", "leptos-use/axum", "leptos-use/ssr", "leptos/ssr", "reqwest/rustls", "speedate", "utils/ssr"]
