[package]
name = "yral-metadata-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
chrono = { workspace = true }
ic-agent = { workspace = true, default-features = false, optional = true }
k256 = { workspace = true, default-features = false, features = ["ecdsa", "pkcs8"], optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
web-time = { workspace = true }

[features]
default = ["ic-agent", "verify"]
ic-agent = ["dep:ic-agent"]
verify = ["dep:k256", "ic-agent"]