apiVersion: ENC[AES256_GCM,data:sGE=,iv:xmX65ndAEJgcm+t+BnHOR9psua66UEnVg9FfSbYVQ20=,tag:iu5Zgm1h0tC7zmKrfvjSCQ==,type:str]
kind: ENC[AES256_GCM,data:hW2MdMgF,iv:HqBrGuIsNo3OzcvOtuT0SVETyps2I6ELFRZKamO46mg=,tag:S2ZXhQS0SBndWgvSCDsdqQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l0i0B1c6fmVZhDJhRp7e8qEM4AfO8gag,iv:bpmatPIx70OTPsc59lY9epfknmXRiljFNEfNVCO1hEQ=,tag:f1Dfh7yVs9g89YBMaG3I6g==,type:str]
    namespace: ENC[AES256_GCM,data:OqcMiVgPJPp/1Hk=,iv:sxMMdsqtfaxdtlLzPxsOgOwApg3iRMylgtFiDM+qULI=,tag:WWMNjbKZAcmahvpA8MccEQ==,type:str]
stringData:
    BYTEBASE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:RA4eVThzm1nXq+1HvjDYc2rk,iv:ykod5QsRPyx4OpdtStghFGqgo6EttJez5MQOZDIKtdk=,tag:NsycdNACwKUaRbfcVUVYHA==,type:str]
    RUST_COUNTER_POSTGRES_PASSWORD: ENC[AES256_GCM,data:bgyXbS5OScTk03JSJIu7HR8G24+mIw==,iv:t3GgslZqqsafcWqdHXBUzPF7C6XQ9sahN3zqfx/fM8E=,tag:zLhCVBLEKPLIwaEBNqlUbA==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS0lPVkFReGFUdjRwU3pH
            ZFVnc1g1VG9FL0tES0lYUU1OSjM1aVg4MndVCjBJazNqVG80OTNQeVBaS1VDdHVO
            d2xyajhIQ3hvTWZhajg4QVcybzBDbmcKLS0tIEJGbEVGSGVhN295eHlwUUFENGUy
            VmNySmx6eStxY0dsOCtvbWVzeVR5aFEKiVGLQ4O0XSUh91y8LiA22Pds0VCDjDKW
            ezRRhGke0b+AX6bFd+Poy75ysDRvnA9zd5UCRLt3XTyhG/hnJRj1Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T17:30:44Z"
    mac: ENC[AES256_GCM,data:qf+jRDZqilSbO9iUl8IHS44+qJdvvlRD6C7fkofdHfxO+pSmLhBwjlM1Qv0w3Adxz/8TgFOEzY5+HwaYAHYMDd2HAwiU/rHsSTLHCXx8+tmOQTtAngiUXdP6IMQVsxzoT024o+azmOQLh2TUju1CszAeS33vM6njet+NFdsbDhQ=,iv:xjVkMqCA4nM8s036bhKgNRFn+PDe33g2Py35bpAAE70=,tag:Tk8zX8vRF4VWJOCgIHSYag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
