apiVersion: ENC[AES256_GCM,data:7Z8=,iv:Lv+4Ly5SfhidKBSBsoKlKmzX+pnImtGZc1evwHjJzAw=,tag:oJiBI2ozKNC8QgjLZmJ3rg==,type:str]
kind: ENC[AES256_GCM,data:t33K0EFb,iv:B3QRxEfb+QxjQt9DozU5/4YIvxtv/AkhgwQEjF+tIl4=,tag:yjIKg1bCsNAiBPI3YQjR2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WkcuK4czzsqIeO9oAmSoF4Z+Aht+PCyw,iv:AnT9tO+Xx79K8QCjBIWKVRnsWmQCJlFUmw4CcAMJzg8=,tag:CLgc7dR6Zbq8XfZMQ7Yimw==,type:str]
    namespace: ENC[AES256_GCM,data:sPZKRSTie7lRZdo=,iv:SajGl8SmJs3XVkyAikvNY+XmhQ87chs9WN4vIBOQIiY=,tag:Sc8TgmvmZtQ8xAwryaRfhw==,type:str]
stringData:
    BYTEBASE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:8dd1NK0kuXSViiJNWSJvvFtW,iv:GL7TEVngjCv2P4lf9BkW+1IM95J3Cnabt8XQMW92DqY=,tag:+u0sReZc0I95NY9y0llyLA==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUlVXczdlaFBZZnNGOHc3
            YmZPY0d4TFBmWkVKOE5QR044M0NjM0c3Z1VjCjhtZmk5d2ViTHc2US9tSVYzMFhn
            bjc5TXhRMHQ4SmRVZG5TTjhpRzVKVXMKLS0tIFlkZjNWWnBrRS9Ea01URlRhY0F6
            YlRMWWh2RUwwR2txcUtuWDNxZ0EvVFUKx1Rjx3zQs0CtZhPbEzT3gsuLR21pUNIu
            YqRVZjndmwMlshS3CbpdDM/r/6ApfwqGroAJDPGYAMIITZOi/t4SiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T11:06:06Z"
    mac: ENC[AES256_GCM,data:4GfGIhc7wIJpkjihSZ6A/NvIUvMF1J/ppSwl00LowR3lWQMKo0iKfqXKljmuMPVdRCvnDSEx1pa0kWxNvztCzuAjfh720qqr6NpQQT2pLTAcslxKrXVvegNVJmwOjd0CAzrN19Pgd0uYM9OTF8WZ700pysooSf5mJY8p+sjjLP0=,iv:gRYmKmv/OB5qbLxIegyL0AIGMG/fV67i2YA2yWmX0Fw=,tag:yR1X6+10eHAaPfyKPUKNzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
