apiVersion: ENC[AES256_GCM,data:uGE=,iv:K4mEFTSLI7BR7s2uJ6oJPM0L78klMUM89ndNnZ7p6h0=,tag:qid9qD6HPRus2hY9GUU6qg==,type:str]
kind: ENC[AES256_GCM,data:TAtRJRyf,iv:ajqA8ncJjd2GCnMdBZKjuhuQQlPaEy0BDfLE0p5mOus=,tag:VjMYroTYOrNS+ucY3mtf2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gG+iCYXGU3Au15l2AjP1edvMbg==,iv:MkTH/DXr8LCMtiMTTYMjH1s6bPKSq+xi8dGTXL4eovE=,tag:qMIf3hVA6naqzHVYXd71XA==,type:str]
    namespace: ENC[AES256_GCM,data:sH9LXBgYrkuj,iv:lMunvBW3CI2xSlccoh4CHhmJSW0DiPR7wCf7vbsid+s=,tag:sNZ27V0c8kCNKEKsXDYFcQ==,type:str]
type: ENC[AES256_GCM,data:eqkZej/KCBfuWdTfWL+x/U9tVMnFpirF,iv:T89AdaBmDwLI24l0DL8nXXdNXFFed1YfdqUMGoGiPqI=,tag:TTIdUKgVRnh+IakYAhVgwA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:GEvP,iv:YSaWpGGWY/kkCpb05uS7CIJypl5dsVJDlQWRH8DzLvo=,tag:1xnKicYJw0p35OsoPbV51Q==,type:str]
    password: ENC[AES256_GCM,data:Kjz3H1fnX1HeC5W9ISumssC3ezuBRr4E+cOMaK3SaDzbaAXgCwmiCCFyezjvBQnYNINROgH+Qqe0NHWrNT4phnxMDuLHLyP5DLv+z4p5S+v5pzWpVwAy14h3ENaU,iv:yU/U4X0qmNQ95UdNCKC+H57H2pXwfECdVL0tbzk8lg8=,tag:8s+7rIE3rfBmj/OmwcP6Fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SkZRQnZ6SWpkWVg3SXJQ
            TWdmb3lPMzVOT2tDRnNCWVJIWXZKaVhmRTJVCjJOa3FuL1JTSHE3TFc2UUtFeGtQ
            Y00xU2h2YWpLTEU5aHREMFdHem5UclUKLS0tIHpWWEtIeGJ1eXZrVU5Gd2tKeldj
            OTBZYm1DbnlObU5aRW5kaGdGWm9yREUKexuZw3U1ijB95D3bIKqD8UK1Zbn+ORNp
            8Vr1DfaezCVo+FszpGU2QIFE3Ctlbl4plxUaVO3gUnF5YSrqYtm0NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-03T13:48:30Z"
    mac: ENC[AES256_GCM,data:KF91rk0WZeFDjdtZiz9QNbuML3mWRqSVG/r0DKuWayU5gam3VcuVrgKTrekwv9srvkw0LttBe6JAIfewNiJOm/AqKnVg+WV166jcWBKQLasEkGnmEVryD4kAAsg2jzFl5WjEcKeiVRKJXI/4e90ZYM7yivY5Lmauymmf0HpECd8=,iv:WgdYP9vCL2pX9EHYnxuZeJJ62m1v1P3z7f/hdiRg9Sk=,tag:4oW3RM/H5YjnCJXW0iOEOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
