apiVersion: v1
kind: Secret
metadata:
    name: github-ssh-secret
    namespace: yral-auth
type: kubernetes.io/ssh-auth
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:dCE4AQgiJn94N4rzlkiQ+CI3M5rooFops78UWi1VIMl2dug/zxtSiAhTTWIsk/9bVgXPDUJDi1G/Xiadds+q5Bumns3kCgYoDQ3e8zeiZsuE6a1okCOBKF6NmZ7s6ZFf4h7100EpWYj8wwzGRoaLvhbWL2XrFhVodf48fSSvyTtNOK0gX/L57VPfTyAPJ4rTibN6Zqq277VMlDEjQWoXJ1hillYDGKe3AxWIk3qaOfYf+ARCusX65E/8EesSuyuGjJP9pYwYP5UDvl1nPzEinoeKGSiFAMCjwxQdN+UIeQp5wyuNpua7k8oqocU3lRuQ3A22s2ix6TE3CZY48cz8czrb2ogzmk1PZ9clUD3lySRRs8ncAnuzTHYsLN+WBo00nnPv67K+HSlj1H9b5IM37BFQN4Ry/wb59yerb2whgmgBL8bNGRcumq9mpOr5wi5E9HvaldfBtD2FJjfClhjw1rAgzTudKjojL9UJpn3LBmvuwEDYO+1n1cdPEmtyNHTnzddRd/wdzkL/E3fMNbNRanGi5jK4YUsEFR2hlhJvjDXQM5Z9,iv:kUUHftc8LPTaetTRFDlteuCkV8OB1Si97WwvFKQzAlI=,tag:W05NiZEKHJCIHNOrvVRJVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQllRVHBqbStmVU5GZTVi
            THlqNmRQMmhLMUFsUHpYZiszcjA2cG9vZUdrClVFUlJGd2laeEordWVnTUVYQ3U4
            OFZUQ0FwTUxJdHBwNnZ4WjVKOVVIckEKLS0tIGs2K3A4VE9UWndxTnZ1VFpuakZC
            dXJPcEpLb3VjbVRZbWVCQ0VSR2Q3c0kKm5OTth1N9t7bgslnYvoQEzjj6RWQiwA6
            aNQ/sCwmpweGNP2MZaqyLTvhUwgCUADIVsMHt6tWMScn/K4hBM3moA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T10:20:47Z"
    mac: ENC[AES256_GCM,data:NzUAsyE/KxHe6c1M8wG7cQyiX3SM0Gdbmmg5R+KM6zD8Sz4bftd/TgkW91QP86icckSOfaT/bzdBYwpFQwAhI5d4TeMh03S6Xgqog4JVVOOoHDq02CGAoEJLw2rntYZXmhZYWEHbdBhSy7qOWe6mQVnvg7so/CGZeiog6dGghqk=,iv:OT2FKc9dN3iCY25aXarG1Tamrm9lca6vMefqF1KN1tA=,tag:EExt+pL4CRPBNx+Yb4QmOQ==,type:str]
    version: 3.13.2
