apiVersion: v1
kind: Secret
metadata:
    name: harbor-pull-secret
    namespace: yral-auth
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:XBnt0MyIS4r8G6n3Hh6+UpEc7XTCUVtyRenrNu+bdf9UdrMBj6DqFGm8CaKzhoijSEGzYQ/UGMcvbtfJhsk5H3UZR/d6jjvNr3GD+5yrubykeusbNI58HJFwyHwp+Rx+7pwHzk56n2hLitBfJVgAKiFXRfv25DngPv0jcLVwbce2w7qwqB1n0iLp3t9pT72wkP7yiTeBJ+HpG0FGIfMzP5Y6iR/zU4+bSko+gRsPxaAsEf/3AUMLHpss7MjKAMhW07WmR9nrg44=,iv:me42khejJT7oxTczMEheqWUgYXmu3DittPCfzbJFNMw=,tag:tZIa5CvCv6BbrAzWcM6+Bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaUo4MzlNL3NSSVlOcFUz
            TW1iZGl4S1huWEp4aUpPNlgyOE11SGh3TDBzClNBaDZ1MFlidCtKYzZ2UzNPVFhz
            aEwrTXYyZEkzYit5cDJ1T3VLdWl2QmsKLS0tIHRBbllsRTZ5b25GN1ZmZDY1VVpH
            clhBR0ZIR2pqSExJdEV3c0Q4WXFUYncKZshHh57Ann9U8m+IjR8MLwQKVS5OHQWO
            tCc39JmSctMcOOi8tR9ha26zc0/KtduO7lGNS2sFk3sYBvANqC33jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:41:04Z"
    mac: ENC[AES256_GCM,data:GpkEHOr7LhQ6dHhDWS21CLfoPalxYyjNBcfGBchU0njoubUBsc98USJfsMyUFDe79s7FC3+lJLS9Cg8zsu0U4qOsywPAqn6vHfaP3+u50CQKJNsexDOLlAw/NZy+PEiIBh7PUfm6dztLoziY6DRajfY6Ogl6l1QznDNWFTbkHRI=,iv:ObtRxWUmzrEaGem4iX+0LYO3II/55HydHuhYGGAgra4=,tag:gTuRomV0PP2MqilLESqyeA==,type:str]
    version: 3.13.2
