apiVersion: v1
kind: Secret
metadata:
    name: harbor-scan-secret
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:kAZibp+90DI4hkTKar/yKUWS1uo0b2c=,iv:+2y+Q+qHKOnlRaMxjvRIOhVdDZnrP1C51tROGNECYxo=,tag:SjOIujEV7Y3sp9lyUYrBkA==,type:str]
    password: ENC[AES256_GCM,data:YLTAce5jm6w8DaeHDz2q80BEXvDwC8fTJh/cZpT+VpI=,iv:XzFV7Cn9g6yZSBy4tUunY+ItCUqfQCfGMoFdj2MXXRc=,tag:M17Yk9kRLOx6xDiX4NJj+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cTRZakZUY2cxSG5ERGtp
            dlFSVFAxUWl5eDJ1d1BEdG1yc1B0L2p2WnhBCk1OUHQxSytodjBmTmxLeDFIVTQz
            V0FkeUxqQ3RRK1NKZm1zWDYvaHp3eVEKLS0tIGN3N01SQ2NMU2RJTVdqYk1GOEVt
            cEVuMUttZit1VHpxQ0M2dnBLQ3lEYkkKFAyWhLi9PQTip9/vxM59lR4dTXhCLtGf
            kNmv61U6VNg6ijtqY63ZQbO1cO8SI8xWxBaEt22KJtDaSJ0x6xt+aA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:41:36Z"
    mac: ENC[AES256_GCM,data:XetIiyt7uNR7P2TDNov+7j2eeYLV0oxyrygwaxVVLvwK4wtxsZgOg3V5daUeT3L+3hX+2qL0g1x20tDVyzwmZS/fofJZDaolh1EvdXkDwXrB6sgvJypgmY4lXPCM04eMGWiH6SAGli4SE1TQ0RYwx9qZtG1DR2jwaW+XDCReXQM=,iv:t1MVvxCV91xZRc3fIZpWPlOP2mPiodGM2MVcZdxjsJM=,tag:sdxKRy0wgMn9/Gw0qqIR/w==,type:str]
    version: 3.13.2
