apiVersion: v1
kind: Secret
metadata:
    name: harbor-scan-secret
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1EQqvW+C4SzS7yJ6D7qOOU0XINIpyAM=,iv:/9+UajGR7Ytfd8Fb8uCZ/XauTclBwlUqLAr97wOrP54=,tag:kTzCLgdeCruEPUpEhUgzVQ==,type:str]
    password: ENC[AES256_GCM,data:dm0Mgiv3uejRGVy5dLfgNELH8cett93rx7kzAAd5RPc=,iv:swwDqHC+LEZS4oBXtePTX0xCTfnKKFnFl9Rt7IKIq2c=,tag:Jy9Qc6kgPOeRX68OyzJaBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM0VublNDK2VKY2Jpa2dy
            Szh2OHFVbXVsRFJtQmRGdlQybzQwak85V0NVCkRPRU9qaXV5dExKWi93Q3N4Vzdw
            U1gyNFBmVFZVWHNsRG9KbDhsSU5LSW8KLS0tIHRvNkFCQUFobG9TZ1djTElnMDd3
            STBTNDhMalhyblRqSHdhNG9qelVLQWsKIAQzHf1Q71SkhN3f00V7BrjjF2g4pbPe
            MXHhQDiUTldI9h2zVkfb4zO5531u+63D7onicjbsTsW7CbfP58FNiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:52:28Z"
    mac: ENC[AES256_GCM,data:Ugf6FAMaSXMQ9DkBP0MmbV5+AxYERG/Cs4qMHyYHPN4pTL4/PIM81ob5C3HHG0uq15VwOJYSqVl0e6Gd43/hoxAbU/bwHgZ2gn6GjkMvvVEK9rCBBvM3MYvFRW+i2v/krckB7m+IgHVK8zEaAbzqEjxUvopF3PnXy/kA3NNqV/g=,iv:U2AiX2dogawJs7zQomvJr8Ws8ylxLYllDde1Tm68vQk=,tag:MkROIsEace0OxKXD1kvZAA==,type:str]
    version: 3.13.2
