apiVersion: ENC[AES256_GCM,data:Rfw=,iv:TYH5B2vKoWswHQVNe3Go+qQfd2IYQ+8Fe6hFZdhCVEo=,tag:FMnkyiYkU4Rpm0g+MvTwtA==,type:str]
kind: ENC[AES256_GCM,data:I2d78jS6,iv:aq1dYyzGKkfw4u10kNmnOyo3Zd1KY55G1tOyVjrVwx4=,tag:d6Yo6lWpolP5H96dRx8otg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qpzt79CvkdxP73uwrO7FT4DTxQ==,iv:n8iRSX5Yn/u7BZNFXhW/A9hAxT9Ok0CjZVbhlmVo6iE=,tag:cB9kL0Vlw9QUZKXZBzR5sA==,type:str]
    namespace: ENC[AES256_GCM,data:BiRty2MvsHkqq+QA8k6B,iv:El6vr927lLAnKHCmBu6TgTLIIT1zqU2oxDSxzuR5+58=,tag:XHVUENAFKjep56fbjZMxJw==,type:str]
type: ENC[AES256_GCM,data:cBlxEu09w1MKcDmPiqORJCRX0akCcYyo,iv:uDWRJ8CCXDCd2GUfOLbFvTVNxJeMUFEewcKV6ijtoiY=,tag:GfFbb8Baks8OweOWceiKXg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:ROom,iv:X+2oLlisJFfXDUd7etmKLaVfpBeueN685Ui919iUyhs=,tag:JMRAoFB83Gyvo1CtCv8XaQ==,type:str]
    password: ENC[AES256_GCM,data:AFGHd2E3hPyTWhdnIKZbgRKqCP64/cM+/6lYzWIJhDHrSxLTWSP9zrASr01jmyecvOqWFNfW18oPG2e9LLzeyCeTzeSU787t7IQkH3+xq2jYn830Oomarf1cuPpc,iv:2gPrbEjfXl5UAIFtrbZqOgEB/D8NpgtJlZiVjuSS3A4=,tag:bvDEITYMKpgQ5IkJD+mK8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY29iMXEzUVNoT1pXaGN6
            MjdTRnZYQlIvSW4zTWMraVdxckdlY3BQZm1zClJOZzJLNUJjOUIxNkRZTVYrdzlF
            Z1pXQnJLV0xyVUJsaFJZNHB1Zm01UU0KLS0tIENTdTkzYytMQVVwSzNtNlZ6N0Ez
            ZzF5T1h0ZUJZOFRRMy96Y3JuR0s4UVUKLpcn7Us8Kf/wYeGUovkZGLQuHEG98kd2
            n8gba1Dj5R98GX6YQY4Vj4wEueVDxVbcarTlUsKZeSIP+9e8xqR0zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    lastmodified: "2026-07-16T15:35:23Z"
    mac: ENC[AES256_GCM,data:MIkkXd34I9nbXeFuL+MCfjqsGsNkW+jy5ib3VmeZH21vVtX4bI376IhiqgsuAX7sahMqJYWmvBJFKxlKipn5ieFBYn9QU8y4RNcjWUitEC2vV2Ibmt7Xi9o4qmjQWNiF6qUAxhVl9jp2G0Q81OIxE6/R9hVP0bgxVap16eUTZwg=,iv:5Y5TZo/eWZMYCJVAS9t/Y/PJXLxboRfFiC6btBsxU7k=,tag:c37JBgbQFqgCLrz7re1X0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
