apiVersion: v1
kind: Secret
metadata:
    name: github-ssh-secret
    namespace: off-chain-agent
type: kubernetes.io/ssh-auth
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:bdi4gu/26PFkHnfNSsGC1M4t1J+ZIuZ2O/v3GxLiWPp++EN/eiyaxxZGrIfYxRWz/9ZLakXIEoX8dayez/1VxohFYc58OYv0BoyJa0DecDS7iGi6nwlgDTjTtwPbaIFPrFDf/YfgOeOKTDMxKRX7nI63djmiQj8oTdqNfrpAAGHs7r22eLgYXPGPO/Gr3w/mDY2ux31B4dffwWgiO/pgkkCu6Egf0yrPz4wVtmAzJptkUqOjRTj3lro1Omvy2BMj2HvneRLZQWa8AdUDuN5zZx2GrzcJftouQNbx2vS48DUKWLt7rS8fjFczvjt8hKCmut1fnVbzCyQcNwAR61rI4zmbTJOnRM4VlMx45ENHB7oJjWSOuUvDzGxBvqvTU6L4flVpWkSpHB6NLsE/gygsaSD68V19Wj8J/o/ue0wRMGkttcyp/JlSghh0gdJIznaxojUP0h+pdTg2o3rVs6A9uOlzquoYkdrX8pgnMj57iGWf9JiK4KDAd8LEP1FWjQyasfh9Gbj5jw7BsJwnk9uMQwyZUGGCEZAmJS8wK1zVeqPN5NZg,iv:L2O6z7xbdr2TykfyyAs69Rf45QpPMg2qplRtKm8BDJI=,tag:YAzXSb8dd4KNULP7CEjCVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYkNHbnhDRm1QbjJnSzA2
            ZEVJVHZYVnhaamhOcC9ncVRHbE1LMHNMQUIwCm9DY1ozaDQ3MDhKT00wR0FXdnND
            QW9vRHRXbXRxa1prZWswOEFJaWFtNEUKLS0tIG9IaHplM3ZvRndRUy9FbEVmaWpp
            a3FONnk2UFYzN2JIOHpJMFRodmx2SzAKLvqX+AYQqql4neNHLX6tbsA5QFW/S+uc
            RMxhygaD462iCRj5iaO/NZbc1Cg2weolCYnG7FRPL438Tz9QhHeTGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T10:20:47Z"
    mac: ENC[AES256_GCM,data:lqg27uruQQyrkj2E1VH2MNZ330O3CYDyuzw0HT1bz5xbO0W2trLgix0Cv6Vpy084kLx+demmM1DLPv5c9mnOTcuvBe0kPccJCAzlESIZJZJY5/5O970QAXvqrHd8+qxSyhXFn1ZqXzyXt4/5E9c/CFEO1UHjZIA5w3y0pXAkgsw=,iv:ZxwwUhGpIFt60OJIy3c0LS+t7vr9UH5VzfifDAyYn0Q=,tag:VLtyjFYFRjYyxqhFIeX4mA==,type:str]
    version: 3.13.2
