apiVersion: v1
kind: Secret
metadata:
    name: harbor-pull-secret
    namespace: off-chain-agent
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:fgpE24HMV9I5Rg33ZT2FdZpOV/7KVv/7cKg6SAGSNlsOS5fErAL2mUUNbf33zPAOC5uRAHivWU3sTLTQ4IqWP+CQAhick6dxowWdvI4o+XDXeJ4pha9qRlqHY/sBrMfwokTHfLFR5bZShmCamoK6GVRvenKlPcwA8jfXaiqqwgj0+qY8pBvEUjg0sTvjhwrTnSAtVHYvFovYVVoSW6SWUz7Zf00ZR66TE3sYg4MLhjQCo53ro9od2bbG7aA6JhSNUKk4rf9UfWM=,iv:M7DVqyk/ILrvLtUlfJU2mm3lviDeh+YDZ1ylm5bgnOs=,tag:pWyqt9ZJiooSi73nZO1EWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdEpVSDlvcUw5L3NuRGNr
            V1ZGZGVlSElENkdISVc1cmQ5cnVKZFlXaVI4CjVPTkJMZ1IxYjVjSmNtc3lyQWRx
            T3BZK05hbGRTZ2I5VktDTW94d2VpMkkKLS0tIDB6eGVJeFNrUDU0c0p0bzBseWJP
            MHdIS08zLzY4Rmcxd1JzeDhkQUdXeTgKuidBNork9BkdB9eeKTSYChEXTFdEW0pG
            6N5gpMuAkG2y33MNzyPjufW9lpWO5yEJImMntZkUZT5ngZ7jC/bfzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:41:04Z"
    mac: ENC[AES256_GCM,data:6mOtjplfMew0w2nQiMFB4yB/V2+TzNsyDmjLAK+GEawyPQIq157pXC8n2d+8fMflWt85/Vn/zEFJBmWhLeC9R8IvIwLyT1C0X5sAhXtSMZcGswM3MzrlOmEiNfNAxAXp6SB8z7NCLJKa0BsyEPRacMFfFbwe1yikmJ2yPX/2wSU=,iv:KtaDeppAsKZIs0w/vMS8NvIBHzZlG/I9FdCbYGSHE7M=,tag:OUei2ujsmovawPCY/B0j3A==,type:str]
    version: 3.13.2
