apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - bootstrap-secret.sops.yaml
  - bootstrap-terraform.yaml
  - bootstrap-job.yaml
