apiVersion: ENC[AES256_GCM,data:z2I=,iv:6U+Q58DFCseIYwwZ7pePLvqaRHf1H9Pr4oM7WzvG9K4=,tag:1i9rhb3H0kxjfkG+VwCPTQ==,type:str]
kind: ENC[AES256_GCM,data:9hfwUnIX,iv:v22doJkI6nfIQwKX+CeFrMkdcrwWS+96sWj6VAAMhLA=,tag:juttc5A4h3CW9ejUZF3SSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l9jeKcohMSbfwC9by/8gY7EnGsU3,iv:Nlhf09fuaWYdtSMpYV09kCpg3D8hy+8FwDVtJGp0p48=,tag:qXYpqO+3XW1xi7rAHBlp1w==,type:str]
    namespace: ENC[AES256_GCM,data:5H19BuJ4AY8=,iv:YxekkHsk73oaRyU1TWy5z08UE9AGVZpvLMgkcKIwaaE=,tag:iRsARHgUZUvh017hgwiJEQ==,type:str]
type: ENC[AES256_GCM,data:tMhupNBDzAnUMh5fkScDx86QUhlmntmp,iv:H+PbhzpeZarhFPEyvORtWU51RRfQvowy3+Zg3U3Ej2U=,tag:W2h6KelPyPi17CPMQ3h+vw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:oZnhcJ0B1go=,iv:9fqcgds7A0+VCdAVnGDhSs6dnB2laQg0OI9qJfUy2DY=,tag:O99mTufWF5r7AZNR6vzHSw==,type:str]
    password: ENC[AES256_GCM,data:vhGrvEoZxbD3hjb0kQyC95XP,iv:CdkAIrFXqfY77w2jC0GMkls+vIKykG9lDU0t1kr3xe8=,tag:MGptEdLuE1Q7GgYO9coRjQ==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYVE2d1ZBdlpTTHhFVER5
            MGhIZ2FGRW9nL2JYbDBBUzhZd1dSQm0wckFjClFtODVPTjB2dG01YTNOMi9WazF1
            R1pWMUVPenZXZHJYbHZHM1puYU5SN0UKLS0tIEVrSDhwMTlmOUk2OVBMZ0ZsdnRF
            aVJDeDg1NmVDQkVGbkZuWHV2Q0tvNHMKNwaHwO2gTIF7d2Rq8PEcREbp+VRiDP5M
            Pa4LzXzOgeonfEzSg3rzZxc0/rYMYvlVHR6JUUjPNUqn5AtLVDkMyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T03:42:55Z"
    mac: ENC[AES256_GCM,data:D4pcsmHLVjvwfYuwH+nzXD3Dd73OSdMP2MblSbkNSjfW5zDi/OD2T7sagVEQhKuui26D6kubMSryUTN9KUr5pv7feyhFVtQSAc06PG+vlltG3gR4VF79ueeqnY9rHYXo2ZkrPAQoM0PmottR0an6SgNf8PGL7TGSmUw0sNaPXlo=,iv:kAdOuKPqCYeaL4fYjRC24NOKlGDgK0lRZveeU4RN4cU=,tag:ZKepzYU+Hn/Ddq9zXePAvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
