apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.sops.yaml
  - deployment-hubble-ui.yaml
  - service-hubble-ui.yaml
  - deployment-grafana.yaml
  - service-grafana.yaml
  - deployment-longhorn-ui.yaml
  - service-longhorn-ui.yaml
  - deployment-goldilocks.yaml
  - service-goldilocks.yaml
  - deployment-headlamp.yaml
  - service-headlamp.yaml
  - deployment-timer-counter.yaml
  - service-timer-counter.yaml
  - reference-grant.yaml
