apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.sops.yaml
  - deployment-harbor.yaml
  - service-harbor.yaml
  - deployment-hubble-ui.yaml
  - service-hubble-ui.yaml
  - deployment-grafana.yaml
  - service-grafana.yaml
  - deployment-headlamp.yaml
  - service-headlamp.yaml
  - deployment-dashboard.yaml
  - service-dashboard.yaml
  - deployment-kafka-console.yaml
  - service-kafka-console.yaml
  - deployment-metabase.yaml
  - service-metabase.yaml
  - deployment-cloudbeaver.yaml
  - service-cloudbeaver.yaml
  - deployment-bytebase.yaml
  - service-bytebase.yaml
  - deployment-dbx.yaml
  - service-dbx.yaml
  - reference-grant.yaml
