#ENC[AES256_GCM,data:Q1oAD+nry3yCrNWBLGh6fgBTIg2InofGNROXqDcTz9KkDsIZxUG/30SXMGCW7janPN1Z9O5f6LytD3v5B2ubv0pVcszyBvShlj97HTKy8Q==,iv:XiV3vZ7x4e2AB6mOEaVd6thEsKApZREiGfBY7QFoCy8=,tag:Wadx7TUkiOlLK7949vltNA==,type:comment]
#ENC[AES256_GCM,data:GIAC7m/raSR13WI2gzGffSB+7/4D6vSpeYYXS0QSZqmv0zImhzl+2kdYR9Za6kpmYsxqDCqyO0t3arvUF32ayF1GZR7M3CjcCNN4D3MaqQEvp192,iv:hBJlMcS8kiASCN2+1mzF0oHcu9kUWF31R5GEw9Wc78E=,tag:mMj1IetfdzaQRVWNrI3JsA==,type:comment]
#ENC[AES256_GCM,data:tEzFUD2dVahO/TXQNtLLUDt5nR2LWFwg5SofZE9aBh3U7MYNUw==,iv:1VyimGk7eBhCsXEAE7+7PRO3O/CS1dQD4FIO4WVxQQw=,tag:J4UZ1ielCLcPNSupUkbwgw==,type:comment]
apiVersion: ENC[AES256_GCM,data:Lb8=,iv:ARfL0rtV8eFGYoyjV0aIC4uZ/C36Ww/n1om2e4GLb7g=,tag:d8mYT4Id6RmFs6oSKLDUbg==,type:str]
kind: ENC[AES256_GCM,data:ZkYjhy9S,iv:lMgZAkQchA/rS2r0Oes3cKxARyD9xp6+oKs9rq1zMdg=,tag:z1EV6fBNblFS7Yav05YmVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:epYhZx58xjPbL+luhMODkzjcSr0=,iv:ayf0lyTi18FK3jwJUUioWj2xJzW0q/faVvhW0BXRm5Q=,tag:rnHBvv9t2JrKBtQg03IOkQ==,type:str]
    namespace: ENC[AES256_GCM,data:SCijtHU8/7pUqd3F,iv:CbGgyFlV9wf/U9W0f7IhaYLN49shFryIKcpzqnDwuwk=,tag:OkSPhQ3mx3rJ/xAf/qBIeg==,type:str]
type: ENC[AES256_GCM,data:yhLo/n3X,iv:JMNYlDGXK9t7TsnBgK6B42NGf1oR5H0nYbWKNK6z6Z0=,tag:lc99HzgO3417CV7KBHoG/A==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:sJrkRv5Hre76igGVcTw8LpCekJNoalSXRSg3xWsCBgZC7u4BzNvfJeKVbKyltmONmA7J9DZTwWZsmwWFMTd3ez+FlHZW/9bD,iv:q4/DUtPVZj1H254xLIN9yEtKFgPc2Cx/pJa4TClRytE=,tag:woVcrxwvYrpNJntHgdPt4w==,type:str]
    client-secret: ENC[AES256_GCM,data:eUUu3Ed4w7tqsfkZe/lGPwD6nRZzo/V2Jgw9i/WWj9ZQTSI=,iv:CewAub1nkPInnULM2COf5EZGFcwA6IyUOar4pEbv/VM=,tag:PxRCRrDlQ6kAr5QB/0n6Xg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:FcLcnrb34rHOr6ezWfgBTKPrZeG2B1PUu9fgndLC4ZmqElQWAdMMR94TvX0=,iv:D5D45ibvTdy9qLBA48r3+zX+kmfWhj984+2tAAGNVFY=,tag:Z52puIc0MuLIH+V0VaTriQ==,type:str]
sops:
    age:
        - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNd3FjS3J5aE5CWncyeHFi
            aUpJbHJXZlozTEsreTlwQ3l2K0FTVVM5aVdjClQra2hLVmhHYlZQQkFnWkl5V1NL
            andlNFZxNUhyeGo3NW9LcENNbGgzUXcKLS0tIGxIbTVTaWVoSnhQWGVScmlvUFJG
            dFdOdGcrQ2lMZXJUbkFkUDYwT2NKY0EKfqPC65d2X3G8EaC6i+19z4/pVHYkqbJ5
            YE6W0a/+55n78wkOf5p+AgleE02Xr8Gv7BG1WSX65fA53VJeyMzh7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T03:36:19Z"
    mac: ENC[AES256_GCM,data:giIGmLQnOxsVZVzxHEMn9RmVVkEScvbSztz24YE+v4OkZ6Iy9QVhQJe9A1JdvJsPk7morTw2HLCU+PxFRvZa44mxPdEzBxbUnQgG/qVXEoqNkoPwXdbPQ62wwVqJOFSo2rcXXUNWCKtad5mpQajAwyIXtVj7C1LqaGKMQzuchAI=,iv:5z6dyxICaLgF3HK8Crz9fVAQV+n8u4pGljHtqfVIULM=,tag:Ew/MjtNBuOMFXwQdwh7LMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
