apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-kafka-bridge
  namespace: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy-kafka-bridge
  ports:
    - port: 4180
      targetPort: 4180
