apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-dbx
  namespace: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy-dbx
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
      name: http