apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-timer-counter
  namespace: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy-timer-counter
  ports:
    - port: 4180
      targetPort: 4180
