apiVersion: ENC[AES256_GCM,data:B3s=,iv:WQlrG8/G77h/N3MN/vrY4Q5o8TwaDi8rBvmdQhQNq/w=,tag:aAVucNVCOFow/h5CKOgsHQ==,type:str]
kind: ENC[AES256_GCM,data:sGDRjrE5,iv:6IRrjS/eMKamclIfjYzQUA4IlAaXXktOBKeMdJyeIbQ=,tag:qBISK4pLQTNfscKvRwreNA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:6o0KYsPBkf+P9AjYZslpTXgG/mYOx8elwk+Y7thQ,iv:ZuE3BBwAi4X0F4tKA44IDNRWdZz+LU+i0mwnE7/RIGM=,tag:uXnovAn3U4jaOiaha008gg==,type:str]
  namespace: ENC[AES256_GCM,data:pC4LB9+t1LLq3yjipq9N,iv:scd5Mh4MYqVI8uVbOQWazX1tiA5fFMmvq/910tGcmfc=,tag:AYegVCFUzlnTlZ4nJAFcHA==,type:str]
type: ENC[AES256_GCM,data:cXgP4rG0,iv:AAybg8qzoHcEfxcEU3Ekvf3AF2CV+Syg/GyevN+6wnc=,tag:GjokQSV699QsyqSvz7dQVw==,type:str]
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KidOQBRGlv/2F4hAKkkeLprzW1Q=,iv:j0j1OPubZ2kGbRFikCRCGCy7WO98uAJ6cNH7bYWuhfo=,tag:LUSypZlIcrfzerRLyRb0Hg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EIRmfK8LzJFnxUu5/qRzIJObIYeBZt8wg3NmXZp5fwQuWIKElTWKbA==,iv:r+cFXnCmDhv3e0kze4FFkpVaCIKhPHhJs+iPgFmsxq0=,tag:8RjRUCQbpORguCVIGJlP3Q==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:K4oUYdnvyNfow76aBKBmu6NG0elVxg/18wI1ZuhSg5kKiCI=,iv:ca6TTX97lbbnKLSgDVI41yvMmUzMviOWXgPZHWedEJk=,tag:nzvks0p0XvJvaIEqLnVpCQ==,type:str]
  VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:Uf8Z/g0=,iv:EuEKKr9lyGdmsCb2M/K43DZ6dBw+9hZE9t6lL6bidPo=,tag:XnRNRs49aP2q9tCxbCcQ4A==,type:str]
sops:
  age:
    - recipient: age1pdqae3ffmt9rxtmn2758pxjqaaxnytg6mzx3wpepuhs7de2ttfkqk3z7hl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRk5xbjVjMmUwVVJkZnVY
        anZrS1NmWWwzZEdud29zSElBY25KRTJkSVJBCkNTbG4yQ0tnL0FwcEkxRnBid0pV
        SnlUVWNYM0UwVDF5TjBtUzhlOXhYaVUKLS0tICtnRmRKMHJIbG9JVGUxa0llNFFj
        RzJDalA0WWI2L3phY1k2VVN0UWdMOHMKl3vPPWJ2sPcRDOcZB5Ume8Cf7GVI9j1y
        QYxtenzF2DQbxJX0hlEbzE39opOh5uM/+d/lLR/idPnkeSY1BB66kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-26T13:17:34Z"
  mac: ENC[AES256_GCM,data:qtE1fgGp2MHSjhJNcuSg3gMrYX7ru9/4TA+gwN87NaRGD/Uz4zpMP3lbcyDp5mIM1MrRMLSfpv8arVPktpYk0XGkMrHu9I0uSfqvNxz75ulqIaeeEaQRkmZo6gZEVNEiMSiueKCgf4uOVw33qeSYt/CaC8i9WlazfauF3YBGSJQ=,iv:aKQGWJwGzsoAW8nNI5xdUYxas4TsmG3caEBvA7w47mo=,tag:6dzPLSLtfSkyJS75LwyLoA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
