---
apiVersion: v1
kind: Service
metadata:
  name: kafka-bridge
  namespace: kafka
  labels:
    app: kafka-bridge
spec:
  type: ClusterIP
  selector:
    app: kafka-bridge
  ports:
    - port: 8080
      targetPort: 8080
      name: http
